;; Sokoban, in the STRIPS subset the fd_adapter parser accepts.
;; Generated by fixtures/sokoban.py -- do not edit by hand.
;;
;; `clear` covers the player as well as the boxes, so "a cell holds at most one
;; thing" is a consequence of the action set rather than an assumption a reader
;; has to supply.  The deadlock carver leans on exactly that: it derives the
;; at-most-one facts itself from reachable pairs, and never sees the board.
;;
;; `adj ?from ?to ?d` is static -- no action adds or deletes it -- which is what
;; lets grounding discard the pushes a wall makes impossible (DECISIONS D-016),
;; and in turn what makes a corner provable: a box in one has no push instance
;; left to delete its position.
(define (domain sokoban)
  (:requirements :strips :typing)
  (:types cell box dir)
  (:predicates
    (at-player ?c - cell)
    (at ?b - box ?c - cell)
    (clear ?c - cell)
    (adj ?from - cell ?to - cell ?d - dir))

  (:action move
    :parameters (?from - cell ?to - cell ?d - dir)
    :precondition (and (at-player ?from) (clear ?to) (adj ?from ?to ?d))
    :effect (and (at-player ?to) (not (at-player ?from))
                 (clear ?from) (not (clear ?to))))

  (:action push
    :parameters (?p - cell ?from - cell ?to - cell ?b - box ?d - dir)
    :precondition (and (at-player ?p) (at ?b ?from) (clear ?to)
                       (adj ?p ?from ?d) (adj ?from ?to ?d))
    :effect (and (at-player ?from) (not (at-player ?p)) (clear ?p)
                 (at ?b ?to) (not (at ?b ?from))
                 (not (clear ?to)) (not (clear ?from)))))
