#!/usr/bin/env sh
# verify.sh -- A18 / agent/a18-scorer-at-run-end
# generated by .claude/skills/verify-gate at 2026-08-01T05:36:10Z; base 4c08ea6
#
# Every check runs even after one fails: a red run must print the whole
# checklist, not stop at the first red. Exit 0 only when every line is PASS.
#
#   sh verify.sh            (from anywhere -- it finds its own worktree root)
#   PYTHON=python3 sh verify.sh
set -u

ROOT=$(cd "$(dirname "$0")" && git rev-parse --show-toplevel) || exit 2
cd "$ROOT" || exit 2
PY=${PYTHON:-python}
export PY                       # `check` runs its command in `sh -c`, a new process
export PYTHONIOENCODING=utf-8   # this repo's prose is Chinese; consoles here are not UTF-8
PASS=0
FAIL=0
LOGDIR=$(mktemp -d 2>/dev/null || printf '%s' "${TMPDIR:-/tmp}/verify.$$")
mkdir -p "$LOGDIR" || exit 2

check() {
  _name=$1
  shift
  if sh -c "$*" >"$LOGDIR/out" 2>&1; then
    printf '[PASS] %s\n' "$_name"
    PASS=$((PASS + 1))
  else
    printf '[FAIL] %s\n' "$_name"
    tail -n 30 "$LOGDIR/out" | sed -e 's/^/       | /'
    FAIL=$((FAIL + 1))
  fi
}

printf '== verify.sh :: %s :: %s ==\n' 'A18' 'agent/a18-scorer-at-run-end'
check 'tests -- theoria-arm' 'cd theoria-arm && "$PY" -m pytest -q'
check 'MANIFEST hashes reproduce' '"$PY" .claude/skills/runs-archive/scripts/runs_archive.py check --run theoria-arm/runs/2026-08-01T045542Z-A18'
check 'boundary -- only theoria-arm changed' '"$PY" .claude/skills/verify-gate/scripts/guards.py boundary --base 4c08ea6be6ff480d9b7cfcd6be8bd17c2e9e3749 --territory theoria-arm'
check 'sealed pile untouched' '"$PY" .claude/skills/verify-gate/scripts/guards.py sealed --base 4c08ea6be6ff480d9b7cfcd6be8bd17c2e9e3749'
check 'credential never entered a tracked file' '"$PY" .claude/skills/verify-gate/scripts/guards.py secret --base 4c08ea6be6ff480d9b7cfcd6be8bd17c2e9e3749'
check 'delivered: theoria-arm/runs/2026-08-01T045542Z-A18/MANIFEST.json' 'test -e '\''theoria-arm/runs/2026-08-01T045542Z-A18/MANIFEST.json'\'''

printf -- '-- %s/%s green' "$PASS" "$((PASS + FAIL))"
if [ "$FAIL" -eq 0 ]; then
  printf '\n'
  exit 0
fi
printf '  <<< NOT GREEN (%s red)\n' "$FAIL"
exit 1
