;; Sokoban level three-b. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #....#
;;   #....#
;;   #....#
;;   ######
;;
;; player c34; boxes b1@c12, b2@c22, b3@c23; goals b1@c33, b2@c14, b3@c31
(define (problem sokoban-three-b)
  (:domain sokoban)
  (:objects
    c11 c12 c13 c14 c21 c22 c23 c24 c31 c32 c33 c34 - cell
    b1 b2 b3 - box
    down left right up - dir)
  (:init
    (at b1 c12)
    (at b2 c22)
    (at b3 c23)
    (at-player c34)
    (clear c11)
    (clear c13)
    (clear c14)
    (clear c21)
    (clear c24)
    (clear c31)
    (clear c32)
    (clear c33)
    (adj c11 c12 right)
    (adj c11 c21 down)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c12 c22 down)
    (adj c13 c12 left)
    (adj c13 c14 right)
    (adj c13 c23 down)
    (adj c14 c13 left)
    (adj c14 c24 down)
    (adj c21 c11 up)
    (adj c21 c22 right)
    (adj c21 c31 down)
    (adj c22 c12 up)
    (adj c22 c21 left)
    (adj c22 c23 right)
    (adj c22 c32 down)
    (adj c23 c13 up)
    (adj c23 c22 left)
    (adj c23 c24 right)
    (adj c23 c33 down)
    (adj c24 c14 up)
    (adj c24 c23 left)
    (adj c24 c34 down)
    (adj c31 c21 up)
    (adj c31 c32 right)
    (adj c32 c22 up)
    (adj c32 c31 left)
    (adj c32 c33 right)
    (adj c33 c23 up)
    (adj c33 c32 left)
    (adj c33 c34 right)
    (adj c34 c24 up)
    (adj c34 c33 left))
  (:goal (and (at b1 c33) (at b2 c14) (at b3 c31))))
