;; Sokoban level rnd0001. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #.##.#
;;   #....#
;;   #....#
;;   #....#
;;   ######
;;
;; player c23; boxes b1@c22, b2@c44, b3@c14, b4@c43; goals b1@c34, b2@c11, b3@c42, b4@c24
(define (problem sokoban-rnd0001)
  (:domain sokoban-guarded)
  (:objects
    c11 c14 c21 c22 c23 c24 c31 c32 c33 c34 c41 c42 c43 c44 - cell
    b1 b2 b3 b4 - box
    down left right up - dir)
  (:init
    (at-player c23)
    (at b1 c22)
    (at b2 c44)
    (at b3 c14)
    (at b4 c43)
    (clear c11)
    (clear c21)
    (clear c24)
    (clear c31)
    (clear c32)
    (clear c33)
    (clear c34)
    (clear c41)
    (clear c42)
    (adj c11 c21 down)
    (adj c14 c24 down)
    (adj c21 c31 down)
    (adj c21 c22 right)
    (adj c21 c11 up)
    (adj c22 c32 down)
    (adj c22 c21 left)
    (adj c22 c23 right)
    (adj c23 c33 down)
    (adj c23 c22 left)
    (adj c23 c24 right)
    (adj c24 c34 down)
    (adj c24 c23 left)
    (adj c24 c14 up)
    (adj c31 c41 down)
    (adj c31 c32 right)
    (adj c31 c21 up)
    (adj c32 c42 down)
    (adj c32 c31 left)
    (adj c32 c33 right)
    (adj c32 c22 up)
    (adj c33 c43 down)
    (adj c33 c32 left)
    (adj c33 c34 right)
    (adj c33 c23 up)
    (adj c34 c44 down)
    (adj c34 c33 left)
    (adj c34 c24 up)
    (adj c41 c42 right)
    (adj c41 c31 up)
    (adj c42 c41 left)
    (adj c42 c43 right)
    (adj c42 c32 up)
    (adj c43 c42 left)
    (adj c43 c44 right)
    (adj c43 c33 up)
    (adj c44 c43 left)
    (adj c44 c34 up)
    ;; deadlock theorems, compiled in by bench/compile_theorems.py
    (dead1 b1 c11)
    (dead1 b1 c24)
    (dead1 b2 c44)
    (dead1 b3 c14)
    (dead1 b4 c43)
)
  (:goal (and (at b1 c34) (at b2 c11) (at b3 c42) (at b4 c24))))
