"""The concept-birth timeline, assembled from the run rather than remembered.

P-8 asks for two books snapshotted before and after every theorize so the
timeline of a concept's arrival is raw material rather than reconstruction.
This turns those snapshots, the adjudication logs and the surprise register
into one ordered account:

    which surprise fired -> what the desk was asked -> what it changed ->
    what certify said next

`THEORIZE_LOG.md`'s narrative is written by hand on top of this; the point of
generating the skeleton is that no revision can be quietly left out of it.

    python -m tools.timeline --slug <run slug>
"""

import argparse
import difflib
import json
import os
import sys
from typing import Any, Dict, List, Optional

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import _bootstrap                                     # noqa: F401  (sys.path)


def _load(path: str, default=None):
    if not os.path.exists(path):
        return default
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def _jsonl(path: str) -> List[Dict[str, Any]]:
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def _read(path: str) -> str:
    if not os.path.exists(path):
        return ""
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def diff(before: str, after: str, name: str) -> str:
    lines = list(difflib.unified_diff(
        before.splitlines(), after.splitlines(),
        fromfile="%s (before)" % name, tofile="%s (after)" % name, lineterm="",
        n=1))
    return "\n".join(lines) if lines else "(unchanged)"


def build(slug: str) -> str:
    run_dir = _bootstrap.path("runs", slug)
    theorize = _load(os.path.join(run_dir, "theorize.json"), []) or []
    certify = _load(os.path.join(run_dir, "certify.json"), []) or []
    surprises = _jsonl(os.path.join(run_dir, "surprises.jsonl"))
    desk_log = _load(os.path.join(run_dir, "desk_log.json"), []) or []
    snapshots_dir = os.path.join(run_dir, "books", "snapshots")

    out: List[str] = []
    out.append("# Concept-birth timeline — `%s`" % slug)
    out.append("")
    out.append("Generated by `tools/timeline.py` from the run's own snapshots, "
               "adjudication logs and surprise register. Every theorize round "
               "appears here whether or not it changed anything; a round that "
               "changed nothing is a measurement.")
    out.append("")

    out.append("## The surprises, in the order they fired")
    out.append("")
    if not surprises:
        out.append("None. With no surprise the loop never reaches a model "
                   "(constraint 8), so a run with zero surprises and zero "
                   "model calls is the constraint holding, not the loop "
                   "failing to start.")
    else:
        out.append("| # | kind | family | book | step | detail |")
        out.append("|---|---|---|---|---|---|")
        for item in surprises:
            out.append("| %s | `%s` | %s | `%s` | %s | %s |" % (
                item.get("seq"), item.get("kind"), item.get("family"),
                item.get("book"), item.get("step_idx"),
                str(item.get("detail", ""))[:160].replace("|", "\\|")))
    out.append("")

    out.append("## The desk's calls")
    out.append("")
    if not desk_log:
        out.append("None.")
    else:
        out.append("| call | beat | label | ms | usd | in | out | step |")
        out.append("|---|---|---|---|---|---|---|---|")
        for entry in desk_log:
            usage = entry.get("usage") or {}
            out.append("| %s | %s | %s | %s | %.4f | %s | %s | %s |" % (
                entry.get("call"), entry.get("beat"), entry.get("label") or "",
                entry.get("elapsed_ms"), float(entry.get("cli_cost_usd") or 0),
                usage.get("input_tokens"), usage.get("output_tokens"),
                entry.get("step_idx")))
    out.append("")

    out.append("## Revisions")
    out.append("")
    snaps = sorted(os.listdir(snapshots_dir)) if os.path.isdir(snapshots_dir) else []
    for i, snap in enumerate(snaps):
        here = os.path.join(snapshots_dir, snap)
        out.append("### %s" % snap)
        out.append("")
        if i == 0:
            theory = _read(os.path.join(here, "theory.dsl"))
            out.append("```")
            out.append(theory.strip() or "(the manual did not exist yet)")
            out.append("```")
        else:
            prev = os.path.join(snapshots_dir, snaps[i - 1])
            body = diff(_read(os.path.join(prev, "theory.dsl")),
                        _read(os.path.join(here, "theory.dsl")), "theory.dsl")
            out.append("```diff")
            out.append(body)
            out.append("```")
        out.append("")

    out.append("## Adjudications, round by round")
    out.append("")
    for i, report in enumerate(theorize, start=1):
        out.append("### theorize %d" % i)
        out.append("")
        rounds = report.get("rounds") or []
        out.append("Calls: %s. Compile: %s." % (
            report.get("calls"),
            "ok" if report.get("ok") else "REFUSED"))
        for entry in rounds:
            if entry.get("compile_errors"):
                out.append("")
                out.append("Attempt %s was refused by the compiler:" % entry.get("attempt"))
                out.append("")
                out.append("```json")
                out.append(json.dumps(entry["compile_errors"], indent=1,
                                      sort_keys=True))
                out.append("```")
        log = report.get("log") or []
        if log:
            out.append("")
            out.append("| id | subject | verdict | as | why |")
            out.append("|---|---|---|---|---|")
            for entry in log:
                out.append("| %s | %s | **%s** | %s | %s |" % (
                    entry.get("id"), str(entry.get("subject", ""))[:60],
                    entry.get("verdict"), entry.get("as", ""),
                    str(entry.get("why", ""))[:260].replace("|", "\\|")
                    .replace("\n", " ")))
        certify_after = certify[i] if i < len(certify) else None
        if certify_after:
            cheap = (certify_after.get("cheap") or {}).get("checks") or {}
            out.append("")
            out.append("certify then said: responsibility %s (%s unexplained "
                       "cells), replay %s (%s), constraint 9 %s, proof layer %s."
                       % (_tick((cheap.get("responsibility") or {}).get("ok")),
                          (cheap.get("responsibility") or {}).get("cells_unexplained"),
                          _tick((cheap.get("replay") or {}).get("ok")),
                          (cheap.get("replay") or {}).get("detail"),
                          _tick((cheap.get("unambiguous") or {}).get("ok")),
                          "available" if certify_after.get("proof_layer_available")
                          else "UNAVAILABLE"))
        out.append("")

    out.append("## Expressivity ledger")
    out.append("")
    out.append("Every `E-` verdict the desk recorded: something the world said "
               "that the DSL could not.")
    out.append("")
    rows = [entry for report in theorize for entry in (report.get("log") or [])
            if str(entry.get("id", "")).startswith("E-")]
    if not rows:
        out.append("None recorded.")
    else:
        out.append("| id | wanted | verdict | note |")
        out.append("|---|---|---|---|")
        for entry in rows:
            out.append("| %s | %s | %s | %s |" % (
                entry.get("id"), str(entry.get("subject", ""))[:70],
                entry.get("verdict"),
                str(entry.get("why", ""))[:300].replace("|", "\\|")
                .replace("\n", " ")))
    out.append("")
    return "\n".join(out) + "\n"


def _tick(value) -> str:
    return {True: "PASS", False: "**FAIL**"}.get(value, "n/a")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--slug", required=True)
    ap.add_argument("--out", default=None)
    args = ap.parse_args(argv)
    text = build(args.slug)
    path = args.out or _bootstrap.path("runs", args.slug, "TIMELINE.md")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
