#!/usr/bin/env python
"""verify-gate -- generate and run the ticket's verify.sh.

  verify_gate.py gen  [--territory ...] [--run ...] [--check "name::cmd"] ...
  verify_gate.py run  [--verify <path>]

`gen` writes a POSIX-sh gate that runs the territory suite, the MANIFEST hash
check, and the three repo-wide guards (territory boundary, sealed pile,
credential sealing). Every check runs even after one fails, because a red run
has to show the whole checklist -- not the first stop.

`run` executes it. On Windows it finds the MSYS/Git-Bash `bash` rather than
WSL's, whose filesystem view is not this repo's.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _fleet import (  # noqa: E402
    detect_test_cmd, die, git, iso, load_ctx, rel, repo_root, save_ctx, say,
    utc_now, write_text,
)

HEADER = """#!/usr/bin/env sh
# verify.sh -- {prompt_id} / {branch}
# generated by .claude/skills/verify-gate at {t}; base {base}
#
# Every check runs even after one fails: a red run must print the whole
# checklist, not stop at the first red. Exit 0 only when every line is PASS.
#
#   sh verify.sh            (from anywhere -- it finds its own worktree root)
#   PYTHON=python3 sh verify.sh
set -u

ROOT=$(cd "$(dirname "$0")" && git rev-parse --show-toplevel) || exit 2
cd "$ROOT" || exit 2
PY=${{PYTHON:-python}}
export PY                       # `check` runs its command in `sh -c`, a new process
export PYTHONIOENCODING=utf-8   # this repo's prose is Chinese; consoles here are not UTF-8
PASS=0
FAIL=0
LOGDIR=$(mktemp -d 2>/dev/null || printf '%s' "${{TMPDIR:-/tmp}}/verify.$$")
mkdir -p "$LOGDIR" || exit 2

check() {{
  _name=$1
  shift
  if sh -c "$*" >"$LOGDIR/out" 2>&1; then
    printf '[PASS] %s\\n' "$_name"
    PASS=$((PASS + 1))
  else
    printf '[FAIL] %s\\n' "$_name"
    tail -n 30 "$LOGDIR/out" | sed -e 's/^/       | /'
    FAIL=$((FAIL + 1))
  fi
}}

printf '== verify.sh :: %s :: %s ==\\n' '{prompt_id}' '{branch}'
"""

FOOTER = """
printf -- '-- %s/%s green' "$PASS" "$((PASS + FAIL))"
if [ "$FAIL" -eq 0 ]; then
  printf '\\n'
  exit 0
fi
printf '  <<< NOT GREEN (%s red)\\n' "$FAIL"
exit 1
"""


def shq(s):
    return "'" + str(s).replace("'", "'\\''") + "'"


def warn_or_pin_eol(root, out, pin):
    """A shell script committed on a `core.autocrlf=true` checkout comes back
    with CRLF, and `sh` then fails on `\\r` with an error that names the wrong
    line. Pin eol=lf for it, or at least say so out loud."""
    rc, val, _ = git(["config", "--get", "core.autocrlf"], cwd=root)
    if val.strip().lower() not in ("true", "input"):
        return
    rel_out = rel(out, root)
    rc, attr, _ = git(["check-attr", "text", "eol", "--", rel_out], cwd=root)
    if "eol: lf" in attr:
        return
    ga = out.parent / ".gitattributes"
    line = "%s text eol=lf\n" % out.name
    if pin:
        prev = read_text_safe(ga)
        if line not in prev:
            write_text(ga, (prev + ("" if prev.endswith("\n") or not prev else "\n")) + line)
        say("pinned eol=lf for %s in %s" % (out.name, rel(ga, root)))
        return
    say("WARNING: core.autocrlf=%s and nothing pins eol for %s." % (val.strip(), rel_out))
    say("         Committed as-is it will come back with CRLF and `sh` will fail on \\r.")
    say("         Re-run with --pin-eol, or add `%s` to %s." % (line.strip(), rel(ga, root)))


def read_text_safe(p):
    try:
        return Path(p).read_text(encoding="utf-8")
    except OSError:
        return ""


def cmd_gen(args, root):
    ctx = load_ctx(root)
    territory = args.territory or ctx.get("territory")
    base = args.base or ctx.get("base_commit")
    branch = args.branch or ctx.get("branch") or "(no branch recorded)"
    prompt_id = args.prompt_id or ctx.get("prompt_id") or "(no prompt id)"
    if not territory:
        die("--territory is required (no ticket context; run fleet-branch-ritual first)")
    if not base:
        die("--base is required: the guards diff this branch against the commit it forked from")

    run_dir = args.run or ctx.get("run_dir")
    lines = []

    # 1 -- the territory's own suite
    test_cmd = detect_test_cmd(root / territory)
    if args.test_cmd:
        lines.append("check %s %s" % (shq("tests -- %s" % territory), shq(args.test_cmd)))
    elif test_cmd:
        lines.append("check %s %s" % (
            shq("tests -- %s" % territory),
            shq('cd %s && "$PY" -m pytest -q' % territory)))
    else:
        lines.append("printf '[ -- ] tests -- %s :: no suite in this territory (不适用)\\n'"
                     % territory)

    # 2 -- the archive still reproduces
    ra = ".claude/skills/runs-archive/scripts/runs_archive.py"
    if run_dir and (root / ra).exists():
        lines.append("check %s %s" % (
            shq("MANIFEST hashes reproduce"),
            shq('"$PY" %s check --run %s' % (ra, run_dir))))
    elif run_dir:
        lines.append("printf '[ -- ] MANIFEST :: runs-archive skill not installed\\n'")

    # 3 -- the three red lines
    g = ".claude/skills/verify-gate/scripts/guards.py"
    allow = "".join(" --allow %s" % shq(a) for a in (args.allow or []))
    lines.append("check %s %s" % (
        shq("boundary -- only %s changed" % territory),
        shq('"$PY" %s boundary --base %s --territory %s%s' % (g, base, territory, allow))))
    lines.append("check %s %s" % (
        shq("sealed pile untouched"),
        shq('"$PY" %s sealed --base %s%s' % (g, base, allow))))
    lines.append("check %s %s" % (
        shq("credential never entered a tracked file"),
        shq('"$PY" %s secret --base %s' % (g, base))))

    # 4 -- what the工单 promised
    for path in args.require or []:
        lines.append("check %s %s" % (shq("delivered: %s" % path), shq("test -e %s" % shq(path))))
    for spec in args.check or []:
        if "::" not in spec:
            die('--check expects "name::command", got %r' % spec)
        name, cmd = spec.split("::", 1)
        lines.append("check %s %s" % (shq(name.strip()), shq(cmd.strip())))

    out = Path(args.out) if args.out else (root / territory / "verify.sh")
    if not out.is_absolute():
        out = root / out
    text = HEADER.format(prompt_id=prompt_id, branch=branch, base=base[:7],
                         t=iso(utc_now(args.now))) + "\n".join(lines) + "\n" + FOOTER
    write_text(out, text)
    try:
        os.chmod(out, 0o755)
    except OSError:
        pass
    warn_or_pin_eol(root, out, args.pin_eol)
    ctx["verify_sh"] = rel(out, root)
    save_ctx(ctx, cwd=root)
    say(rel(out, root))
    say("  %d check(s). Run it:  python .claude/skills/verify-gate/scripts/verify_gate.py run"
        % (len([l for l in lines if l.startswith("check ")])))
    return 0


# --------------------------------------------------------------------------


def find_sh():
    """A POSIX shell that shares this repo's filesystem view. On Windows the
    `bash` on PATH is often WSL's, which cannot see C:\\Users the same way --
    prefer Git for Windows / MSYS."""
    env = os.environ.get("FLEET_SH")
    if env:
        return env
    if os.name != "nt":
        return shutil.which("sh") or shutil.which("bash") or "sh"
    candidates = []
    if os.environ.get("MSYSTEM"):
        candidates += [shutil.which("bash"), shutil.which("sh")]
    candidates += [
        r"C:\Program Files\Git\bin\bash.exe",
        r"C:\Program Files\Git\usr\bin\sh.exe",
        r"C:\Program Files (x86)\Git\bin\bash.exe",
        shutil.which("bash"),
        shutil.which("sh"),
    ]
    for c in candidates:
        if not c or not Path(c).exists():
            continue
        try:
            p = subprocess.run([c, "-c", "uname -s"], stdout=subprocess.PIPE,
                               stderr=subprocess.DEVNULL, timeout=30)
            name = p.stdout.decode("utf-8", "replace").strip().upper()
        except (OSError, subprocess.SubprocessError):
            continue
        if any(tag in name for tag in ("MINGW", "MSYS", "CYGWIN")):
            return c
    die("no MSYS/Git-Bash shell found. Install Git for Windows, or set FLEET_SH to a "
        "shell that can see this repo's paths (WSL's bash cannot).")


def cmd_run(args, root):
    ctx = load_ctx(root)
    target = args.verify or ctx.get("verify_sh")
    if not target:
        die("no verify.sh recorded. Generate one first: verify_gate.py gen")
    p = Path(target)
    if not p.is_absolute():
        p = root / p
    if not p.exists():
        die("verify.sh not found at %s" % p)
    sh = find_sh()
    posix = str(p).replace("\\", "/")
    say("running %s  (%s)" % (rel(p, root), sh))
    proc = subprocess.run([sh, posix], cwd=str(root))
    if proc.returncode == 0:
        say("")
        say("green. 收工 -> skill handoff-close")
    else:
        say("")
        say("NOT GREEN. The checklist above is the report: fix the red lines, or if one")
        say("cannot be fixed inside this ticket, carry it verbatim into RUN_STATE 的 gap")
        say("清单 and PARTNER_SYNC 的阻塞 line. 验收标准是合同,不许自降。")
    return proc.returncode


def main(argv=None):
    ap = argparse.ArgumentParser(description="Theoria fleet: verify gate")
    ap.add_argument("--now", default=None)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("gen", help="write verify.sh")
    p.add_argument("--territory", default=None)
    p.add_argument("--base", default=None)
    p.add_argument("--branch", default=None)
    p.add_argument("--prompt-id", default=None)
    p.add_argument("--run", default=None, help="run dir whose MANIFEST must reproduce")
    p.add_argument("--out", default=None, help="default <territory>/verify.sh")
    p.add_argument("--test-cmd", default=None, help="override the detected test command")
    p.add_argument("--require", action="append", help="path the工单 promised; asserts it exists")
    p.add_argument("--check", action="append", help='extra check, "name::shell command"')
    p.add_argument("--allow", action="append", help="path exempt from the boundary/sealed guards")
    p.add_argument("--pin-eol", action="store_true",
                   help="write `verify.sh text eol=lf` into the sibling .gitattributes")
    p.set_defaults(fn=cmd_gen)

    p = sub.add_parser("run", help="execute verify.sh and print the checklist")
    p.add_argument("--verify", default=None)
    p.set_defaults(fn=cmd_run)

    args = ap.parse_args(argv)
    return args.fn(args, repo_root(Path.cwd()))


if __name__ == "__main__":
    raise SystemExit(main())
