#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""freeze/u3.py — E1, the U3 attainment evaluator (主终点一 · U3 达成率).

This is the computation code whose absence STATS_RULES.md §9.14 registers as a
launch precondition ("U3 达成率本身没有任何计算代码 … 未实现不得开跑").  It decides,
for one run directory, whether that run ATTAINED U3 under the frozen judgment.

The frozen judgment (STATS_RULES.md §1.2, verbatim anchor, 冻结时不得改)
-----------------------------------------------------------------------
A game attains U3 iff the Theoria arm produced 至少一条机器可查的定理 such that

  (a) the Lean form generated by theory-compiler COMPILES;
  (b) `#print axioms` reports only WHITELISTED axioms —
        allow  : propext, Quot.sound          (实测必需, G1 收窄记录 2026-07-29)
        never  : sorryAx                      (未完成的证明)
        never  : Lean.ofReduceBool            (native_decide bypasses the kernel)
        anything else, including Classical.choice, FAILS (b).  Classical.choice
        is additionally FLAGGED, because §1.2 preregisters a sensitivity
        listing of games that needed it ("不是禁止, 是记账");
  (c) the statement is NON-VACUOUS (§1.2.1) — not the cold-start-a3 D-A3-007
        class (`I := true`).

U3 = 证得动吗 (Theoria.md:262), NOT winning: §5.7.5 states U3 从产出物裁, does not
require the episode to finish, and does not look at `levels_completed`.  The
cheap layer's replay result is therefore REPORTED but is NOT a criterion.

Strict readings taken here (documented for the freeze territory)
----------------------------------------------------------------
1. DECLARED REFUSAL.  A run whose expensive layer says
   "not attempted: the enumerative development … too big" produced NO theorem.
   The frozen sentence requires the arm to *produce* one, so the run reads
   NOT-ATTAINED.  It is not excluded: §1.2 fixes the denominator and §1.2.1
   rules 缺格局留在分母、计为未达成 — so even on the most generous reading the
   verdict is the same; only the *label* could differ (whether it is a 缺格 g
   for §1.4's inconclusive arithmetic).  §1.2.1 defines 缺格 as "拿检查器去跑
   臂产出的那条定理跑不动" — a theorem exists but cannot be checked.  A refusal
   produced no theorem, so strictly it is NOT a 缺格; and §9.20 forbids g from
   entering adjudication arithmetic until its game-level, prior criterion
   lands.  We therefore emit verdict=not_attained, label=declared_refusal,
   flags.gap_candidate_g=true — the flag surfaces the ambiguity, changes no
   arithmetic.
2. UNDISCHARGED / UNREPORTED.  A Lean file that exists but was never run
   ("lean not on PATH"), or ran green but left no `#print axioms` evidence,
   fails strictly ((a) resp. (b) unverified is unmet, 机器可查 means checked,
   not checkable-in-principle).  `--probe` can re-run Lean to recover.
3. NON-VACUITY residual.  The executable (c) checks here are:
     * a static constant scan of `def I` / `def Goal` (catches the D-A3-007
       class with no Lean install), and
     * definitional-constancy probes under `--probe` (`fun _ => rfl` /
       `trivial`) that machine-check constancy in Lean itself.
   These catch every definitionally-constant invariant, which strictly
   includes the frozen negative control (cold-start-a3/theory/
   generated_l1_vacuous).  They do NOT decide §1.2.1's full two-witness
   predicate for a syntactically disguised constant; that residual is
   reported in `criteria.c_residuals`, never silently passed.  For
   unsolvable-kind theorems the §1.2.1 sub-checks (a)(b) are discharged by
   the co-theorems (inv_init, goal_break), (c)(d) by recorded run evidence
   (trace transitions > 0; a recorded solvable sibling / plan), each with its
   provenance named.  A theorem kind with no implemented check fails (c)
   closed, it does not pass open.

Evidence adapters (all offline, read-only; no API, no network)
--------------------------------------------------------------
  * theoria-arm run dir      : certify.json records / transfer.json .certify
  * a0-spike territory       : artifacts/a0_report.json  (+ artifacts/A0.lean)
  * cold-start-a0 territory  : artifacts/certify_lean_generated_theory_lean.json
                               (+ theory/generated/theory.lean)
  * bare theory dir          : theory.lean evaluated live (needs Lean)

CLI
---
  python u3.py eval  <dir> [--probe] [--json]
  python u3.py sweep <dir>... [--probe] [--md OUT] [--json OUT]

Exit codes: eval — 0 attained, 3 not attained, 2 error.  sweep — always 0
unless it cannot write its output (the table is the product, not the verdict).
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional

# ----------------------------------------------------------------- frozen sets

ALLOWED_AXIOMS = frozenset({"propext", "Quot.sound"})
NEVER_AXIOMS = frozenset({"sorryAx", "Lean.ofReduceBool"})
CLASSICAL = "Classical.choice"

# Label stages, least to most advanced.  A run's label is the most advanced
# stage any of its certify records reached; attainment needs the last one.
STAGES = [
    "unreadable",          # artefact present but not parseable (e.g. mid-write)
    "no_evidence",         # no proof-layer artefact at all
    "no_proof_layer",      # proof layer recorded unavailable, no reason class
    "declared_refusal",    # explicit "not attempted: … too big" refusal
    "undischarged",        # Lean file exists, never run (no binary)
    "failing_obligation",  # Lean rejected the file — (a) fails
    "axioms_unreported",   # compiled, but no #print axioms evidence — (b) unverified
    "axiom_violation",     # compiled, axioms outside the whitelist — (b) fails
    "vacuous",             # compiled + whitelisted, but statement is vacuous — (c) fails
    "discharged",          # (a) ∧ (b) ∧ (c) for at least one theorem — ATTAINED
]
_STAGE_RANK = {s: i for i, s in enumerate(STAGES)}

REFUSAL_PREFIX = "not attempted:"


# ------------------------------------------------------------------- axioms (b)

_AXIOM_LINE = re.compile(
    r"'(?P<name>[^']+)'\s+(?:does not depend on any axioms"
    r"|depends on axioms:\s*\[(?P<axioms>[^\]]*)\])")


def parse_axiom_lines(text_or_lines) -> Dict[str, List[str]]:
    """Parse `#print axioms` output lines into {theorem: [axiom, ...]}."""
    if isinstance(text_or_lines, str):
        lines = text_or_lines.splitlines()
    else:
        lines = list(text_or_lines)
    out: Dict[str, List[str]] = {}
    for line in lines:
        m = _AXIOM_LINE.search(str(line))
        if not m:
            continue
        raw = m.group("axioms")
        axioms = [a.strip() for a in raw.split(",") if a.strip()] if raw else []
        out[m.group("name")] = axioms
    return out


def judge_axioms(axioms: List[str]) -> Dict[str, Any]:
    """Frozen (b): pass iff every reported axiom is whitelisted."""
    bad = [a for a in axioms if a not in ALLOWED_AXIOMS]
    never = [a for a in axioms if a in NEVER_AXIOMS]
    return {
        "ok": not bad,
        "axioms": axioms,
        "outside_whitelist": bad,
        "never_allowed": never,
        "classical_choice_needed": CLASSICAL in axioms,
    }


# ------------------------------------------------------------------ kinds / (c)

INVARIANT_KIND = "invariant"
UNSOLVABLE_KIND = "unsolvable"
PRUNE_KIND = "prune"
UNKNOWN_KIND = "unknown"


def classify_theorem(name: str) -> str:
    n = name.lower()
    if n.startswith(("inv_", "invariant")) or n == "inv":
        return INVARIANT_KIND
    if n.startswith(("unsolvable", "goal_break", "no_goal")):
        return UNSOLVABLE_KIND
    if n.startswith(("prune", "deadlock")):
        return PRUNE_KIND
    return UNKNOWN_KIND


_DEF_RE = re.compile(
    r"^def\s+(?P<name>I|Goal)\s*(?:\(\s*\w+\s*:\s*(?P<sty>[\w.]+)\s*\))?"
    r"\s*:\s*(?P<rty>Bool|Prop)\s*:=\s*(?P<body>.+)$",
    re.M)

_CONSTANT_BODIES = {"true", "false", "True", "False"}


def scan_defs(lean_src: str) -> Dict[str, Dict[str, Any]]:
    """Static scan of `def I` / `def Goal`: is the body a literal constant?"""
    out: Dict[str, Dict[str, Any]] = {}
    for m in _DEF_RE.finditer(lean_src):
        body = m.group("body").strip()
        out[m.group("name")] = {
            "state_type": m.group("sty"),
            "ret_type": m.group("rty"),
            "body": body,
            "constant": body if body in _CONSTANT_BODIES else None,
        }
    return out


def _probe_texts(state_type: str, ret_type: str) -> List[Dict[str, str]]:
    """Definitional-constancy probes.  A probe that ELABORATES proves the
    invariant is definitionally constant of that polarity → vacuous."""
    if ret_type == "Bool":
        return [
            {"polarity": "true",
             "text": "example : ∀ s : %s, I s = true := fun _ => rfl"
                     % state_type},
            {"polarity": "false",
             "text": "example : ∀ s : %s, I s = false := fun _ => rfl"
                     % state_type},
        ]
    return [
        {"polarity": "true",
         "text": "example : ∀ s : %s, I s := fun _ => trivial"
                 % state_type},
        {"polarity": "false",
         "text": "example : ∀ s : %s, ¬ I s := fun _ h => h"
                 % state_type},
    ]


def find_lean() -> Optional[str]:
    for cand in ("lean",):
        hit = shutil.which(cand)
        if hit:
            return hit
    elan = Path.home() / ".elan" / "bin" / "lean.exe"
    if elan.exists():
        return str(elan)
    return None


def run_lean(lean_bin: str, path: Path, timeout: int = 900) -> Dict[str, Any]:
    try:
        proc = subprocess.run([lean_bin, str(path)], capture_output=True,
                              text=True, encoding="utf-8", errors="replace",
                              timeout=timeout)
        return {"returncode": proc.returncode, "stdout": proc.stdout,
                "stderr": proc.stderr}
    except Exception as exc:  # noqa: BLE001 — a crashed checker is a verdict input
        return {"returncode": -1, "stdout": "",
                "stderr": "%s: %s" % (type(exc).__name__, exc)}


def probe_constancy(lean_bin: str, lean_src_path: Path,
                    scratch: Optional[Path] = None) -> Dict[str, Any]:
    """Run the constancy probes against a COPY of the source.  Only meaningful
    if the source itself already compiles (else every probe 'fails')."""
    src = lean_src_path.read_text(encoding="utf-8")
    defs = scan_defs(src)
    info = defs.get("I")
    if not info or not info.get("state_type"):
        return {"probed": False, "reason": "no `def I (s : T) : Bool|Prop :=` found"}
    results = []
    tmpdir = Path(tempfile.mkdtemp(prefix="u3probe_", dir=scratch))
    try:
        for probe in _probe_texts(info["state_type"], info["ret_type"]):
            probe_file = tmpdir / ("probe_%s.lean" % probe["polarity"])
            probe_file.write_text(src + "\n\n-- u3 (c) constancy probe\n"
                                  + probe["text"] + "\n", encoding="utf-8")
            res = run_lean(lean_bin, probe_file)
            results.append({"polarity": probe["polarity"],
                            "elaborated": res["returncode"] == 0})
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
    constant = next((r["polarity"] for r in results if r["elaborated"]), None)
    return {"probed": True, "results": results, "constant": constant}


# ------------------------------------------------------------- per-theorem (c)

def judge_nonvacuity(kind: str, defs: Dict[str, Dict[str, Any]],
                     probe_result: Optional[Dict[str, Any]],
                     recorded: Dict[str, Any]) -> Dict[str, Any]:
    """Frozen (c), per §1.2.1, executable extent; fails CLOSED on unknowns.

    `recorded` carries run-record evidence for the unsolvable-kind sub-checks:
      trace_transitions      : int  — >0 discharges §1.2.1-unsolvable (c)
      solvable_witness       : bool — discharges §1.2.1-unsolvable (d)
      theorems_present       : set of theorem names in the development
      recorded_non_vacuous   : Optional[bool] — the pipeline's own recorded bit,
                               reported as provenance, never sufficient alone
    """
    residuals: List[str] = []
    inv = defs.get("I", {})
    inv_constant = inv.get("constant")
    if probe_result and probe_result.get("probed"):
        if probe_result.get("constant"):
            inv_constant = inv_constant or ("true" if probe_result["constant"] == "true"
                                            else "false")
    else:
        residuals.append("constancy probe not run (static scan only)")

    if kind == INVARIANT_KIND:
        if not inv:
            return {"ok": False, "why": "no `def I` found to check", "residuals": residuals}
        if inv_constant is not None:
            return {"ok": False,
                    "why": "invariant is constant `%s` — D-A3-007 class, "
                           "fails §1.2.1 (two-witness)" % inv_constant,
                    "residuals": residuals}
        residuals.append("full §1.2.1 two-witness check deferred (§9.2 residual): "
                         "non-constancy established %s"
                         % ("definitionally (probe)" if probe_result
                            and probe_result.get("probed") else "statically only"))
        return {"ok": True, "why": "invariant not constant", "residuals": residuals}

    if kind == UNSOLVABLE_KIND:
        subs = {}
        present = set(recorded.get("theorems_present") or [])
        subs["a_inv_at_init"] = "inv_init" in present or "inv_all" in present
        subs["b_goals_excluded"] = "goal_break" in present or "unsolvable" in present
        goal = defs.get("Goal", {})
        goal_constant = goal.get("constant")
        if goal_constant in ("false", "False"):
            return {"ok": False, "why": "Goal is constant false — empty goal set, "
                                        "fails §1.2.1-unsolvable (d)",
                    "residuals": residuals, "sub_checks": subs}
        transitions = recorded.get("trace_transitions") or 0
        subs["c_init_has_action"] = bool(transitions > 0)
        if transitions > 0:
            subs["c_provenance"] = "recorded trace: %d transitions" % transitions
        subs["d_goal_nonempty"] = bool(recorded.get("solvable_witness"))
        if recorded.get("solvable_witness"):
            subs["d_provenance"] = recorded.get("solvable_witness_provenance",
                                                "recorded solvable witness")
        if inv_constant is not None:
            return {"ok": False,
                    "why": "invariant is constant `%s` — the unsolvability rests "
                           "on a vacuous I" % inv_constant,
                    "residuals": residuals, "sub_checks": subs}
        ok = all(subs.get(k) for k in
                 ("a_inv_at_init", "b_goals_excluded",
                  "c_init_has_action", "d_goal_nonempty"))
        why = ("§1.2.1-unsolvable (a)-(d) discharged" if ok else
               "missing sub-check: %s" % [k for k in
                                          ("a_inv_at_init", "b_goals_excluded",
                                           "c_init_has_action", "d_goal_nonempty")
                                          if not subs.get(k)])
        return {"ok": ok, "why": why, "residuals": residuals, "sub_checks": subs}

    # prune-kind and unknown-kind: no implemented check → fail closed (§9.2).
    return {"ok": False,
            "why": "no executable §1.2.1 check implemented for kind `%s` — "
                   "fails closed" % kind,
            "residuals": residuals}


# ------------------------------------------------------------ verdict assembly

def _verdict(label: str, criteria: Dict[str, Any], evidence: Dict[str, Any],
             flags: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    return {
        "verdict": "attained" if label == "discharged" else "not_attained",
        "label": label,
        "criteria": criteria,
        "evidence": evidence,
        "flags": flags or {},
    }


def judge_development(compiles: bool, axiom_report: Dict[str, List[str]],
                      lean_src: Optional[str],
                      probe_result: Optional[Dict[str, Any]],
                      recorded: Dict[str, Any],
                      evidence: Dict[str, Any]) -> Dict[str, Any]:
    """Judge one Lean development that reached the compile stage."""
    if not compiles:
        return _verdict("failing_obligation",
                        {"a_compiles": False, "b_axioms": None, "c_nonvacuous": None},
                        evidence)
    if not axiom_report:
        return _verdict("axioms_unreported",
                        {"a_compiles": True, "b_axioms": None, "c_nonvacuous": None,
                         "note": "compiled, but no `#print axioms` evidence; "
                                 "strict (b) unmet — re-run with --probe"},
                        evidence)
    defs = scan_defs(lean_src) if lean_src else {}
    per_theorem: Dict[str, Any] = {}
    flags: Dict[str, Any] = {"classical_choice_needed": False}
    any_pass = False
    c_residuals: List[str] = []
    for name, axioms in sorted(axiom_report.items()):
        b = judge_axioms(axioms)
        if b["classical_choice_needed"]:
            flags["classical_choice_needed"] = True
        kind = classify_theorem(name)
        c = (judge_nonvacuity(kind, defs, probe_result, recorded)
             if b["ok"] else {"ok": None, "why": "not reached — (b) failed"})
        if c.get("residuals"):
            c_residuals.extend("%s: %s" % (name, r) for r in c["residuals"])
        per_theorem[name] = {"kind": kind, "b": b, "c": c}
        if b["ok"] and c.get("ok"):
            any_pass = True
    if not lean_src:
        c_residuals.append("no Lean source available — (c) judged from recorded "
                           "evidence only")
    if any_pass:
        label = "discharged"
    elif any(t["b"]["ok"] for t in per_theorem.values()):
        label = "vacuous"
    else:
        label = "axiom_violation"
    return _verdict(label,
                    {"a_compiles": True,
                     "b_axioms": {n: t["b"]["ok"] for n, t in per_theorem.items()},
                     "c_nonvacuous": {n: t["c"].get("ok")
                                      for n, t in per_theorem.items()},
                     "per_theorem": per_theorem,
                     "c_residuals": c_residuals},
                    evidence, flags)


# ----------------------------------------------------------------- adapters

def _load_json(path: Path) -> Optional[Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 — a live leg may be mid-write; unreadable is a verdict
        return None


def eval_arm_record(record: Dict[str, Any], run_dir: Path,
                    probe: bool, lean_bin: Optional[str]) -> Dict[str, Any]:
    """One certify.json record from a theoria-arm run."""
    exp = record.get("expensive") or {}
    evidence = {"source": "certify record", "kind": "arm_certify",
                "cheap_green": record.get("cheap_green"),
                "proof_layer_available": record.get("proof_layer_available"),
                "detail": exp.get("detail")}
    if not exp.get("available"):
        detail = (exp.get("detail") or "").strip().lower()
        if detail.startswith(REFUSAL_PREFIX):
            return _verdict("declared_refusal",
                            {"a_compiles": None, "b_axioms": None,
                             "c_nonvacuous": None,
                             "note": "no theorem was produced; strict reading "
                                     "of §1.2 (see module docstring, item 1)"},
                            evidence,
                            {"gap_candidate_g": True})
        return _verdict("no_proof_layer",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None},
                        evidence)
    # Proof layer available.
    lean_file = exp.get("lean_file")
    if "returncode" not in exp:
        # a Lean file exists but lean was never run
        if probe and lean_bin and lean_file and Path(lean_file).exists():
            return eval_lean_source(Path(lean_file), probe=True,
                                    lean_bin=lean_bin, recorded={})
        return _verdict("undischarged",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None,
                         "note": exp.get("detail")},
                        evidence)
    compiles = exp.get("returncode") == 0 and bool(exp.get("ok"))
    axiom_report = parse_axiom_lines(exp.get("stdout") or "")
    lean_src = None
    if lean_file and Path(lean_file).exists():
        try:
            lean_src = Path(lean_file).read_text(encoding="utf-8")
        except OSError:
            lean_src = None
    probe_result = None
    if probe and lean_bin and compiles and lean_file and Path(lean_file).exists():
        if not axiom_report:
            live = eval_lean_source(Path(lean_file), probe=True,
                                    lean_bin=lean_bin, recorded={})
            live["evidence"]["source"] = "certify record + live re-run of %s" % lean_file
            return live
        probe_result = probe_constancy(lean_bin, Path(lean_file))
    return judge_development(compiles, axiom_report, lean_src, probe_result,
                             {}, evidence)


def eval_lean_source(lean_path: Path, probe: bool, lean_bin: Optional[str],
                     recorded: Dict[str, Any]) -> Dict[str, Any]:
    """Live evaluation of a Lean development (the §9.2 checker path)."""
    evidence = {"source": str(lean_path), "kind": "lean_source_live"}
    if not lean_bin:
        return _verdict("undischarged",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None,
                         "note": "no Lean binary found; the obligations are "
                                 "stated and undischarged"},
                        evidence)
    src = lean_path.read_text(encoding="utf-8")
    theorems = re.findall(r"^theorem\s+(\w+)", src, re.M)
    recorded = dict(recorded)
    recorded.setdefault("theorems_present", theorems)
    with tempfile.TemporaryDirectory(prefix="u3lean_") as td:
        aug = Path(td) / lean_path.name
        extra = "\n".join("#print axioms %s" % t for t in theorems)
        aug.write_text(src + "\n\n-- u3 axiom audit\n" + extra + "\n",
                       encoding="utf-8")
        res = run_lean(lean_bin, aug)
    compiles = res["returncode"] == 0
    axiom_report = {t: a for t, a in
                    parse_axiom_lines(res["stdout"]).items() if t in theorems}
    probe_result = None
    if probe and compiles:
        probe_result = probe_constancy(lean_bin, lean_path)
    out = judge_development(compiles, axiom_report, src, probe_result,
                            recorded, evidence)
    if not compiles:
        out["evidence"]["stderr_tail"] = (res["stderr"] or res["stdout"])[-800:]
    return out


def eval_a0_report(report: Dict[str, Any], territory: Path,
                   probe: bool, lean_bin: Optional[str]) -> Dict[str, Any]:
    """a0-spike style: artifacts/a0_report.json `lean` block."""
    lean_block = report.get("lean") or {}
    evidence = {"source": str(territory / "artifacts" / "a0_report.json"),
                "kind": "a0_report"}
    if not lean_block.get("available"):
        return _verdict("no_proof_layer",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None},
                        evidence)
    lean_path = territory / "artifacts" / "A0.lean"
    recorded = {
        "theorems_present": lean_block.get("theorems") or [],
        "trace_transitions": (report.get("explore") or {}).get("transitions", 0),
        "recorded_non_vacuous": lean_block.get("non_vacuous"),
    }
    grading = report.get("grading") or {}
    solvable = [lvl for lvl, g in grading.items() if g.get("actually_solvable")]
    if solvable:
        recorded["solvable_witness"] = True
        recorded["solvable_witness_provenance"] = (
            "a0_report grading: level(s) %s actually solvable with recorded plan"
            % ",".join(sorted(solvable)))
    if probe and lean_bin and lean_path.exists():
        return eval_lean_source(lean_path, probe=True, lean_bin=lean_bin,
                                recorded=recorded)
    compiles = bool(lean_block.get("compiles"))
    if lean_block.get("uses_sorry") or lean_block.get("sorry_in_source"):
        compiles = False  # a sorried development is not a discharged one
    axiom_report = parse_axiom_lines(lean_block.get("axioms") or [])
    lean_src = lean_path.read_text(encoding="utf-8") if lean_path.exists() else None
    return judge_development(compiles, axiom_report, lean_src, None,
                             recorded, evidence)


def eval_lean_cert(cert: Dict[str, Any], territory: Path,
                   probe: bool, lean_bin: Optional[str]) -> Dict[str, Any]:
    """cold-start-a0 style: certify_lean_generated_theory_lean.json."""
    evidence = {"source": str(territory / "artifacts" /
                              "certify_lean_generated_theory_lean.json"),
                "kind": "lean_cert_json"}
    if not cert.get("available"):
        return _verdict("no_proof_layer",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None},
                        evidence)
    lean_rel = (cert.get("file") or "").replace("\\", "/")
    lean_path = (territory / lean_rel) if lean_rel else None
    recorded: Dict[str, Any] = {}
    if probe and lean_bin and lean_path and lean_path.exists():
        return eval_lean_source(lean_path, probe=True, lean_bin=lean_bin,
                                recorded=recorded)
    compiles = bool(cert.get("green")) and cert.get("returncode") == 0 \
        and not cert.get("sorries")
    axiom_report = {r.get("name"): r.get("axioms", [])
                    for r in (cert.get("axiom_reports") or []) if r.get("name")}
    if not axiom_report:
        axiom_report = parse_axiom_lines(cert.get("output") or [])
    lean_src = (lean_path.read_text(encoding="utf-8")
                if lean_path and lean_path.exists() else None)
    recorded["theorems_present"] = list(axiom_report)
    return judge_development(compiles, axiom_report, lean_src, None,
                             recorded, evidence)


# ------------------------------------------------------------- run-dir driver

def evaluate(path: Path, probe: bool = False,
             lean_bin: Optional[str] = None) -> Dict[str, Any]:
    """Evaluate one directory.  Returns the verdict dict (plus `run`, `game`)."""
    path = Path(path)
    if probe and lean_bin is None:
        lean_bin = find_lean()
    game = None
    run_meta = _load_json(path / "run.json") if (path / "run.json").exists() else None
    if isinstance(run_meta, dict):
        game = run_meta.get("game_id")

    best: Optional[Dict[str, Any]] = None

    def consider(v: Dict[str, Any]) -> None:
        nonlocal best
        if best is None or _STAGE_RANK[v["label"]] > _STAGE_RANK[best["label"]]:
            best = v

    # 1. a0-spike style
    a0_report_path = path / "artifacts" / "a0_report.json"
    if a0_report_path.exists():
        report = _load_json(a0_report_path)
        if report is None:
            consider(_verdict("unreadable", {}, {"source": str(a0_report_path)}))
        else:
            consider(eval_a0_report(report, path, probe, lean_bin))

    # 2. cold-start-a0 style
    cert_path = path / "artifacts" / "certify_lean_generated_theory_lean.json"
    if cert_path.exists():
        cert = _load_json(cert_path)
        if cert is None:
            consider(_verdict("unreadable", {}, {"source": str(cert_path)}))
        else:
            consider(eval_lean_cert(cert, path, probe, lean_bin))

    # 3. theoria-arm run dir
    certify_path = path / "certify.json"
    if certify_path.exists():
        records = _load_json(certify_path)
        if records is None:
            consider(_verdict("unreadable", {}, {"source": str(certify_path)}))
        elif isinstance(records, list) and records:
            for rec in records:
                if isinstance(rec, dict):
                    consider(eval_arm_record(rec, path, probe, lean_bin))
        else:
            consider(_verdict("no_evidence",
                              {"note": "certify.json is empty — the certify "
                                       "stage left no records"},
                              {"source": str(certify_path), "kind": "arm_certify"}))
    transfer_path = path / "transfer.json"
    if transfer_path.exists() and (best is None
                                   or _STAGE_RANK[best["label"]]
                                   <= _STAGE_RANK["no_evidence"]):
        transfer = _load_json(transfer_path)
        cert_block = (transfer or {}).get("certify") if isinstance(transfer, dict) else None
        if isinstance(cert_block, dict):
            if cert_block.get("proof_layer_available"):
                consider(_verdict("undischarged",
                                  {"note": "transfer.certify records the proof layer "
                                           "available but carries no Lean result"},
                                  {"source": str(transfer_path),
                                   "kind": "arm_transfer",
                                   "cheap_green": cert_block.get("cheap_green")}))
            else:
                consider(_verdict("no_proof_layer",
                                  {"a_compiles": None, "b_axioms": None,
                                   "c_nonvacuous": None},
                                  {"source": str(transfer_path),
                                   "kind": "arm_transfer",
                                   "cheap_green": cert_block.get("cheap_green")}))

    # 4. bare theory dir with a Lean development.  Compiling is criterion (a),
    # so Lean is looked up even without --probe; --probe only adds the
    # constancy probes.
    lean_file = path / "theory.lean"
    if best is None and lean_file.exists():
        consider(eval_lean_source(lean_file, probe=probe,
                                  lean_bin=lean_bin or find_lean(),
                                  recorded={}))

    if best is None:
        best = _verdict("no_evidence",
                        {"note": "no recognised proof-layer artefact in %s" % path},
                        {"source": str(path)})
    best["run"] = str(path)
    best["game"] = game
    return best


# -------------------------------------------------------------------- sweep

def expand_targets(paths: List[Path]) -> List[Path]:
    out: List[Path] = []
    for p in paths:
        p = Path(p)
        if not p.is_dir():
            continue
        # A runs/ container: expand to children that look like run dirs.
        children = [c for c in sorted(p.iterdir()) if c.is_dir()]
        has_own = any((p / n).exists() for n in
                      ("certify.json", "transfer.json", "theory.lean")) \
            or (p / "artifacts").is_dir()
        if has_own:
            out.append(p)
        elif children and p.name == "runs":
            out.extend(children)
        elif (p / "runs").is_dir() and (p / "artifacts").is_dir() is False:
            out.extend(c for c in sorted((p / "runs").iterdir()) if c.is_dir())
        else:
            out.append(p)
    return out


def to_markdown(rows: List[Dict[str, Any]]) -> str:
    lines = [
        "| run | game | verdict | label | (a) | (b) | (c) | evidence | flags |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    def _tri(v: Any) -> str:
        if v is True:
            return "pass"
        if v is False:
            return "FAIL"
        if isinstance(v, dict):
            vals = set(v.values())
            if vals == {True}:
                return "pass"
            if True in vals:
                return "mixed"
            if False in vals:
                return "FAIL"
            return "—"
        return "—"

    for r in rows:
        c = r.get("criteria") or {}
        flags = r.get("flags") or {}
        flag_bits = [k for k, v in flags.items() if v]
        lines.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
            Path(r["run"]).name, r.get("game") or "—",
            "**attained**" if r["verdict"] == "attained" else "not attained",
            r["label"],
            _tri(c.get("a_compiles")), _tri(c.get("b_axioms")),
            _tri(c.get("c_nonvacuous")),
            (r.get("evidence") or {}).get("kind", "—"),
            ",".join(flag_bits) or "—"))
    n_att = sum(1 for r in rows if r["verdict"] == "attained")
    lines.append("")
    lines.append("**%d / %d directories attained U3** (per-directory, not the "
                 "E1 per-game rate; the frozen denominator 19/12 applies only "
                 "to the sealed campaign)." % (n_att, len(rows)))
    return "\n".join(lines)


# ------------------------------------------------------------- path hygiene

def sanitize_paths(obj: Any) -> Any:
    """Strip machine-naming prefixes from every string in a verdict structure.

    tools/check_locations.py: no tracked artefact may record where its builder
    stood.  Sweep outputs land in freeze/runs/ (run scope), so they are written
    clean instead of allowlisted: the repo root (worktree or main tree) becomes
    `<repo>` and the home directory becomes `<home>`.
    """
    here = Path(__file__).resolve()
    roots: List[str] = []
    wt_root = here.parents[1]           # <root>/freeze/u3.py
    roots.append(str(wt_root))
    # a .worktrees checkout: the main tree is two levels above the checkout
    parts = wt_root.parts
    if ".worktrees" in parts:
        main_root = Path(*parts[:parts.index(".worktrees")])
        roots.append(str(main_root))
    roots.append(str(Path.home()))
    subs: List[tuple] = []
    for i, r in enumerate(sorted(set(roots), key=len, reverse=True)):
        tag = "<home>" if Path(r) == Path.home() else "<repo>"
        subs.append((r.replace("\\", "/"), tag))
        subs.append((r.replace("/", "\\"), tag))

    def walk(x: Any) -> Any:
        if isinstance(x, str):
            for frm, to in subs:
                x = x.replace(frm, to)
            return x
        if isinstance(x, list):
            return [walk(v) for v in x]
        if isinstance(x, dict):
            return {k: walk(v) for k, v in x.items()}
        return x

    return walk(obj)


# ---------------------------------------------------------------------- CLI

def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(prog="u3.py", description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)

    ev = sub.add_parser("eval", help="judge one run/territory/theory directory")
    ev.add_argument("path", type=Path)
    ev.add_argument("--probe", action="store_true",
                    help="run Lean live: axiom audit + constancy probes")
    ev.add_argument("--lean", default=None, help="path to the lean binary")
    ev.add_argument("--json", action="store_true", dest="as_json")

    sw = sub.add_parser("sweep", help="judge many directories, emit a table")
    sw.add_argument("paths", nargs="+", type=Path)
    sw.add_argument("--probe", action="store_true")
    sw.add_argument("--lean", default=None)
    sw.add_argument("--md", type=Path, default=None, help="write Markdown table")
    sw.add_argument("--json", type=Path, default=None, dest="json_out",
                    help="write full verdicts as JSON")

    args = ap.parse_args(argv)
    lean_bin = args.lean or (find_lean() if args.probe else None)

    if args.cmd == "eval":
        v = evaluate(args.path, probe=args.probe, lean_bin=lean_bin)
        if args.as_json:
            print(json.dumps(v, indent=1, ensure_ascii=False, sort_keys=True))
        else:
            print("%s  %s  [%s]" % (v["verdict"].upper(), v["run"], v["label"]))
        return 0 if v["verdict"] == "attained" else 3

    rows = [evaluate(t, probe=args.probe, lean_bin=lean_bin)
            for t in expand_targets(args.paths)]
    rows = sanitize_paths(rows)
    md = to_markdown(rows)
    if args.md:
        args.md.write_text(md + "\n", encoding="utf-8")
    if args.json_out:
        args.json_out.write_text(
            json.dumps(rows, indent=1, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8")
    print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
