#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""freeze/u3.py — E1, the U3 attainment evaluator (主终点一 · U3 达成率).

This is the computation code whose absence STATS_RULES.md §9.14 registers as a
launch precondition ("U3 达成率本身没有任何计算代码 … 未实现不得开跑").  It decides,
for one run directory, whether that run ATTAINED U3 under the frozen judgment.

The frozen judgment (STATS_RULES.md §1.2, verbatim anchor, 冻结时不得改)
-----------------------------------------------------------------------
A game attains U3 iff the Theoria arm produced 至少一条机器可查的定理 such that

  (a) the Lean form generated by theory-compiler COMPILES;
  (b) `#print axioms` reports only WHITELISTED axioms —
        allow  : propext, Quot.sound          (实测必需, G1 收窄记录 2026-07-29)
        never  : sorryAx                      (未完成的证明)
        never  : Lean.ofReduceBool            (native_decide bypasses the kernel)
        anything else, including Classical.choice, FAILS (b).  Classical.choice
        is additionally FLAGGED, because §1.2 preregisters a sensitivity
        listing of games that needed it ("不是禁止, 是记账");
  (c) the statement is NON-VACUOUS (§1.2.1) — not the cold-start-a3 D-A3-007
        class (`I := true`).

U3 = 证得动吗 (Theoria.md:262), NOT winning: §5.7.5 states U3 从产出物裁, does not
require the episode to finish, and does not look at `levels_completed`.  The
cheap layer's replay result is therefore REPORTED but is NOT a criterion.

Strict readings taken here (documented for the freeze territory)
----------------------------------------------------------------
1. DECLARED REFUSAL.  A run whose expensive layer says
   "not attempted: the enumerative development … too big" produced NO theorem.
   The frozen sentence requires the arm to *produce* one, so the run reads
   NOT-ATTAINED.  It is not excluded: §1.2 fixes the denominator and §1.2.1
   rules 缺格局留在分母、计为未达成 — so even on the most generous reading the
   verdict is the same; only the *label* could differ (whether it is a 缺格 g
   for §1.4's inconclusive arithmetic).  §1.2.1 defines 缺格 as "拿检查器去跑
   臂产出的那条定理跑不动" — a theorem exists but cannot be checked.  A refusal
   produced no theorem, so strictly it is NOT a 缺格; and §9.20 forbids g from
   entering adjudication arithmetic until its game-level, prior criterion
   lands.  We therefore emit verdict=not_attained, label=declared_refusal,
   flags.gap_candidate_g=true — the flag surfaces the ambiguity, changes no
   arithmetic.
2. UNDISCHARGED / UNREPORTED.  A Lean file that exists but was never run
   ("lean not on PATH"), or ran green but left no `#print axioms` evidence,
   fails strictly ((a) resp. (b) unverified is unmet, 机器可查 means checked,
   not checkable-in-principle).  `--probe` can re-run Lean to recover.
3. NON-VACUITY residual.  The executable (c) checks here are:
     * a static constant scan of `def I` / `def Goal` (catches the D-A3-007
       class with no Lean install), and
     * definitional-constancy probes under `--probe` (`fun _ => rfl` /
       `trivial`) that machine-check constancy in Lean itself.
   These catch every definitionally-constant invariant, which strictly
   includes the frozen negative control (cold-start-a3/theory/
   generated_l1_vacuous).  They do NOT decide §1.2.1's full two-witness
   predicate for a syntactically disguised constant; that residual is
   reported in `criteria.c_residuals`, never silently passed.  For
   unsolvable-kind theorems the §1.2.1 sub-checks (a)(b) are discharged by
   the co-theorems (inv_init, goal_break), (c)(d) by recorded run evidence
   (trace transitions > 0; a recorded solvable sibling / plan), each with its
   provenance named.  A theorem kind with no implemented check fails (c)
   closed, it does not pass open.

Evidence adapters (all offline, read-only; no API, no network)
--------------------------------------------------------------
  * theoria-arm run dir      : certify.json records / transfer.json .certify
  * a0-spike territory       : artifacts/a0_report.json  (+ artifacts/A0.lean)
  * cold-start-a0 territory  : artifacts/certify_lean_generated_theory_lean.json
                               (+ theory/generated/theory.lean)
  * bare theory dir          : theory.lean evaluated live (needs Lean)

CLI
---
  python u3.py eval  <dir> [--probe] [--json]
  python u3.py sweep <dir>... [--probe] [--md OUT] [--json OUT]

Exit codes: eval — 0 attained, 3 not attained, 2 error.  sweep — always 0
unless it cannot write its output (the table is the product, not the verdict).
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set

try:                                    # `python -m freeze.u3` and `python u3.py`
    from freeze import theorem_shape as _shape
except ImportError:                     # pragma: no cover - direct-script fallback
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from freeze import theorem_shape as _shape

# ----------------------------------------------------------------- frozen sets

ALLOWED_AXIOMS = frozenset({"propext", "Quot.sound"})
NEVER_AXIOMS = frozenset({"sorryAx", "Lean.ofReduceBool"})
CLASSICAL = "Classical.choice"

# Label stages, least to most advanced.  A run's label is the most advanced
# stage any of its certify records reached; attainment needs the last one.
STAGES = [
    "unreadable",          # artefact present but not parseable (e.g. mid-write)
    "no_evidence",         # no proof-layer artefact at all
    "no_proof_layer",      # proof layer recorded unavailable, no reason class
    "declared_refusal",    # explicit "not attempted: … too big" refusal
    "undischarged",        # Lean file exists, never run (no binary)
    "failing_obligation",  # Lean rejected the file — (a) fails
    "axioms_unreported",   # compiled, but no #print axioms evidence — (b) unverified
    "axiom_violation",     # compiled, axioms outside the whitelist — (b) fails
    "vacuous",             # (c) CHECKED and refuted — the manual proved a tautology
    "unclassified",        # (c) NOT CHECKED — E1 does not know this kind of assertion
    "discharged",          # (a) ∧ (b) ∧ (c) for at least one theorem — ATTAINED
]

# `vacuous` and `unclassified` are the two verdicts one word used to carry
# (exam → freeze, 2026-08-01, F1).  They are not interchangeable:
#
#   vacuous       an ACCUSATION about the manual.  §1.2.1's check ran and said
#                 no: the invariant is constant, the pattern is satisfied by
#                 nothing, the goal set is empty.  Action: the arm must prove
#                 something else.
#   unclassified  a CONFESSION about this adjudicator.  The statement's shape
#                 is outside the fragment §1.2.1 writes a requirement for, so
#                 no check ran.  Action: extend E1, or narrow §1.2 on purpose.
#
# Both are `not_attained` — the arithmetic is unchanged, and fails-closed still
# fails closed.  `unclassified` ranks ABOVE `vacuous` because a development that
# was never checked may yet attain once a check exists, while a refuted one will
# not; the rank orders "how close did this come", not "how bad is it".
_STAGE_RANK = {s: i for i, s in enumerate(STAGES)}

REFUSAL_PREFIX = "not attempted:"


# ------------------------------------------------------------------- axioms (b)

_AXIOM_LINE = re.compile(
    r"'(?P<name>[^']+)'\s+(?:does not depend on any axioms"
    r"|depends on axioms:\s*\[(?P<axioms>[^\]]*)\])")


def parse_axiom_lines(text_or_lines) -> Dict[str, List[str]]:
    """Parse `#print axioms` output lines into {theorem: [axiom, ...]}."""
    if isinstance(text_or_lines, str):
        lines = text_or_lines.splitlines()
    else:
        lines = list(text_or_lines)
    out: Dict[str, List[str]] = {}
    for line in lines:
        m = _AXIOM_LINE.search(str(line))
        if not m:
            continue
        raw = m.group("axioms")
        axioms = [a.strip() for a in raw.split(",") if a.strip()] if raw else []
        out[m.group("name")] = axioms
    return out


def judge_axioms(axioms: List[str]) -> Dict[str, Any]:
    """Frozen (b): pass iff every reported axiom is whitelisted."""
    bad = [a for a in axioms if a not in ALLOWED_AXIOMS]
    never = [a for a in axioms if a in NEVER_AXIOMS]
    return {
        "ok": not bad,
        "axioms": axioms,
        "outside_whitelist": bad,
        "never_allowed": never,
        "classical_choice_needed": CLASSICAL in axioms,
    }


# ------------------------------------------------------------------ kinds / (c)

INVARIANT_KIND = _shape.INVARIANT_KIND
UNSOLVABLE_KIND = _shape.UNSOLVABLE_KIND
PRUNE_KIND = _shape.PRUNE_KIND
POINT_KIND = _shape.POINT_KIND
WITNESS_KIND = _shape.WITNESS_KIND
UNCLASSIFIED_KIND = _shape.UNCLASSIFIED_KIND

#: Retained only so a reader can see what the old prefix matcher WOULD have
#: said.  It is reported as `name_hint` next to every theorem and is read by
#: nothing that decides anything — see `theorem_shape.name_hint`.
classify_theorem = _shape.name_hint


_DEF_RE = re.compile(
    r"^def\s+(?P<name>[A-Za-z_][A-Za-z0-9_']*)"
    r"\s*(?:\(\s*\w+\s*:\s*(?P<sty>[\w.]+)\s*\))?"
    r"\s*:\s*(?P<rty>Bool|Prop)\s*:=\s*(?P<body>.+)$",
    re.M)

_CONSTANT_BODIES = {"true", "false", "True", "False"}


def scan_defs(lean_src: str) -> Dict[str, Dict[str, Any]]:
    """Static scan of every single-line `def P (s : T) : Bool|Prop := body`:
    is the body a literal constant?  Formerly restricted to the names `I` and
    `Goal`; the predicate a theorem is about is now read off the theorem, so
    the scan may not assume what it is called."""
    out: Dict[str, Dict[str, Any]] = {}
    for m in _DEF_RE.finditer(lean_src):
        body = m.group("body").strip()
        out[m.group("name")] = {
            "state_type": m.group("sty"),
            "ret_type": m.group("rty"),
            "body": body,
            "constant": body if body in _CONSTANT_BODIES else None,
        }
    return out


def _probe_texts(state_type: str, ret_type: str, pred: str = "I") -> List[Dict[str, str]]:
    """Definitional-constancy probes.  A probe that ELABORATES proves the
    predicate is definitionally constant of that polarity → vacuous."""
    if ret_type == "Bool":
        return [
            {"polarity": "true",
             "text": "example : ∀ s : %s, %s s = true := fun _ => rfl"
                     % (state_type, pred)},
            {"polarity": "false",
             "text": "example : ∀ s : %s, %s s = false := fun _ => rfl"
                     % (state_type, pred)},
        ]
    return [
        {"polarity": "true",
         "text": "example : ∀ s : %s, %s s := fun _ => trivial"
                 % (state_type, pred)},
        {"polarity": "false",
         "text": "example : ∀ s : %s, ¬ %s s := fun _ h => h"
                 % (state_type, pred)},
    ]


def find_lean() -> Optional[str]:
    for cand in ("lean",):
        hit = shutil.which(cand)
        if hit:
            return hit
    elan = Path.home() / ".elan" / "bin" / "lean.exe"
    if elan.exists():
        return str(elan)
    return None


def run_lean(lean_bin: str, path: Path, timeout: int = 900) -> Dict[str, Any]:
    try:
        proc = subprocess.run([lean_bin, str(path)], capture_output=True,
                              text=True, encoding="utf-8", errors="replace",
                              timeout=timeout)
        return {"returncode": proc.returncode, "stdout": proc.stdout,
                "stderr": proc.stderr}
    except Exception as exc:  # noqa: BLE001 — a crashed checker is a verdict input
        return {"returncode": -1, "stdout": "",
                "stderr": "%s: %s" % (type(exc).__name__, exc)}


def probe_constancy(lean_bin: str, lean_src_path: Path,
                    scratch: Optional[Path] = None,
                    pred: str = "I") -> Dict[str, Any]:
    """Run the constancy probes against a COPY of the source.  Only meaningful
    if the source itself already compiles (else every probe 'fails')."""
    src = lean_src_path.read_text(encoding="utf-8")
    defs = scan_defs(src)
    info = defs.get(pred)
    if not info or not info.get("state_type"):
        return {"probed": False, "pred": pred,
                "reason": "no `def %s (s : T) : Bool|Prop :=` found" % pred}
    results = []
    tmpdir = Path(tempfile.mkdtemp(prefix="u3probe_", dir=scratch))
    try:
        for probe in _probe_texts(info["state_type"], info["ret_type"], pred):
            probe_file = tmpdir / ("probe_%s.lean" % probe["polarity"])
            probe_file.write_text(src + "\n\n-- u3 (c) constancy probe\n"
                                  + probe["text"] + "\n", encoding="utf-8")
            res = run_lean(lean_bin, probe_file)
            results.append({"polarity": probe["polarity"],
                            "elaborated": res["returncode"] == 0})
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
    constant = next((r["polarity"] for r in results if r["elaborated"]), None)
    return {"probed": True, "pred": pred, "results": results, "constant": constant}


# ------------------------------------------------------------- per-theorem (c)

class Prober:
    """Lazily answers "is predicate `P` definitionally constant?".

    Accepts the legacy single-probe dict (which probed `I` and nothing else),
    a {pred: result} map, and/or a callable that runs a fresh probe.  Results
    are memoised so a wide development is not recompiled once per predicate.
    """

    def __init__(self, probe_result: Any = None,
                 run: Optional[Callable[[str], Optional[Dict[str, Any]]]] = None,
                 budget: int = 4):
        self._cache: Dict[str, Optional[Dict[str, Any]]] = {}
        self._run = run
        self._budget = budget
        if isinstance(probe_result, dict):
            if "probed" in probe_result:
                self._cache[probe_result.get("pred") or "I"] = probe_result
            else:
                self._cache.update(probe_result)

    def __call__(self, pred: Optional[str]) -> Optional[Dict[str, Any]]:
        if not pred:
            return None
        if pred in self._cache:
            return self._cache[pred]
        if self._run is None or self._budget <= 0:
            return None
        self._budget -= 1
        try:
            res = self._run(pred)
        except Exception:  # noqa: BLE001 — a crashed probe is "not probed"
            res = None
        self._cache[pred] = res
        return res

    def ran(self) -> bool:
        return any(bool(v) and v.get("probed") for v in self._cache.values())


def _constancy(pred: Optional[str], defs: Dict[str, Dict[str, Any]],
               prober: Optional[Prober], residuals: List[str]) -> Optional[str]:
    """`"true"` / `"false"` if `pred` is a literal or definitional constant."""
    if not pred:
        return None
    info = defs.get(pred, {})
    const = info.get("constant")
    res = prober(pred) if prober else None
    if res and res.get("probed"):
        if res.get("constant"):
            const = const or res["constant"]
    else:
        residuals.append("constancy probe not run for `%s` (static scan only)" % pred)
    if pred not in defs:
        residuals.append("`%s` has no single-line `def` this scan can read; "
                         "non-constancy is not established statically" % pred)
    return const


def _mentions_constant(thm: "_shape.Theorem", dev: "_shape.Development") -> bool:
    return any(re.search(r"(?<![\w.])%s(?![\w])" % re.escape(c), thm.statement)
               for c in dev.constants)


def judge_nonvacuity(thm: "_shape.Theorem", dev: "_shape.Development",
                     defs: Dict[str, Dict[str, Any]],
                     prober: Optional[Prober],
                     recorded: Dict[str, Any],
                     axiom_ok: Callable[[str], bool]) -> Dict[str, Any]:
    """Frozen (c), per §1.2.1, keyed on WHAT THE THEOREM PROVES.

    Three-valued on purpose (exam → freeze F1):

      ok = True   §1.2.1's requirement for this kind of assertion is discharged
      ok = False  it ran and FAILED — the manual proved a tautology (`vacuous`)
      ok = None   §1.2.1 defines no requirement for this shape, so nothing ran
                  (`unclassified`).  Still not attained; not an accusation.

    Every supporting obligation a sub-check leans on must itself have passed
    (b): a witness resting on `sorry` witnesses nothing.  That is what
    `axiom_ok` is for.

    `recorded` carries run-record evidence, used only where the Lean source
    cannot supply it:
      trace_transitions   : int  — >0 discharges §1.2.1-unsolvable (c)
      solvable_witness    : bool — discharges §1.2.1-unsolvable (d) / prune (c)
      recorded_non_vacuous: Optional[bool] — the pipeline's own bit, provenance
                            only, never sufficient alone
    """
    residuals: List[str] = []

    # ---------------------------------------------------------- invariant
    if thm.kind == INVARIANT_KIND:
        pred = thm.basis.get("invariant_pred")
        const = _constancy(pred, defs, prober, residuals)
        if const is not None:
            return {"ok": False,
                    "why": "the invariant `%s` is constant `%s` — D-A3-007 "
                           "class, fails §1.2.1 (two-witness)" % (pred, const),
                    "residuals": residuals}
        residuals.append("full §1.2.1 two-witness check deferred (§9.2 residual): "
                         "non-constancy of `%s` established %s"
                         % (pred, "definitionally (probe)"
                            if prober and prober(pred) and prober(pred).get("probed")
                            else "statically only"))
        return {"ok": True,
                "why": "the invariant `%s` is not constant" % pred,
                "residuals": residuals}

    # --------------------------------------------------------- unsolvable
    if thm.kind == UNSOLVABLE_KIND:
        goal = thm.basis.get("goal_pred")
        subs: Dict[str, Any] = {}
        gconst = _constancy(goal, defs, prober, residuals)
        if gconst in ("false", "False"):
            return {"ok": False,
                    "why": "`%s` is constant false — empty goal set, fails "
                           "§1.2.1-unsolvable (d)" % goal,
                    "residuals": residuals, "sub_checks": subs}

        inv_preds = {t.basis.get("invariant_pred")
                     for t in dev.by_kind(INVARIANT_KIND) if axiom_ok(t.name)}
        inv_preds.discard(None)
        init_claims = [t for t in dev.by_kind(POINT_KIND)
                       if axiom_ok(t.name)
                       and t.basis.get("pred") in inv_preds
                       and any(a.polarity == "pos" for a in t.concl_atoms)]
        subs["a_inv_at_init"] = bool(init_claims)
        if init_claims:
            t0 = init_claims[0]
            subs["a_provenance"] = (
                "`%s` states `%s` at the closed state `%s`, and `%s` is the "
                "subject of a closure theorem in the same development"
                % (t0.name, t0.basis.get("pred"), t0.basis.get("at"),
                   t0.basis.get("pred")))
            for t in init_claims:
                c = _constancy(t.basis.get("pred"), defs, prober, residuals)
                if c is not None:
                    return {"ok": False,
                            "why": "the invariant `%s` the unsolvability rests "
                                   "on is constant `%s`" % (t.basis.get("pred"), c),
                            "residuals": residuals, "sub_checks": subs}

        excluders = [t.name for t in dev.theorems.values()
                     if t.name != thm.name and axiom_ok(t.name)
                     and (any(a.pred == goal and a.polarity == "neg"
                              for a in t.concl_atoms)
                          or (any(a.pred == goal and a.polarity == "pos"
                                  for a in t.hyp_atoms)
                              and any(a.polarity == "neg" for a in t.concl_atoms)))]
        subs["b_goals_excluded"] = bool(excluders)
        if excluders:
            subs["b_provenance"] = "goal states excluded by `%s`" % excluders[0]

        transitions = recorded.get("trace_transitions") or 0
        subs["c_init_has_action"] = bool(transitions > 0)
        if transitions > 0:
            subs["c_provenance"] = "recorded trace: %d transitions" % transitions

        goal_witnesses = [t.name for t in dev.by_kind(WITNESS_KIND)
                          if axiom_ok(t.name)
                          and any(a.pred == goal and a.polarity == "pos"
                                  for a in t.concl_atoms)]
        subs["d_goal_nonempty"] = bool(recorded.get("solvable_witness")
                                       or goal_witnesses)
        if recorded.get("solvable_witness"):
            subs["d_provenance"] = recorded.get("solvable_witness_provenance",
                                                "recorded solvable witness")
        elif goal_witnesses:
            subs["d_provenance"] = ("`%s` exhibits a state satisfying `%s`"
                                    % (goal_witnesses[0], goal))
        if not subs["c_init_has_action"]:
            residuals.append(
                "§1.2.1-unsolvable (c) has no source-level check: "
                "「初始态存在至少一个合法动作」is discharged only from a run "
                "record's `trace_transitions`, which a bare Lean book never "
                "carries.  Stated as a coverage gap, not passed open.")
        ok = all(subs.get(k) for k in ("a_inv_at_init", "b_goals_excluded",
                                       "c_init_has_action", "d_goal_nonempty"))
        why = ("§1.2.1-unsolvable (a)-(d) discharged" if ok else
               "missing sub-check: %s" % [k for k in
                                          ("a_inv_at_init", "b_goals_excluded",
                                           "c_init_has_action", "d_goal_nonempty")
                                          if not subs.get(k)])
        return {"ok": ok, "why": why, "residuals": residuals, "sub_checks": subs}

    # -------------------------------------------------------------- prune
    if thm.kind == PRUNE_KIND:
        goal = thm.basis.get("goal_pred")
        pattern = list(thm.basis.get("pattern_preds") or [])
        subs = {"pattern_preds": pattern, "goal_pred": goal}
        for p in pattern:
            c = _constancy(p, defs, prober, residuals)
            if c is not None:
                return {"ok": False,
                        "why": "the pattern predicate `%s` is constant `%s` — "
                               "the pattern has no content, so the theorem says "
                               "nothing (§1.2.1-prune (a))" % (p, c),
                        "residuals": residuals, "sub_checks": subs}
        gconst = _constancy(goal, defs, prober, residuals)
        if gconst in ("false", "False"):
            return {"ok": False,
                    "why": "`%s` is constant false — an empty goal set makes "
                           "every pattern dead for free" % goal,
                    "residuals": residuals, "sub_checks": subs}

        # (a) at least one well-formed state satisfies the pattern.  The whole
        # pattern conjunction must hold, at ONE closed state, in ONE theorem.
        witness = None
        for t in dev.theorems.values():
            if t.name == thm.name or not axiom_ok(t.name):
                continue
            by_arg: Dict[str, Set[str]] = {}
            for a in t.concl_atoms:
                if a.polarity == "pos" and not t.mentions_bound(a.arg):
                    by_arg.setdefault(a.arg.strip(), set()).add(a.pred)
            for arg, preds in sorted(by_arg.items()):
                if set(pattern) <= preds:
                    witness = (t.name, arg)
                    break
            if witness:
                break
        subs["a_pattern_satisfiable"] = witness is not None
        if witness:
            subs["a_provenance"] = ("`%s` exhibits the state `%s` satisfying %s"
                                    % (witness[0], witness[1], pattern))

        # (b) the pattern contains no goal state — proved of the PATTERN, not
        # of the reachable set (a co-theorem with a relation hypothesis would
        # be the deadlock theorem restating itself).
        excluder = None
        for t in dev.theorems.values():
            if t.name == thm.name or not axiom_ok(t.name) or t.relation_hyps:
                continue
            if not any(a.pred == goal and a.polarity == "neg"
                       and t.mentions_bound(a.arg) for a in t.concl_atoms):
                continue
            hp = {a.pred for a in t.hyp_atoms if a.polarity == "pos"}
            if hp and hp <= set(pattern):
                excluder = t.name
                break
        subs["b_pattern_excludes_goal"] = excluder is not None
        if excluder:
            subs["b_provenance"] = "`%s` excludes goal states from the pattern" % excluder

        # (c) the level is itself solvable — otherwise "already lost" is
        # masquerading as a dead zone (CONTRACTS/deadlock_certificate_v0.1:
        # 「在一局本来就输定的关卡上证一条死区定理，句句为真，什么也没证明」).
        solvable = None
        for t in dev.by_kind(WITNESS_KIND):
            if not axiom_ok(t.name):
                continue
            if any(a.pred == goal and a.polarity == "pos" for a in t.concl_atoms) \
                    and _mentions_constant(t, dev):
                solvable = t.name
                break
        subs["c_level_solvable"] = bool(solvable or recorded.get("solvable_witness"))
        if solvable:
            subs["c_provenance"] = ("`%s` exhibits a run from a declared initial "
                                    "state to a state satisfying `%s`" % (solvable, goal))
        elif recorded.get("solvable_witness"):
            subs["c_provenance"] = recorded.get("solvable_witness_provenance",
                                                "recorded solvable witness")

        keys = ("a_pattern_satisfiable", "b_pattern_excludes_goal", "c_level_solvable")
        ok = all(subs.get(k) for k in keys)
        why = ("§1.2.1-prune (a)-(c) discharged" if ok else
               "missing sub-check: %s" % [k for k in keys if not subs.get(k)])
        return {"ok": ok, "why": why, "residuals": residuals, "sub_checks": subs}

    # ------------------------------------------------------- unclassified
    return {"ok": None,
            "why": "§1.2.1 defines no non-vacuity requirement for a `%s` "
                   "assertion — UNCLASSIFIED, not vacuous: E1 did not check "
                   "this theorem, it is not accusing it (%s)"
                   % (thm.kind, thm.basis.get("rule", "")),
            "residuals": residuals,
            "shape": {"conclusion": thm.conclusion,
                      "hypotheses": thm.hypotheses}}


# ------------------------------------------------------------ verdict assembly

def _verdict(label: str, criteria: Dict[str, Any], evidence: Dict[str, Any],
             flags: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    return {
        "verdict": "attained" if label == "discharged" else "not_attained",
        "label": label,
        "criteria": criteria,
        "evidence": evidence,
        "flags": flags or {},
    }


def judge_development(compiles: bool, axiom_report: Dict[str, List[str]],
                      lean_src: Optional[str],
                      probe_result: Optional[Dict[str, Any]],
                      recorded: Dict[str, Any],
                      evidence: Dict[str, Any]) -> Dict[str, Any]:
    """Judge one Lean development that reached the compile stage."""
    if not compiles:
        return _verdict("failing_obligation",
                        {"a_compiles": False, "b_axioms": None, "c_nonvacuous": None},
                        evidence)
    if not axiom_report:
        return _verdict("axioms_unreported",
                        {"a_compiles": True, "b_axioms": None, "c_nonvacuous": None,
                         "note": "compiled, but no `#print axioms` evidence; "
                                 "strict (b) unmet — re-run with --probe"},
                        evidence)
    defs = scan_defs(lean_src) if lean_src else {}
    dev = _shape.parse_development(lean_src)
    prober = probe_result if isinstance(probe_result, Prober) else Prober(probe_result)
    b_by_name = {name: judge_axioms(axioms) for name, axioms in axiom_report.items()}

    def axiom_ok(name: str) -> bool:
        """A supporting obligation counts only if it passed (b) itself."""
        rec = b_by_name.get(name)
        return bool(rec and rec["ok"])

    per_theorem: Dict[str, Any] = {}
    flags: Dict[str, Any] = {"classical_choice_needed": False}
    c_residuals: List[str] = []
    passed: List[str] = []
    refuted: List[str] = []
    unclassified: List[str] = []
    kind_coverage: Dict[str, int] = {}

    for name, axioms in sorted(axiom_report.items()):
        b = b_by_name[name]
        if b["classical_choice_needed"]:
            flags["classical_choice_needed"] = True
        thm = dev.theorems.get(name)
        if thm is None:
            thm = _shape.Theorem(
                name=name, statement="",
                kind=_shape.UNCLASSIFIED_KIND,
                basis={"rule": "no Lean statement available for `%s` — the "
                               "shape could not be read, so no §1.2.1 check "
                               "applies" % name})
        kind_coverage[thm.kind] = kind_coverage.get(thm.kind, 0) + 1
        c = (judge_nonvacuity(thm, dev, defs, prober, recorded, axiom_ok)
             if b["ok"] else {"ok": None, "why": "not reached — (b) failed"})
        if c.get("residuals"):
            c_residuals.extend("%s: %s" % (name, r) for r in c["residuals"])
        per_theorem[name] = {"kind": thm.kind, "kind_basis": thm.basis,
                             "name_hint": _shape.name_hint(name),
                             "b": b, "c": c}
        if not b["ok"]:
            continue
        if c.get("ok") is True:
            passed.append(name)
        elif c.get("ok") is False:
            refuted.append(name)
        else:
            unclassified.append(name)

    if not lean_src:
        c_residuals.append("no Lean source available — every theorem reads "
                           "`unclassified` because the statement could not be "
                           "read; a name is not evidence of what was proved")

    # Label precedence.  `vacuous` is the strongest CLAIM this adjudicator can
    # make, so it is reached only when a §1.2.1 check actually ran and refused;
    # `unclassified` is what is left when nothing ran.  A development holding
    # both a refuted and an unclassified theorem reads `vacuous` — the word is
    # then true of the theorems named in `criteria.refuted`, and the residual
    # below names the ones it is NOT true of, so the accusation stays bounded.
    if passed:
        label = "discharged"
    elif refuted:
        label = "vacuous"
        if unclassified:
            c_residuals.append(
                "label `vacuous` is a finding about %s, the theorem(s) whose "
                "§1.2.1 check ran and failed.  It is NOT a finding about %s, "
                "which E1 could not classify." % (refuted, unclassified))
    elif unclassified:
        label = "unclassified"
    else:
        label = "axiom_violation"
    if unclassified:
        flags["unclassified_theorems"] = unclassified
    return _verdict(label,
                    {"a_compiles": True,
                     "b_axioms": {n: t["b"]["ok"] for n, t in per_theorem.items()},
                     "c_nonvacuous": {n: t["c"].get("ok")
                                      for n, t in per_theorem.items()},
                     "per_theorem": per_theorem,
                     "kind_coverage": kind_coverage,
                     "attaining": passed,
                     "refuted": refuted,
                     "unclassified": unclassified,
                     "c_residuals": c_residuals},
                    evidence, flags)


# ----------------------------------------------------------------- adapters

def _load_json(path: Path) -> Optional[Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 — a live leg may be mid-write; unreadable is a verdict
        return None


def eval_arm_record(record: Dict[str, Any], run_dir: Path,
                    probe: bool, lean_bin: Optional[str]) -> Dict[str, Any]:
    """One certify.json record from a theoria-arm run."""
    exp = record.get("expensive") or {}
    evidence = {"source": "certify record", "kind": "arm_certify",
                "cheap_green": record.get("cheap_green"),
                "proof_layer_available": record.get("proof_layer_available"),
                "detail": exp.get("detail")}
    if not exp.get("available"):
        detail = (exp.get("detail") or "").strip().lower()
        if detail.startswith(REFUSAL_PREFIX):
            return _verdict("declared_refusal",
                            {"a_compiles": None, "b_axioms": None,
                             "c_nonvacuous": None,
                             "note": "no theorem was produced; strict reading "
                                     "of §1.2 (see module docstring, item 1)"},
                            evidence,
                            {"gap_candidate_g": True})
        return _verdict("no_proof_layer",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None},
                        evidence)
    # Proof layer available.
    lean_file = exp.get("lean_file")
    if "returncode" not in exp:
        # a Lean file exists but lean was never run
        if probe and lean_bin and lean_file and Path(lean_file).exists():
            return eval_lean_source(Path(lean_file), probe=True,
                                    lean_bin=lean_bin, recorded={})
        return _verdict("undischarged",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None,
                         "note": exp.get("detail")},
                        evidence)
    compiles = exp.get("returncode") == 0 and bool(exp.get("ok"))
    axiom_report = parse_axiom_lines(exp.get("stdout") or "")
    lean_src = None
    if lean_file and Path(lean_file).exists():
        try:
            lean_src = Path(lean_file).read_text(encoding="utf-8")
        except OSError:
            lean_src = None
    probe_result = None
    if probe and lean_bin and compiles and lean_file and Path(lean_file).exists():
        if not axiom_report:
            live = eval_lean_source(Path(lean_file), probe=True,
                                    lean_bin=lean_bin, recorded={})
            live["evidence"]["source"] = "certify record + live re-run of %s" % lean_file
            return live
        _lf = Path(lean_file)
        probe_result = Prober(run=lambda p: probe_constancy(lean_bin, _lf, pred=p))
    return judge_development(compiles, axiom_report, lean_src, probe_result,
                             {}, evidence)


def eval_lean_source(lean_path: Path, probe: bool, lean_bin: Optional[str],
                     recorded: Dict[str, Any]) -> Dict[str, Any]:
    """Live evaluation of a Lean development (the §9.2 checker path)."""
    evidence = {"source": str(lean_path), "kind": "lean_source_live"}
    if not lean_bin:
        return _verdict("undischarged",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None,
                         "note": "no Lean binary found; the obligations are "
                                 "stated and undischarged"},
                        evidence)
    src = lean_path.read_text(encoding="utf-8")
    theorems = re.findall(r"^theorem\s+(\w+)", src, re.M)
    recorded = dict(recorded)
    recorded.setdefault("theorems_present", theorems)
    with tempfile.TemporaryDirectory(prefix="u3lean_") as td:
        aug = Path(td) / lean_path.name
        extra = "\n".join("#print axioms %s" % t for t in theorems)
        aug.write_text(src + "\n\n-- u3 axiom audit\n" + extra + "\n",
                       encoding="utf-8")
        res = run_lean(lean_bin, aug)
    compiles = res["returncode"] == 0
    axiom_report = {t: a for t, a in
                    parse_axiom_lines(res["stdout"]).items() if t in theorems}
    probe_result = None
    if probe and compiles:
        probe_result = Prober(
            run=lambda p: probe_constancy(lean_bin, lean_path, pred=p))
    out = judge_development(compiles, axiom_report, src, probe_result,
                            recorded, evidence)
    if not compiles:
        out["evidence"]["stderr_tail"] = (res["stderr"] or res["stdout"])[-800:]
    return out


def eval_a0_report(report: Dict[str, Any], territory: Path,
                   probe: bool, lean_bin: Optional[str]) -> Dict[str, Any]:
    """a0-spike style: artifacts/a0_report.json `lean` block."""
    lean_block = report.get("lean") or {}
    evidence = {"source": str(territory / "artifacts" / "a0_report.json"),
                "kind": "a0_report"}
    if not lean_block.get("available"):
        return _verdict("no_proof_layer",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None},
                        evidence)
    lean_path = territory / "artifacts" / "A0.lean"
    recorded = {
        "theorems_present": lean_block.get("theorems") or [],
        "trace_transitions": (report.get("explore") or {}).get("transitions", 0),
        "recorded_non_vacuous": lean_block.get("non_vacuous"),
    }
    grading = report.get("grading") or {}
    solvable = [lvl for lvl, g in grading.items() if g.get("actually_solvable")]
    if solvable:
        recorded["solvable_witness"] = True
        recorded["solvable_witness_provenance"] = (
            "a0_report grading: level(s) %s actually solvable with recorded plan"
            % ",".join(sorted(solvable)))
    if probe and lean_bin and lean_path.exists():
        return eval_lean_source(lean_path, probe=True, lean_bin=lean_bin,
                                recorded=recorded)
    compiles = bool(lean_block.get("compiles"))
    if lean_block.get("uses_sorry") or lean_block.get("sorry_in_source"):
        compiles = False  # a sorried development is not a discharged one
    axiom_report = parse_axiom_lines(lean_block.get("axioms") or [])
    lean_src = lean_path.read_text(encoding="utf-8") if lean_path.exists() else None
    return judge_development(compiles, axiom_report, lean_src, None,
                             recorded, evidence)


def eval_lean_cert(cert: Dict[str, Any], territory: Path,
                   probe: bool, lean_bin: Optional[str]) -> Dict[str, Any]:
    """cold-start-a0 style: certify_lean_generated_theory_lean.json."""
    evidence = {"source": str(territory / "artifacts" /
                              "certify_lean_generated_theory_lean.json"),
                "kind": "lean_cert_json"}
    if not cert.get("available"):
        return _verdict("no_proof_layer",
                        {"a_compiles": None, "b_axioms": None, "c_nonvacuous": None},
                        evidence)
    lean_rel = (cert.get("file") or "").replace("\\", "/")
    lean_path = (territory / lean_rel) if lean_rel else None
    recorded: Dict[str, Any] = {}
    if probe and lean_bin and lean_path and lean_path.exists():
        return eval_lean_source(lean_path, probe=True, lean_bin=lean_bin,
                                recorded=recorded)
    compiles = bool(cert.get("green")) and cert.get("returncode") == 0 \
        and not cert.get("sorries")
    axiom_report = {r.get("name"): r.get("axioms", [])
                    for r in (cert.get("axiom_reports") or []) if r.get("name")}
    if not axiom_report:
        axiom_report = parse_axiom_lines(cert.get("output") or [])
    lean_src = (lean_path.read_text(encoding="utf-8")
                if lean_path and lean_path.exists() else None)
    recorded["theorems_present"] = list(axiom_report)
    return judge_development(compiles, axiom_report, lean_src, None,
                             recorded, evidence)


# ------------------------------------------------------------- run-dir driver

_THEOREM_LINE = re.compile(r"^\s*(?:theorem|lemma)\s+\w", re.M)


def states_a_theorem(lean_file: Path) -> bool:
    """Does this `.lean` file declare a theorem?  A build script does not."""
    try:
        return bool(_THEOREM_LINE.search(
            _shape.strip_comments(lean_file.read_text(encoding="utf-8"))))
    except OSError:
        return False


def find_books(path: Path) -> List[Path]:
    """Lean developments directly inside `path`, `theory.lean` first."""
    if not path.is_dir():
        return []
    books = [p for p in sorted(path.glob("*.lean"))
             if p.is_file() and states_a_theorem(p)]
    books.sort(key=lambda p: (p.name != "theory.lean", p.name))
    return books


def evaluate(path: Path, probe: bool = False,
             lean_bin: Optional[str] = None) -> Dict[str, Any]:
    """Evaluate one directory.  Returns the verdict dict (plus `run`, `game`)."""
    path = Path(path)
    if probe and lean_bin is None:
        lean_bin = find_lean()
    game = None
    run_meta = _load_json(path / "run.json") if (path / "run.json").exists() else None
    if isinstance(run_meta, dict):
        game = run_meta.get("game_id")

    best: Optional[Dict[str, Any]] = None

    def consider(v: Dict[str, Any]) -> None:
        nonlocal best
        if best is None or _STAGE_RANK[v["label"]] > _STAGE_RANK[best["label"]]:
            best = v

    # 1. a0-spike style
    a0_report_path = path / "artifacts" / "a0_report.json"
    if a0_report_path.exists():
        report = _load_json(a0_report_path)
        if report is None:
            consider(_verdict("unreadable", {}, {"source": str(a0_report_path)}))
        else:
            consider(eval_a0_report(report, path, probe, lean_bin))

    # 2. cold-start-a0 style
    cert_path = path / "artifacts" / "certify_lean_generated_theory_lean.json"
    if cert_path.exists():
        cert = _load_json(cert_path)
        if cert is None:
            consider(_verdict("unreadable", {}, {"source": str(cert_path)}))
        else:
            consider(eval_lean_cert(cert, path, probe, lean_bin))

    # 3. theoria-arm run dir
    certify_path = path / "certify.json"
    if certify_path.exists():
        records = _load_json(certify_path)
        if records is None:
            consider(_verdict("unreadable", {}, {"source": str(certify_path)}))
        elif isinstance(records, list) and records:
            for rec in records:
                if isinstance(rec, dict):
                    consider(eval_arm_record(rec, path, probe, lean_bin))
        else:
            consider(_verdict("no_evidence",
                              {"note": "certify.json is empty — the certify "
                                       "stage left no records"},
                              {"source": str(certify_path), "kind": "arm_certify"}))
    transfer_path = path / "transfer.json"
    if transfer_path.exists() and (best is None
                                   or _STAGE_RANK[best["label"]]
                                   <= _STAGE_RANK["no_evidence"]):
        transfer = _load_json(transfer_path)
        cert_block = (transfer or {}).get("certify") if isinstance(transfer, dict) else None
        if isinstance(cert_block, dict):
            if cert_block.get("proof_layer_available"):
                consider(_verdict("undischarged",
                                  {"note": "transfer.certify records the proof layer "
                                           "available but carries no Lean result"},
                                  {"source": str(transfer_path),
                                   "kind": "arm_transfer",
                                   "cheap_green": cert_block.get("cheap_green")}))
            else:
                consider(_verdict("no_proof_layer",
                                  {"a_compiles": None, "b_axioms": None,
                                   "c_nonvacuous": None},
                                  {"source": str(transfer_path),
                                   "kind": "arm_transfer",
                                   "cheap_green": cert_block.get("cheap_green")}))

    # 4. bare theory dir with a Lean development.  Compiling is criterion (a),
    # so Lean is looked up even without --probe; --probe only adds the
    # constancy probes.
    #
    # D1 (exam → freeze, 2026-08-01): this used to hard-code `theory.lean`, so
    # the four handover packages whose book is called `Level.lean` read
    # `no_evidence` — indistinguishable from "there was no proof layer".  A
    # book's file name is not evidence about a book, so every `.lean` file in
    # the directory that STATES A THEOREM is a candidate.  `lakefile.lean` and
    # friends state none and are skipped by that test, not by a name list.
    if best is None:
        for lean_file in find_books(path):
            consider(eval_lean_source(lean_file, probe=probe,
                                      lean_bin=lean_bin or find_lean(),
                                      recorded={}))

    if best is None:
        best = _verdict("no_evidence",
                        {"note": "no recognised proof-layer artefact in %s" % path},
                        {"source": str(path)})
    best["run"] = str(path)
    best["game"] = game
    return best


# -------------------------------------------------------------------- sweep

#: Directories a census must never descend into, each with the reason it is
#: excluded.  An exclusion that is invisible cannot be audited, so
#: `expand_targets` will hand the list back on request rather than silently
#: dropping paths.
DEFAULT_EXCLUSIONS: Dict[str, str] = {
    ".git": "git internals, not artefacts",
    ".worktrees": "byte-copies of other branches; counting them would inflate "
                  "the denominator with duplicates of the same book",
    ".lake": "Lean build output, not a book",
    ".toolchain": "gitignored toolchain build",
    "build": "build output",
    "__pycache__": "compiled Python",
    "node_modules": "vendored dependencies",
    "environment_files": "upstream game source — the pile cut forbids reading "
                         "anything here that is not development pile",
    "_worktree-scratch-archive": "archived byte-copies of other territories' books",
}


def is_target_dir(p: Path) -> bool:
    """Does this directory hold a proof-layer artefact E1 can adjudicate?"""
    if any((p / n).exists() for n in ("certify.json", "transfer.json")):
        return True
    if (p / "artifacts").is_dir() and any(
            (p / "artifacts" / n).exists()
            for n in ("a0_report.json", "certify_lean_generated_theory_lean.json")):
        return True
    return bool(find_books(p))


def expand_targets(paths: List[Path], exclusions: Optional[Dict[str, str]] = None,
                   record_exclusions: Optional[List[Dict[str, str]]] = None,
                   max_depth: int = 12) -> List[Path]:
    """Every adjudicable directory at or under each path.

    D2 (exam → freeze, 2026-08-01): this used to descend exactly one level, so
    the three books under `cold-start-a3/runs/<run>/generated/<variant>/` were
    unreachable and the 2026-07-31 sweep's hand-typed path list stood in for a
    census.  A hand-typed list only finds what someone remembered, which is the
    one thing a census may not depend on.  It now walks, and it declares what
    it refuses to walk into.
    """
    excl = DEFAULT_EXCLUSIONS if exclusions is None else exclusions
    out: List[Path] = []
    seen: Set[Path] = set()

    def walk(d: Path, depth: int, root: Path) -> None:
        if depth > max_depth:
            if record_exclusions is not None:
                record_exclusions.append(
                    {"path": str(d), "reason": "deeper than max_depth=%d" % max_depth})
            return
        if is_target_dir(d):
            key = d.resolve()
            if key not in seen:
                seen.add(key)
                out.append(d)
        try:
            children = sorted(c for c in d.iterdir() if c.is_dir())
        except OSError:
            return
        for c in children:
            if c.is_symlink():
                continue
            if c.name in excl:
                if record_exclusions is not None:
                    record_exclusions.append(
                        {"path": str(c.relative_to(root)) if root in c.parents
                                 else str(c),
                         "reason": excl[c.name]})
                continue
            walk(c, depth + 1, root)

    for p in paths:
        p = Path(p)
        if not p.is_dir():
            continue
        walk(p, 0, p)
    return out


def to_markdown(rows: List[Dict[str, Any]]) -> str:
    lines = [
        "| run | game | verdict | label | (a) | (b) | (c) | evidence | flags |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    def _tri(v: Any) -> str:
        if v is True:
            return "pass"
        if v is False:
            return "FAIL"
        if isinstance(v, dict):
            vals = set(v.values())
            if vals == {True}:
                return "pass"
            if True in vals:
                return "mixed"
            if False in vals:
                return "FAIL"
            return "—"
        return "—"

    for r in rows:
        c = r.get("criteria") or {}
        flags = r.get("flags") or {}
        flag_bits = [k for k, v in flags.items() if v]
        lines.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
            Path(r["run"]).name, r.get("game") or "—",
            "**attained**" if r["verdict"] == "attained" else "not attained",
            r["label"],
            _tri(c.get("a_compiles")), _tri(c.get("b_axioms")),
            _tri(c.get("c_nonvacuous")),
            (r.get("evidence") or {}).get("kind", "—"),
            ",".join(flag_bits) or "—"))
    n_att = sum(1 for r in rows if r["verdict"] == "attained")
    lines.append("")
    lines.append("**%d / %d directories attained U3** (per-directory, not the "
                 "E1 per-game rate; the frozen denominator 19/12 applies only "
                 "to the sealed campaign)." % (n_att, len(rows)))
    return "\n".join(lines)


# ------------------------------------------------------------- path hygiene

def sanitize_paths(obj: Any) -> Any:
    """Strip machine-naming prefixes from every string in a verdict structure.

    tools/check_locations.py: no tracked artefact may record where its builder
    stood.  Sweep outputs land in freeze/runs/ (run scope), so they are written
    clean instead of allowlisted: the repo root (worktree or main tree) becomes
    `<repo>` and the home directory becomes `<home>`.
    """
    here = Path(__file__).resolve()
    roots: List[str] = []
    wt_root = here.parents[1]           # <root>/freeze/u3.py
    roots.append(str(wt_root))
    # a .worktrees checkout: the main tree is two levels above the checkout
    parts = wt_root.parts
    if ".worktrees" in parts:
        main_root = Path(*parts[:parts.index(".worktrees")])
        roots.append(str(main_root))
    roots.append(str(Path.home()))
    subs: List[tuple] = []
    for i, r in enumerate(sorted(set(roots), key=len, reverse=True)):
        tag = "<home>" if Path(r) == Path.home() else "<repo>"
        subs.append((r.replace("\\", "/"), tag))
        subs.append((r.replace("/", "\\"), tag))

    def walk(x: Any) -> Any:
        if isinstance(x, str):
            for frm, to in subs:
                x = x.replace(frm, to)
            return x
        if isinstance(x, list):
            return [walk(v) for v in x]
        if isinstance(x, dict):
            return {k: walk(v) for k, v in x.items()}
        return x

    return walk(obj)


# ---------------------------------------------------------------------- CLI

def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(prog="u3.py", description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)

    ev = sub.add_parser("eval", help="judge one run/territory/theory directory")
    ev.add_argument("path", type=Path)
    ev.add_argument("--probe", action="store_true",
                    help="run Lean live: axiom audit + constancy probes")
    ev.add_argument("--lean", default=None, help="path to the lean binary")
    ev.add_argument("--json", action="store_true", dest="as_json")

    sw = sub.add_parser("sweep", help="judge many directories, emit a table")
    sw.add_argument("paths", nargs="+", type=Path)
    sw.add_argument("--probe", action="store_true")
    sw.add_argument("--lean", default=None)
    sw.add_argument("--md", type=Path, default=None, help="write Markdown table")
    sw.add_argument("--json", type=Path, default=None, dest="json_out",
                    help="write full verdicts as JSON")

    args = ap.parse_args(argv)
    lean_bin = args.lean or (find_lean() if args.probe else None)

    if args.cmd == "eval":
        v = evaluate(args.path, probe=args.probe, lean_bin=lean_bin)
        if args.as_json:
            print(json.dumps(v, indent=1, ensure_ascii=False, sort_keys=True))
        else:
            print("%s  %s  [%s]" % (v["verdict"].upper(), v["run"], v["label"]))
        return 0 if v["verdict"] == "attained" else 3

    rows = [evaluate(t, probe=args.probe, lean_bin=lean_bin)
            for t in expand_targets(args.paths)]
    rows = sanitize_paths(rows)
    md = to_markdown(rows)
    if args.md:
        args.md.write_text(md + "\n", encoding="utf-8")
    if args.json_out:
        args.json_out.write_text(
            json.dumps(rows, indent=1, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8")
    print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
