;; Sokoban with the deadlock theorems compiled in (singleton guard).
;; Generated by bench/compile_theorems.py -- do not edit by hand.
;;
;; Identical to fixtures/data/sokoban_domain.pddl except that `push` may not
;; create a state matching a proved dead pattern.  `dead1` and `deadpair` are
;; static -- no action adds or deletes them -- so they cost grounding, not search.
(define (domain sokoban-guarded)
  (:requirements :strips :typing :negative-preconditions)
  (:types cell box dir)
  (:predicates
    (at-player ?c - cell)
    (at ?b - box ?c - cell)
    (clear ?c - cell)
    (adj ?from - cell ?to - cell ?d - dir)
    (dead1 ?b - box ?c - cell)
    (deadpair ?b1 - box ?c1 - cell ?b2 - box ?c2 - cell))

  (:action move
    :parameters (?from - cell ?to - cell ?d - dir)
    :precondition (and (at-player ?from) (clear ?to) (adj ?from ?to ?d))
    :effect (and (at-player ?to) (not (at-player ?from))
                 (clear ?from) (not (clear ?to))))

  (:action push
    :parameters (?p - cell ?from - cell ?to - cell ?b - box ?d - dir)
    :precondition (and (at-player ?p) (at ?b ?from) (clear ?to)
                       (adj ?p ?from ?d) (adj ?from ?to ?d)
                       (not (dead1 ?b ?to)))
    :effect (and (at-player ?from) (not (at-player ?p)) (clear ?p)
                 (at ?b ?to) (not (at ?b ?from))
                 (not (clear ?to)) (not (clear ?from)))))
