"""Fixture D - two sokoban levels, emitted as PDDL.

Theoria 1.9's example of a conditional mini unsolvability theorem is "box in a
dead corner AND not the goal implies dead", and nothing in fixtures A/B/C can
carry it: the cart world has no pushable second object, and peg solitaire has no
geometry.  So the deadlock carver gets a world of its own.

Two levels, one domain:

    open4   a 4x4 open interior, two boxes, two goals.  Four interior corners,
            none of them a goal, so each is a dead corner for both boxes; the
            wall rows additionally admit pair deadlocks (two boxes side by side
            against a wall can never be separated).  This is the level the
            pruning comparison is measured on.

    ring    a 1-wide corridor loop.  A box in a 1-wide corridor can be pushed
            along it but can never turn a corner, because turning needs the
            player to stand beside the box and there is no beside.  That makes
            half the board provably unreachable *for a box*, which is what gives
            the probe layer a genuine "this experiment cannot be performed"
            verdict rather than a manufactured one.

The PDDL is generated, not hand-written, so the two levels cannot drift apart
from the geometry the tests reason about.  Same source, same bytes.
"""

import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple

Cell = Tuple[int, int]

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

DOMAIN_PATH = os.path.join(DATA_DIR, "sokoban_domain.pddl")
OPEN4_PATH = os.path.join(DATA_DIR, "sokoban_open4.pddl")
OPEN4FAR_PATH = os.path.join(DATA_DIR, "sokoban_open4far.pddl")
RING_PATH = os.path.join(DATA_DIR, "sokoban_ring.pddl")
RINGSTUCK_PATH = os.path.join(DATA_DIR, "sokoban_ringstuck.pddl")

WALL = "#"
FLOOR = "."

# (row delta, column delta) per direction name, in the order the PDDL lists them.
DELTA: Dict[str, Cell] = {
    "down": (1, 0),
    "left": (0, -1),
    "right": (0, 1),
    "up": (-1, 0),
}
DIRECTIONS = tuple(sorted(DELTA))


DOMAIN = """;; Sokoban, in the STRIPS subset the fd_adapter parser accepts.
;; Generated by fixtures/sokoban.py -- do not edit by hand.
;;
;; `clear` covers the player as well as the boxes, so "a cell holds at most one
;; thing" is a consequence of the action set rather than an assumption a reader
;; has to supply.  The deadlock carver leans on exactly that: it derives the
;; at-most-one facts itself from reachable pairs, and never sees the board.
;;
;; `adj ?from ?to ?d` is static -- no action adds or deletes it -- which is what
;; lets grounding discard the pushes a wall makes impossible (DECISIONS D-016),
;; and in turn what makes a corner provable: a box in one has no push instance
;; left to delete its position.
(define (domain sokoban)
  (:requirements :strips :typing)
  (:types cell box dir)
  (:predicates
    (at-player ?c - cell)
    (at ?b - box ?c - cell)
    (clear ?c - cell)
    (adj ?from - cell ?to - cell ?d - dir))

  (:action move
    :parameters (?from - cell ?to - cell ?d - dir)
    :precondition (and (at-player ?from) (clear ?to) (adj ?from ?to ?d))
    :effect (and (at-player ?to) (not (at-player ?from))
                 (clear ?from) (not (clear ?to))))

  (:action push
    :parameters (?p - cell ?from - cell ?to - cell ?b - box ?d - dir)
    :precondition (and (at-player ?p) (at ?b ?from) (clear ?to)
                       (adj ?p ?from ?d) (adj ?from ?to ?d))
    :effect (and (at-player ?from) (not (at-player ?p)) (clear ?p)
                 (at ?b ?to) (not (at ?b ?from))
                 (not (clear ?to)) (not (clear ?from)))))
"""


@dataclass(frozen=True)
class Level:
    """A board plus its placements. The PDDL below is a rendering of this."""

    name: str
    grid: Tuple[str, ...]
    player: Cell
    boxes: Tuple[Tuple[str, Cell], ...]        # (box name, cell)
    goals: Tuple[Tuple[str, Cell], ...]        # (box name, goal cell)
    optimum: Optional[int] = None              # hand-derived, argued in the README
    path: str = ""

    # ------------------------------------------------------------- geometry

    def floors(self) -> List[Cell]:
        return sorted(
            (r, c)
            for r, row in enumerate(self.grid)
            for c, char in enumerate(row)
            if char == FLOOR
        )

    def is_floor(self, cell: Cell) -> bool:
        r, c = cell
        if not (0 <= r < len(self.grid) and 0 <= c < len(self.grid[r])):
            return False
        return self.grid[r][c] == FLOOR

    def neighbour(self, cell: Cell, direction: str) -> Optional[Cell]:
        dr, dc = DELTA[direction]
        target = (cell[0] + dr, cell[1] + dc)
        return target if self.is_floor(target) else None

    def corners(self) -> List[Cell]:
        """Cells with walls on two perpendicular sides.

        Geometry, for the probe layer's hypotheses to talk about and for the
        tests to check the carver against.  The carver itself derives its
        deadlocks from the grounded action set and never calls this.
        """
        out = []
        for cell in self.floors():
            vertical = [d for d in ("up", "down") if self.neighbour(cell, d) is None]
            horizontal = [d for d in ("left", "right") if self.neighbour(cell, d) is None]
            if vertical and horizontal:
                out.append(cell)
        return out

    def goal_cells(self) -> List[Cell]:
        return sorted(cell for _, cell in self.goals)

    # ------------------------------------------------------------ pddl names

    def cell_name(self, cell: Cell) -> str:
        return "c%d%d" % cell

    def box_names(self) -> List[str]:
        return [name for name, _ in self.boxes]

    def occupied(self) -> Dict[Cell, str]:
        out = {self.player: "player"}
        for name, cell in self.boxes:
            out[cell] = name
        return out

    def problem_text(self) -> str:
        cells = self.floors()
        names = [self.cell_name(cell) for cell in cells]
        occupied = self.occupied()

        adjacency = []
        for cell in cells:
            for direction in DIRECTIONS:
                target = self.neighbour(cell, direction)
                if target is not None:
                    adjacency.append(
                        "    (adj %s %s %s)"
                        % (self.cell_name(cell), self.cell_name(target), direction)
                    )

        init = ["    (at-player %s)" % self.cell_name(self.player)]
        init += [
            "    (at %s %s)" % (name, self.cell_name(cell))
            for name, cell in sorted(self.boxes)
        ]
        init += [
            "    (clear %s)" % self.cell_name(cell)
            for cell in cells
            if cell not in occupied
        ]

        goal = " ".join(
            "(at %s %s)" % (name, self.cell_name(cell)) for name, cell in sorted(self.goals)
        )

        picture = "\n".join(";;   " + row for row in self.grid)
        return (
            ";; Sokoban level %s. Generated by fixtures/sokoban.py -- do not edit.\n"
            ";;\n%s\n;;\n"
            ";; player %s; boxes %s; goals %s\n"
            "(define (problem sokoban-%s)\n"
            "  (:domain sokoban)\n"
            "  (:objects\n"
            "    %s - cell\n"
            "    %s - box\n"
            "    %s - dir)\n"
            "  (:init\n%s\n%s)\n"
            "  (:goal (and %s)))\n"
            % (
                self.name,
                picture,
                self.cell_name(self.player),
                ", ".join(
                    "%s@%s" % (name, self.cell_name(cell)) for name, cell in sorted(self.boxes)
                ),
                ", ".join(
                    "%s@%s" % (name, self.cell_name(cell)) for name, cell in sorted(self.goals)
                ),
                self.name,
                " ".join(names),
                " ".join(self.box_names()),
                " ".join(DIRECTIONS),
                "\n".join(init),
                "\n".join(adjacency),
                goal,
            )
        )


# ------------------------------------------------------------------ the levels

OPEN4 = Level(
    name="open4",
    grid=(
        "######",
        "#....#",
        "#....#",
        "#....#",
        "#....#",
        "######",
    ),
    player=(4, 4),
    boxes=(("b1", (2, 2)), ("b2", (3, 3))),
    goals=(("b1", (1, 2)), ("b2", (4, 3))),
    # Hand-derived optimum 6, argued in engines/deadlock_carver/README.md.
    optimum=6,
    path=OPEN4_PATH,
)

OPEN4FAR = Level(
    name="open4far",
    grid=OPEN4.grid,
    player=(4, 4),
    boxes=(("b1", (2, 2)), ("b2", (3, 3))),
    # Each box has to cross the board, and each box is in the other's way while
    # it does.  The point is depth: on `open4` the search finds its 6-action plan
    # before it has wandered into a single dead region, so the theorems are true
    # and worth nothing.  Pruning only pays where the search would otherwise go.
    goals=(("b1", (4, 2)), ("b2", (1, 3))),
    optimum=None,
    path=OPEN4FAR_PATH,
)

RING = Level(
    name="ring",
    grid=(
        "######",
        "#....#",
        "#.##.#",
        "#.##.#",
        "#....#",
        "######",
    ),
    player=(1, 1),
    boxes=(("b1", (1, 2)),),
    goals=(("b1", (1, 3)),),
    optimum=1,
    path=RING_PATH,
)

RING_STUCK = Level(
    name="ringstuck",
    grid=RING.grid,
    player=RING.player,
    boxes=RING.boxes,
    # The same ring, asking for the box in the side corridor.  Unsolvable, and
    # unsolvable for a reason the geometry makes plain: turning a box out of row
    # 1 needs the player beside it, and a 1-wide corridor has no beside.  This is
    # the instance where deadlock pruning matters most -- proving "no plan" means
    # exhausting the space, and half of that space is dead.
    goals=(("b1", (3, 1)),),
    optimum=None,
    path=RINGSTUCK_PATH,
)

LEVELS = (OPEN4, OPEN4FAR, RING, RING_STUCK)


def by_name(name: str) -> Level:
    for level in LEVELS:
        if level.name == name:
            return level
    raise KeyError(name)


# ---------------------------------------------------------------- generation

def write(data_dir: str = DATA_DIR) -> Dict[str, str]:
    """Write the domain and both problems; returns {name: path}."""
    os.makedirs(data_dir, exist_ok=True)
    written = {"domain": DOMAIN_PATH}
    _write_text(DOMAIN_PATH, DOMAIN)
    for level in LEVELS:
        _write_text(level.path, level.problem_text())
        written[level.name] = level.path
    return written


def _write_text(path: str, text: str) -> None:
    # newline="" so Windows cannot turn the fixture into CRLF behind our back.
    with open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(text)


if __name__ == "__main__":  # pragma: no cover
    paths = write()
    for level in LEVELS:
        print(
            "sokoban %-6s %2d cells, %d box(es), corners %s -> %s"
            % (
                level.name,
                len(level.floors()),
                len(level.boxes),
                [level.cell_name(c) for c in level.corners()],
                paths[level.name],
            )
        )
