;; Sokoban level ring. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #....#
;;   #.##.#
;;   #.##.#
;;   #....#
;;   ######
;;
;; player c11; boxes b1@c12; goals b1@c13
(define (problem sokoban-ring)
  (:domain sokoban)
  (:objects
    c11 c12 c13 c14 c21 c24 c31 c34 c41 c42 c43 c44 - cell
    b1 - box
    down left right up - dir)
  (:init
    (at-player c11)
    (at b1 c12)
    (clear c13)
    (clear c14)
    (clear c21)
    (clear c24)
    (clear c31)
    (clear c34)
    (clear c41)
    (clear c42)
    (clear c43)
    (clear c44)
    (adj c11 c21 down)
    (adj c11 c12 right)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c13 c12 left)
    (adj c13 c14 right)
    (adj c14 c24 down)
    (adj c14 c13 left)
    (adj c21 c31 down)
    (adj c21 c11 up)
    (adj c24 c34 down)
    (adj c24 c14 up)
    (adj c31 c41 down)
    (adj c31 c21 up)
    (adj c34 c44 down)
    (adj c34 c24 up)
    (adj c41 c42 right)
    (adj c41 c31 up)
    (adj c42 c41 left)
    (adj c42 c43 right)
    (adj c43 c42 left)
    (adj c43 c44 right)
    (adj c44 c43 left)
    (adj c44 c34 up))
  (:goal (and (at b1 c13))))
