"""A differential check across the rungs, on random gripper instances.

Two things are compared here and only one of them is a planner.  The gripper
optimum has a closed form -- `optimum()`, derived below from the domain rather
than measured from a search -- so the bundled BFS can be checked against
arithmetic on a machine with no planner installed at all, and against Fast
Downward's own answer on a machine that has one.  That is what makes this a
differential rather than a regression: the oracle does not share a line of code
with the thing it is checking.

Random instances rather than one fixture because the failure this is looking for
is an off-by-one in the number of *trips*, and a single two-ball instance cannot
see it -- two balls fill both grippers exactly, so the ferrying never happens.

Every instance keeps at least one ball out of place.  A goal that already holds
in the initial state is a different question, answered by Fast Downward's
translator before the search ever runs, and it would test the driver rather than
the ladder.
"""

import os
import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from engines import fd_adapter
from engines.fd_adapter import backends

GRIPPERS = ("left", "right")

# (tier, heuristic) pairs the FD rungs are asked for, and the key each answer is
# filed under.  Two optimal configurations, because two independent optimal
# planners agreeing on a length is worth more than one agreeing with itself.
FD_RUNGS = (
    ("fd-optimal", "lmcut", "fd-optimal/lmcut"),
    ("fd-optimal", "ipdb", "fd-optimal/ipdb"),
    ("fd-satisficing", None, "fd-satisficing"),
)


def optimum(movers: int, grippers: int = len(GRIPPERS)) -> int:
    """The gripper optimum, in closed form.

    Every ball out of place needs exactly one pick and one drop and no schedule
    can share either, which is `2 * movers` actions.  The robot carries at most
    `grippers` balls at a time, so it makes `ceil(movers / grippers)` trips to
    the far room and one fewer back, which is `2 * ceil(movers / grippers) - 1`
    moves.  The obvious schedule -- fill both grippers, move, empty them, move
    back -- attains both counts simultaneously, so the sum is the optimum and
    not merely a lower bound.

    Sanity: `optimum(2) == 5`, the hand-verified optimum of the bundled fixture.
    """
    if movers == 0:
        return 0
    trips = -(-movers // grippers)
    return 2 * movers + 2 * trips - 1


@dataclass
class Instance:
    """A random gripper problem, and what the arithmetic says its optimum is."""

    name: str
    movers: int                        # balls in rooma that must reach roomb
    settled: int                       # balls already in roomb, pure grounding weight

    @property
    def optimum(self) -> int:
        return optimum(self.movers)

    def problem_text(self) -> str:
        balls = ["b%d" % i for i in range(1, self.movers + 1)]
        extra = ["s%d" % i for i in range(1, self.settled + 1)]
        init = ["(at-robby rooma)"]
        init += ["(free %s)" % g for g in GRIPPERS]
        init += ["(at %s rooma)" % b for b in balls]
        init += ["(at %s roomb)" % b for b in extra]
        goal = ["(at %s roomb)" % b for b in balls + extra]
        return (
            ";; generated by engines.fd_adapter.fuzz -- closed-form optimum %d\n"
            "(define (problem %s)\n"
            "  (:domain gripper)\n"
            "  (:objects\n"
            "    rooma roomb - room\n"
            "    %s - ball\n"
            "    %s - gripper)\n"
            "  (:init %s)\n"
            "  (:goal (and %s)))\n"
            % (
                self.optimum, self.name,
                " ".join(balls + extra), " ".join(GRIPPERS),
                " ".join(init), " ".join(goal),
            )
        )


def random_instances(rounds: int = 6, seed: int = 20260728) -> List[Instance]:
    """A fixed sequence of instances for a fixed seed -- determinism, as ever."""
    rng = random.Random(seed)
    return [
        Instance(
            name="fuzz-%02d" % index,
            movers=rng.randint(1, 3),
            settled=rng.randint(0, 2),
        )
        for index in range(rounds)
    ]


def write(instance: Instance, directory: str) -> Tuple[str, str]:
    """Put the instance on disk; Fast Downward reads files, not objects."""
    problem_path = os.path.join(directory, "%s.pddl" % instance.name)
    with open(problem_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(instance.problem_text())
    return fd_adapter.DOMAIN_PATH, problem_path


@dataclass
class Comparison:
    """What each rung answered on one instance, against the closed form."""

    name: str
    closed_form: int
    lengths: Dict[str, int] = field(default_factory=dict)

    def disagreements(self) -> List[str]:
        """Which rungs answered something they were not entitled to answer.

        An optimal rung must return exactly the closed-form optimum -- shorter
        would mean the arithmetic is wrong, longer would mean the rung is not
        optimal after all.  The satisficing rung only has to come in at or above
        it: every plan reaching this point has already been replayed by the
        independent validator, so a longer one is just LAMA being LAMA.
        """
        bad = []
        for key, length in sorted(self.lengths.items()):
            if key.startswith(backends.FD_SATISFICING):
                if length < self.closed_form:
                    bad.append("%s: %d < optimum %d" % (key, length, self.closed_form))
            elif length != self.closed_form:
                bad.append("%s: %d != optimum %d" % (key, length, self.closed_form))
        return bad


def compare(instance: Instance, directory: str,
            executable: Optional[str] = None) -> Comparison:
    """Solve one instance on every rung this machine can reach."""
    domain_path, problem_path = write(instance, directory)
    comparison = Comparison(name=instance.name, closed_form=instance.optimum)

    plan = fd_adapter.solve(domain_path, problem_path, prefer=backends.STUB)
    comparison.lengths[backends.STUB] = plan.length

    if executable is not None:
        for tier, heuristic, key in FD_RUNGS:
            plan = fd_adapter.solve(
                domain_path, problem_path, prefer=tier, heuristic=heuristic,
            )
            comparison.lengths[key] = plan.length
    return comparison


def differential(directory: str, rounds: int = 6, seed: int = 20260728,
                 executable: Optional[str] = None) -> List[Comparison]:
    """The whole check: `rounds` instances, every reachable rung, one by one.

    `executable` defaults to whatever `find_fast_downward` turns up, so the FD
    rungs join in the moment a planner is installed and are silently absent
    until then -- the suite must be green either way.
    """
    if executable is None:
        executable = backends.find_fast_downward()
    return [
        compare(instance, directory, executable)
        for instance in random_instances(rounds=rounds, seed=seed)
    ]
