#!/usr/bin/env sh
# verify.sh -- P1PUSH4 / closeout/p1-owner-ruling
# generated by .claude/skills/verify-gate at 2026-08-01T02:43:25Z; base aa2e2cc
#
# Every check runs even after one fails: a red run must print the whole
# checklist, not stop at the first red. Exit 0 only when every line is PASS.
#
#   sh verify.sh            (from anywhere -- it finds its own worktree root)
#   PYTHON=python3 sh verify.sh
set -u

ROOT=$(cd "$(dirname "$0")" && git rev-parse --show-toplevel) || exit 2
cd "$ROOT" || exit 2
PY=${PYTHON:-python}
export PY                       # `check` runs its command in `sh -c`, a new process
export PYTHONIOENCODING=utf-8   # this repo's prose is Chinese; consoles here are not UTF-8
PASS=0
FAIL=0
LOGDIR=$(mktemp -d 2>/dev/null || printf '%s' "${TMPDIR:-/tmp}/verify.$$")
mkdir -p "$LOGDIR" || exit 2

check() {
  _name=$1
  shift
  if sh -c "$*" >"$LOGDIR/out" 2>&1; then
    printf '[PASS] %s\n' "$_name"
    PASS=$((PASS + 1))
  else
    printf '[FAIL] %s\n' "$_name"
    tail -n 30 "$LOGDIR/out" | sed -e 's/^/       | /'
    FAIL=$((FAIL + 1))
  fi
}

printf '== verify.sh :: %s :: %s ==\n' 'P1PUSH4' 'closeout/p1-owner-ruling'
check 'tests -- monitor' 'cd monitor && "$PY" -m pytest -q'
check 'MANIFEST hashes reproduce' '"$PY" .claude/skills/runs-archive/scripts/runs_archive.py check --run monitor/runs/2026-08-01T023624Z-P1PUSH4'
check 'boundary -- only monitor changed' '"$PY" .claude/skills/verify-gate/scripts/guards.py boundary --base aa2e2cc15ac47c5781d4bf7c5e23276a57463346 --territory monitor --allow '\''monitor/spec.py'\'' --allow '\''monitor/state.json'\'' --allow '\''monitor/index.html'\'''
check 'sealed pile untouched' '"$PY" .claude/skills/verify-gate/scripts/guards.py sealed --base aa2e2cc15ac47c5781d4bf7c5e23276a57463346 --allow '\''monitor/spec.py'\'' --allow '\''monitor/state.json'\'' --allow '\''monitor/index.html'\'''
check 'credential never entered a tracked file' '"$PY" .claude/skills/verify-gate/scripts/guards.py secret --base aa2e2cc15ac47c5781d4bf7c5e23276a57463346'
check 'delivered: monitor/runs/2026-08-01T023624Z-P1PUSH4/MANIFEST.json' 'test -e '\''monitor/runs/2026-08-01T023624Z-P1PUSH4/MANIFEST.json'\'''

printf -- '-- %s/%s green' "$PASS" "$((PASS + FAIL))"
if [ "$FAIL" -eq 0 ]; then
  printf '\n'
  exit 0
fi
printf '  <<< NOT GREEN (%s red)\n' "$FAIL"
exit 1
