;; Sokoban level pillar. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #....#
;;   #.##.#
;;   #....#
;;   #....#
;;   ######
;;
;; player c42; boxes b1@c13, b2@c32; goals b1@c31, b2@c14
(define (problem sokoban-pillar)
  (:domain sokoban-guarded)
  (:objects
    c11 c12 c13 c14 c21 c24 c31 c32 c33 c34 c41 c42 c43 c44 - cell
    b1 b2 - box
    down left right up - dir)
  (:init
    (at-player c42)
    (at b1 c13)
    (at b2 c32)
    (clear c11)
    (clear c12)
    (clear c14)
    (clear c21)
    (clear c24)
    (clear c31)
    (clear c33)
    (clear c34)
    (clear c41)
    (clear c43)
    (clear c44)
    (adj c11 c21 down)
    (adj c11 c12 right)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c13 c12 left)
    (adj c13 c14 right)
    (adj c14 c24 down)
    (adj c14 c13 left)
    (adj c21 c31 down)
    (adj c21 c11 up)
    (adj c24 c34 down)
    (adj c24 c14 up)
    (adj c31 c41 down)
    (adj c31 c32 right)
    (adj c31 c21 up)
    (adj c32 c42 down)
    (adj c32 c31 left)
    (adj c32 c33 right)
    (adj c33 c43 down)
    (adj c33 c32 left)
    (adj c33 c34 right)
    (adj c34 c44 down)
    (adj c34 c33 left)
    (adj c34 c24 up)
    (adj c41 c42 right)
    (adj c41 c31 up)
    (adj c42 c41 left)
    (adj c42 c43 right)
    (adj c42 c32 up)
    (adj c43 c42 left)
    (adj c43 c44 right)
    (adj c43 c33 up)
    (adj c44 c43 left)
    (adj c44 c34 up)
    ;; deadlock theorems, compiled in by bench/compile_theorems.py
    (dead1 b1 c11)
    (dead1 b1 c14)
    (dead1 b2 c11)
    (dead1 b2 c14)
    (dead1 b2 c41)
    (dead1 b2 c44)
)
  (:goal (and (at b1 c31) (at b2 c14))))
