;; Sokoban level rnd0014. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #....#
;;   #....#
;;   #..#.#
;;   #....#
;;   ######
;;
;; player c21; boxes b1@c22, b2@c41, b3@c23, b4@c31; goals b1@c14, b2@c43, b3@c44, b4@c32
(define (problem sokoban-rnd0014)
  (:domain sokoban)
  (:objects
    c11 c12 c13 c14 c21 c22 c23 c24 c31 c32 c34 c41 c42 c43 c44 - cell
    b1 b2 b3 b4 - box
    down left right up - dir)
  (:init
    (at-player c21)
    (at b1 c22)
    (at b2 c41)
    (at b3 c23)
    (at b4 c31)
    (clear c11)
    (clear c12)
    (clear c13)
    (clear c14)
    (clear c24)
    (clear c32)
    (clear c34)
    (clear c42)
    (clear c43)
    (clear c44)
    (adj c11 c21 down)
    (adj c11 c12 right)
    (adj c12 c22 down)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c13 c23 down)
    (adj c13 c12 left)
    (adj c13 c14 right)
    (adj c14 c24 down)
    (adj c14 c13 left)
    (adj c21 c31 down)
    (adj c21 c22 right)
    (adj c21 c11 up)
    (adj c22 c32 down)
    (adj c22 c21 left)
    (adj c22 c23 right)
    (adj c22 c12 up)
    (adj c23 c22 left)
    (adj c23 c24 right)
    (adj c23 c13 up)
    (adj c24 c34 down)
    (adj c24 c23 left)
    (adj c24 c14 up)
    (adj c31 c41 down)
    (adj c31 c32 right)
    (adj c31 c21 up)
    (adj c32 c42 down)
    (adj c32 c31 left)
    (adj c32 c22 up)
    (adj c34 c44 down)
    (adj c34 c24 up)
    (adj c41 c42 right)
    (adj c41 c31 up)
    (adj c42 c41 left)
    (adj c42 c43 right)
    (adj c42 c32 up)
    (adj c43 c42 left)
    (adj c43 c44 right)
    (adj c44 c43 left)
    (adj c44 c34 up))
  (:goal (and (at b1 c14) (at b2 c43) (at b3 c44) (at b4 c32))))
