;; Sokoban level rnd0031. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #....#
;;   #.#..#
;;   #....#
;;   ###.##
;;   ######
;;
;; player c32; boxes b1@c34, b2@c31, b3@c23; goals b1@c21, b2@c33, b3@c43
(define (problem sokoban-rnd0031)
  (:domain sokoban)
  (:objects
    c11 c12 c13 c14 c21 c23 c24 c31 c32 c33 c34 c43 - cell
    b1 b2 b3 - box
    down left right up - dir)
  (:init
    (at-player c32)
    (at b1 c34)
    (at b2 c31)
    (at b3 c23)
    (clear c11)
    (clear c12)
    (clear c13)
    (clear c14)
    (clear c21)
    (clear c24)
    (clear c33)
    (clear c43)
    (adj c11 c21 down)
    (adj c11 c12 right)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c13 c23 down)
    (adj c13 c12 left)
    (adj c13 c14 right)
    (adj c14 c24 down)
    (adj c14 c13 left)
    (adj c21 c31 down)
    (adj c21 c11 up)
    (adj c23 c33 down)
    (adj c23 c24 right)
    (adj c23 c13 up)
    (adj c24 c34 down)
    (adj c24 c23 left)
    (adj c24 c14 up)
    (adj c31 c32 right)
    (adj c31 c21 up)
    (adj c32 c31 left)
    (adj c32 c33 right)
    (adj c33 c43 down)
    (adj c33 c32 left)
    (adj c33 c34 right)
    (adj c33 c23 up)
    (adj c34 c33 left)
    (adj c34 c24 up)
    (adj c43 c33 up))
  (:goal (and (at b1 c21) (at b2 c33) (at b3 c43))))
