#!/usr/bin/env bash
# crosscheck territory -- verification gate.
#
#   bash crosscheck/verify.sh
#
# Green means: the C14 census re-derives from the tracked corpus exactly as
# committed, the generated PDDL is byte-identical, and nothing in this territory
# wrote outside it or touched the network.  Run from the repo root.
set -uo pipefail

cd "$(dirname "$0")/.." || exit 1
rc=0

echo "== C14 census reproduces =="
python -m crosscheck.tools.c14_verify || rc=1

echo
echo "== positive control: the instrument can say GOOD =="
# An instrument only ever pointed at a corpus where everything scores bad has not
# been shown capable of the other verdict. The second PDDL backend is the control.
python -m crosscheck.tools.c14_positive_control || rc=1

echo
echo "== the slicing table is arithmetic over the committed census =="
# The headline table in FOUR_FORMS_TRUTH.md is generated by this tool, not typed.
# The claim under test is not "0 of 303" but "0 under every way of choosing the
# corpus" -- so the gate checks the maximum, not one row.
python - <<'PY' || rc=1
import json, subprocess, sys
# Run the generator in-process rather than via a temp file: an earlier version
# redirected to /tmp with stderr swallowed, and on a shell where that path does
# not exist the gate reported a traceback instead of a verdict.
proc = subprocess.run([sys.executable, "-m", "crosscheck.tools.c14_slicings",
                       "--json"], capture_output=True, text=True)
if proc.returncode != 0:
    print("RED  slicing generator failed:\n%s" % (proc.stderr or "")); sys.exit(1)
rows = json.loads(proc.stdout)
if not rows:
    print("RED  slicing table is empty"); sys.exit(1)
# Until 2026-07-31 this asserted max good == 0 -- the pre-repair truth. The
# generator was then repaired (see FOUR_FORMS_TRUTH.md "Superseded"); the
# claim under test is now internal consistency: the slicing table must be
# arithmetic over the committed census, not a typed number. The 0-of-303 run
# dir stays frozen as the pre-repair record.
census = json.load(open("crosscheck/runs/20260731T061500Z-C14-after-the-repair/out/census.json", encoding="utf-8"))
summ = census["summary"] if "summary" in census else census
head = rows[0]
bad = []
if head["actions"] != summ["actions_owed"]:
    bad.append("headline actions %d != census owed %d" % (head["actions"], summ["actions_owed"]))
if head["good"] != summ["actions_semantically_non_empty"]:
    bad.append("headline good %d != census non-empty %d" % (head["good"], summ["actions_semantically_non_empty"]))
for r in rows:
    if r["good"] > r["actions"]:
        bad.append("slicing %r reports more good than actions" % r["slicing"])
if bad:
    for b in bad: print("RED  " + b)
    sys.exit(1)
print("green  %d slicings consistent with the committed census "
      "(headline: %d/%d good; pre-repair record 0/303 frozen)"
      % (len(rows), head["good"], head["actions"]))
PY

echo
echo "== territory discipline: crosscheck/ writes only =="
# The other track's tree is off limits by CLAUDE.md; a diff touching it is a red.
# Three exceptions, and only three: the board item's own territory (crosscheck/),
# this worker's own appended paragraph in PARTNER_SYNC.md, and monitor/inbox/ --
# the one path under monitor/ every worker is standing-authorised to write.
# Anything else under monitor/ is still a red.
strays=$(git diff --name-only HEAD -- . \
           ':(exclude)crosscheck' \
           ':(exclude)PARTNER_SYNC.md' \
           ':(exclude)monitor/inbox' 2>/dev/null)
if [ -n "$strays" ]; then
  echo "RED  this branch modifies files outside crosscheck/:"
  echo "$strays" | sed 's/^/     /'
  rc=1
else
  echo "green  no tracked file outside crosscheck/ (and PARTNER_SYNC.md) modified"
fi

echo
echo "== theory-compiler/ untouched (other track) =="
if git diff --name-only HEAD -- theory-compiler 2>/dev/null | grep -q .; then
  echo "RED  theory-compiler/ modified -- it belongs to the other track"
  rc=1
else
  echo "green  theory-compiler/ byte-untouched"
fi

echo
echo "== no credential in tracked crosscheck/ files =="
# The census reads no secrets, but the release manifest publishes every tracked
# file, so this is checked rather than assumed.
if git grep -nI -E 'ARC_API_KEY[[:space:]]*=[[:space:]]*[A-Za-z0-9_-]{12,}' -- crosscheck 2>/dev/null | grep -q .; then
  echo "RED  a credential value appears in crosscheck/"
  rc=1
else
  echo "green  no credential value in crosscheck/"
fi

echo
if [ "$rc" -eq 0 ]; then echo "crosscheck/verify.sh: GREEN"; else echo "crosscheck/verify.sh: RED"; fi
exit $rc
