;; Sokoban level rnd0023. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   ##.#.#
;;   #....#
;;   #.#..#
;;   #....#
;;   ######
;;
;; player c42; boxes b1@c21, b2@c44; goals b1@c23, b2@c31
(define (problem sokoban-rnd0023)
  (:domain sokoban-guarded)
  (:objects
    c12 c14 c21 c22 c23 c24 c31 c33 c34 c41 c42 c43 c44 - cell
    b1 b2 - box
    down left right up - dir)
  (:init
    (at-player c42)
    (at b1 c21)
    (at b2 c44)
    (clear c12)
    (clear c14)
    (clear c22)
    (clear c23)
    (clear c24)
    (clear c31)
    (clear c33)
    (clear c34)
    (clear c41)
    (clear c43)
    (adj c12 c22 down)
    (adj c14 c24 down)
    (adj c21 c31 down)
    (adj c21 c22 right)
    (adj c22 c21 left)
    (adj c22 c23 right)
    (adj c22 c12 up)
    (adj c23 c33 down)
    (adj c23 c22 left)
    (adj c23 c24 right)
    (adj c24 c34 down)
    (adj c24 c23 left)
    (adj c24 c14 up)
    (adj c31 c41 down)
    (adj c31 c21 up)
    (adj c33 c43 down)
    (adj c33 c34 right)
    (adj c33 c23 up)
    (adj c34 c44 down)
    (adj c34 c33 left)
    (adj c34 c24 up)
    (adj c41 c42 right)
    (adj c41 c31 up)
    (adj c42 c41 left)
    (adj c42 c43 right)
    (adj c43 c42 left)
    (adj c43 c44 right)
    (adj c43 c33 up)
    (adj c44 c43 left)
    (adj c44 c34 up)
    ;; deadlock theorems, compiled in by bench/compile_theorems.py
    (dead1 b1 c21)
    (dead1 b2 c44)
)
  (:goal (and (at b1 c23) (at b2 c31))))
