;; Sokoban level ringstuck6. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ########
;;   #......#
;;   #.####.#
;;   #.####.#
;;   #.####.#
;;   #.####.#
;;   #......#
;;   ########
;;
;; player c11; boxes b1@c12; goals b1@c51
(define (problem sokoban-ringstuck6)
  (:domain sokoban-guarded)
  (:objects
    c11 c12 c13 c14 c15 c16 c21 c26 c31 c36 c41 c46 c51 c56 c61 c62 c63 c64 c65 c66 - cell
    b1 - box
    down left right up - dir)
  (:init
    (at-player c11)
    (at b1 c12)
    (clear c13)
    (clear c14)
    (clear c15)
    (clear c16)
    (clear c21)
    (clear c26)
    (clear c31)
    (clear c36)
    (clear c41)
    (clear c46)
    (clear c51)
    (clear c56)
    (clear c61)
    (clear c62)
    (clear c63)
    (clear c64)
    (clear c65)
    (clear c66)
    (adj c11 c21 down)
    (adj c11 c12 right)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c13 c12 left)
    (adj c13 c14 right)
    (adj c14 c13 left)
    (adj c14 c15 right)
    (adj c15 c14 left)
    (adj c15 c16 right)
    (adj c16 c26 down)
    (adj c16 c15 left)
    (adj c21 c31 down)
    (adj c21 c11 up)
    (adj c26 c36 down)
    (adj c26 c16 up)
    (adj c31 c41 down)
    (adj c31 c21 up)
    (adj c36 c46 down)
    (adj c36 c26 up)
    (adj c41 c51 down)
    (adj c41 c31 up)
    (adj c46 c56 down)
    (adj c46 c36 up)
    (adj c51 c61 down)
    (adj c51 c41 up)
    (adj c56 c66 down)
    (adj c56 c46 up)
    (adj c61 c62 right)
    (adj c61 c51 up)
    (adj c62 c61 left)
    (adj c62 c63 right)
    (adj c63 c62 left)
    (adj c63 c64 right)
    (adj c64 c63 left)
    (adj c64 c65 right)
    (adj c65 c64 left)
    (adj c65 c66 right)
    (adj c66 c65 left)
    (adj c66 c56 up)
    ;; deadlock theorems, compiled in by bench/compile_theorems.py
    (dead1 b1 c11)
    (dead1 b1 c16)
)
  (:goal (and (at b1 c51))))
