;; Sokoban level ringstuck5. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   #######
;;   #.....#
;;   #.###.#
;;   #.###.#
;;   #.###.#
;;   #.....#
;;   #######
;;
;; player c11; boxes b1@c12; goals b1@c41
(define (problem sokoban-ringstuck5)
  (:domain sokoban-guarded)
  (:objects
    c11 c12 c13 c14 c15 c21 c25 c31 c35 c41 c45 c51 c52 c53 c54 c55 - cell
    b1 - box
    down left right up - dir)
  (:init
    (at-player c11)
    (at b1 c12)
    (clear c13)
    (clear c14)
    (clear c15)
    (clear c21)
    (clear c25)
    (clear c31)
    (clear c35)
    (clear c41)
    (clear c45)
    (clear c51)
    (clear c52)
    (clear c53)
    (clear c54)
    (clear c55)
    (adj c11 c21 down)
    (adj c11 c12 right)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c13 c12 left)
    (adj c13 c14 right)
    (adj c14 c13 left)
    (adj c14 c15 right)
    (adj c15 c25 down)
    (adj c15 c14 left)
    (adj c21 c31 down)
    (adj c21 c11 up)
    (adj c25 c35 down)
    (adj c25 c15 up)
    (adj c31 c41 down)
    (adj c31 c21 up)
    (adj c35 c45 down)
    (adj c35 c25 up)
    (adj c41 c51 down)
    (adj c41 c31 up)
    (adj c45 c55 down)
    (adj c45 c35 up)
    (adj c51 c52 right)
    (adj c51 c41 up)
    (adj c52 c51 left)
    (adj c52 c53 right)
    (adj c53 c52 left)
    (adj c53 c54 right)
    (adj c54 c53 left)
    (adj c54 c55 right)
    (adj c55 c54 left)
    (adj c55 c45 up)
    ;; deadlock theorems, compiled in by bench/compile_theorems.py
    (dead1 b1 c11)
    (dead1 b1 c15)
)
  (:goal (and (at b1 c41))))
