;; Sokoban with the deadlock theorems compiled in (indexed guard).
;; Generated by bench/compile_theorems.py -- do not edit by hand.
;;
;; Identical to fixtures/data/sokoban_domain.pddl except that `push` may not
;; create a state matching a proved dead pattern.  `dead1` and `deadpair` are
;; static -- no action adds or deletes them -- so they cost grounding, not search.
(define (domain sokoban-guarded)
  (:requirements :strips :typing :negative-preconditions)
  (:types cell box dir)
  (:predicates
    (at-player ?c - cell)
    (at ?b - box ?c - cell)
    (clear ?c - cell)
    (adj ?from - cell ?to - cell ?d - dir)
    (dead1 ?b - box ?c - cell)
    (deadpair ?b1 - box ?c1 - cell ?b2 - box ?c2 - cell)
    (npair0 ?b - box ?c - cell)
    (npair1 ?b - box ?c - cell)
    (deadpair1 ?b - box ?c - cell ?ob - box ?oc - cell))

  (:action move
    :parameters (?from - cell ?to - cell ?d - dir)
    :precondition (and (at-player ?from) (clear ?to) (adj ?from ?to ?d))
    :effect (and (at-player ?to) (not (at-player ?from))
                 (clear ?from) (not (clear ?to))))

  (:action push-pair0
    :parameters (?p - cell ?from - cell ?to - cell ?b - box ?d - dir)
    :precondition (and (at-player ?p) (at ?b ?from) (clear ?to)
                       (adj ?p ?from ?d) (adj ?from ?to ?d)
                       (not (dead1 ?b ?to))
                       (npair0 ?b ?to))
    :effect (and (at-player ?from) (not (at-player ?p)) (clear ?p)
                 (at ?b ?to) (not (at ?b ?from))
                 (not (clear ?to)) (not (clear ?from))))
  (:action push-pair1
    :parameters (?p - cell ?from - cell ?to - cell ?b - box ?d - dir ?ob1 - box ?oc1 - cell)
    :precondition (and (at-player ?p) (at ?b ?from) (clear ?to)
                       (adj ?p ?from ?d) (adj ?from ?to ?d)
                       (not (dead1 ?b ?to))
                       (npair1 ?b ?to)
                       (deadpair1 ?b ?to ?ob1 ?oc1)
                       (not (at ?ob1 ?oc1)))
    :effect (and (at-player ?from) (not (at-player ?p)) (clear ?p)
                 (at ?b ?to) (not (at ?b ?from))
                 (not (clear ?to)) (not (clear ?from)))))
