"""Shared plumbing for the figure data extractors.

Every extractor in this directory obeys the same three rules:

* it reads only files that are already in the repository — no network, no API,
  no model call;
* it writes one JSON payload under ``figures/data/`` and one plain-text
  rendering under ``figures/``, and nothing else;
* it is byte-deterministic: ``sort_keys=True``, ``ensure_ascii=False``, LF
  endings, no timestamps in the payload.

The last rule is the load-bearing one. A figure whose data cannot be
regenerated byte-for-byte is a figure a reviewer cannot check.
"""

from __future__ import annotations

import json
from pathlib import Path

FIG_DIR = Path(__file__).resolve().parent
DATA_DIR = FIG_DIR / "data"
PAPER_DIR = FIG_DIR.parent
REPO = PAPER_DIR.parent.parent


def repo_text(rel: str) -> str:
    """Read a repo-relative file as UTF-8. Never guesses the locale."""
    return (REPO / rel).read_text(encoding="utf-8")


def repo_json(rel: str):
    return json.loads(repo_text(rel))


def emit(name: str, payload: dict, rendering: str) -> None:
    """Write ``data/<name>.json`` and ``<name>.txt``, both LF, both stable."""
    DATA_DIR.mkdir(exist_ok=True)
    blob = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    (DATA_DIR / f"{name}.json").write_text(blob, encoding="utf-8", newline="\n")
    (FIG_DIR / f"{name}.txt").write_text(
        rendering if rendering.endswith("\n") else rendering + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {DATA_DIR.name}/{name}.json and {name}.txt")


def rule(width: int = 78, ch: str = "-") -> str:
    return ch * width
