"""Hand a deadlock theorem to a planner that has no pruning hook.

`fd_adapter.search` takes a `prune` callable and Fast Downward does not -- the
adapter says so in `choose_tier` clause 3, and it is a fact about the backend
rather than a gap in the adapter.  So the question "does a proved deadlock speed
up *the planner*", which is what Theoria 1.9 actually promises, cannot be asked
of the FD rungs by the route the bundled rung uses.

It can be asked by a different route: put the theorem in the task.

## The compilation, and why it preserves the answer

A theorem says: pattern `P` is closed under the action set, and no state
containing `P` is a goal.  Therefore every state containing `P` is dead.

The compilation forbids exactly the transitions that *enter* `P` -- an action is
blocked when its effect would produce a state containing every atom of `P`.  What
that removes from the state space is a set of states from which no goal is
reachable, so:

* every plan of the original task survives (a plan never enters a dead state, or
  it would never reach the goal);
* every plan of the compiled task is a plan of the original (the compiled action
  set is a subset of the original one, with the same effects);

hence plan existence and **optimal plan length are unchanged**.  Same guarantee
as the pruner, arrived at by editing the task instead of the search.

## What is guarded, and the assumption that is checked rather than assumed

The theorems this rig proves are conjunctions of ground `at(box, cell)` atoms --
the carver restricts its candidate atoms to the predicates the goal mentions, and
in sokoban the goal is about box positions.  `push` is the only schema that adds
`at`, so it is the only one guarded.  Both facts are **checked** in
`guardable()`, which raises rather than emitting a domain whose guard silently
covers less than the theorems do; a guard that misses a transition costs only the
dividend, but one that is written on a false assumption would be a benchmark
reporting a saving it did not make.

## The safety net

Nothing here is trusted.  `bench/dividend.py` validates every plan the compiled
task produces against the **original** domain, using the rig's own independent
replay validator, and asserts the length matches the unguarded optimal rung's.
A guard that is too strong shows up as a longer plan or no plan at all; a guard
that is too weak shows up as no dividend, which is a disappointment rather than a
falsehood.  See `dividend.py` for where those two checks are made.

## The cost side of the ledger

The guard is not free and the artifacts do not pretend it is.  `deadpair` is a
4-ary static predicate, so the problem file grows quadratically in the number of
pair theorems, and the universal precondition makes FD's translator do
noticeably more work.  Both the translator's time and its task-size figure are
recorded, so "the search expanded fewer nodes" and "the run got faster" stay
separate claims.
"""

import os
from typing import Dict, List, Optional, Sequence, Tuple

from engines.deadlock_carver.carve import Theorem
from engines.fd_adapter.pddl import Domain, Problem

# Two guards, because one of them does not fit through the optimal rungs.
#
# **singleton** is `fixtures/data/sokoban_domain.pddl` with one static predicate
# and one negative precondition added to `push`: a box may not be pushed onto a
# cell proved dead for it.  That is still STRIPS, so every rung accepts it.
#
# **full** adds the pair guard -- "there is no other box sitting where it would
# complete a dead pair with the position I am about to create" -- which needs a
# universally quantified negated conjunction, hence `:adl`.
#
# The pair guard is written down here even though the optimal rungs reject it,
# and it is measured rather than dropped.  See MEASURED, below: FD's translator
# turns that quantified precondition into an **axiom**, and `astar(lmcut())` and
# `astar(ipdb())` both refuse a task with axioms (`This configuration does not
# support axioms!`, driver exit 34).  That refusal is one of this run's findings,
# so the encoding that produces it has to exist to be pointed at.
_MOVE = """
  (:action move
    :parameters (?from - cell ?to - cell ?d - dir)
    :precondition (and (at-player ?from) (clear ?to) (adj ?from ?to ?d))
    :effect (and (at-player ?to) (not (at-player ?from))
                 (clear ?from) (not (clear ?to))))
"""

_EFFECT = """
    :effect (and (at-player ?from) (not (at-player ?p)) (clear ?p)
                 (at ?b ?to) (not (at ?b ?from))
                 (not (clear ?to)) (not (clear ?from)))))
"""

_HEADER = """;; Sokoban with the deadlock theorems compiled in (%s guard).
;; Generated by bench/compile_theorems.py -- do not edit by hand.
;;
;; Identical to fixtures/data/sokoban_domain.pddl except that `push` may not
;; create a state matching a proved dead pattern.  `dead1` and `deadpair` are
;; static -- no action adds or deletes them -- so they cost grounding, not search.
(define (domain %s)
  (:requirements %s)
  (:types cell box dir)
  (:predicates
    (at-player ?c - cell)
    (at ?b - box ?c - cell)
    (clear ?c - cell)
    (adj ?from - cell ?to - cell ?d - dir)
    (dead1 ?b - box ?c - cell)
    (deadpair ?b1 - box ?c1 - cell ?b2 - box ?c2 - cell))
"""

SINGLETON_DOMAIN = (
    _HEADER % ("singleton", "sokoban-guarded", ":strips :typing :negative-preconditions")
    + _MOVE
    + """
  (:action push
    :parameters (?p - cell ?from - cell ?to - cell ?b - box ?d - dir)
    :precondition (and (at-player ?p) (at ?b ?from) (clear ?to)
                       (adj ?p ?from ?d) (adj ?from ?to ?d)
                       (not (dead1 ?b ?to)))"""
    + _EFFECT
)

FULL_DOMAIN = (
    _HEADER % ("full", "sokoban-guarded", ":adl :typing")
    + _MOVE
    + """
  (:action push
    :parameters (?p - cell ?from - cell ?to - cell ?b - box ?d - dir)
    :precondition (and (at-player ?p) (at ?b ?from) (clear ?to)
                       (adj ?p ?from ?d) (adj ?from ?to ?d)
                       (not (dead1 ?b ?to))
                       (forall (?ob - box ?oc - cell)
                         (or (not (deadpair ?b ?to ?ob ?oc))
                             (not (at ?ob ?oc)))))"""
    + _EFFECT
)

GUARDS = {"singleton": SINGLETON_DOMAIN, "full": FULL_DOMAIN}

GUARD_PREDICATE = "at"                   # the predicate the theorems talk about
GUARD_SCHEMA = "push"                    # the only schema that adds it


class NotGuardable(RuntimeError):
    """A theorem this compilation cannot express, stated rather than skipped."""


def guardable(domain: Domain, theorems: Sequence[Theorem]) -> None:
    """Check the two assumptions the guard rests on, and raise on either.

    1. Every theorem atom is `at(box, cell)`.  The guard tests `dead1`/`deadpair`
       on `push`'s `?b`/`?to`, so an atom about anything else would not be
       covered and the compiled task would keep a transition the theorem forbids.
    2. `push` is the only schema adding `at`.  If `move` (or anything added
       later) could add a box position, guarding `push` alone would leave a way
       into the dead region.

    Both are true of the sokoban fixture today.  Neither is true by definition,
    which is why they are asserted at compile time rather than believed.
    """
    for theorem in theorems:
        for atom in theorem.pattern:
            if atom[0] != GUARD_PREDICATE or len(atom) != 3:
                raise NotGuardable(
                    "theorem atom %r is not %s(box,cell); the guard would not "
                    "cover it" % (atom, GUARD_PREDICATE)
                )
        if theorem.size > 2:
            raise NotGuardable(
                "pattern of size %d; the guard expresses singletons and pairs"
                % theorem.size
            )

    adders = sorted(
        action.name
        for action in domain.actions
        if any(effect[0] == GUARD_PREDICATE for effect in action.add_effects)
    )
    if adders != [GUARD_SCHEMA]:
        raise NotGuardable(
            "schemas adding %s are %s; the guard only covers %r"
            % (GUARD_PREDICATE, adders, GUARD_SCHEMA)
        )


def guard_facts(theorems: Sequence[Theorem], guard: str = "full"
                ) -> Tuple[List[str], List[str]]:
    """The static facts that turn the theorems into preconditions.

    Pairs are emitted in **both** orders.  The guard fires on the box being
    pushed, and either box of a dead pair can be the one that completes it, so a
    single ordering would catch the pattern only when it is created from one
    side -- which is exactly the kind of half-guard that shows up as a smaller
    dividend rather than as an error.

    Under the `singleton` guard the pair facts are not emitted at all rather
    than emitted and ignored: `push` has no precondition reading `deadpair`
    there, so writing them would inflate the task size the artifacts report
    without changing a single transition -- a cost charged against a dividend
    that was never collected.
    """
    singles: List[str] = []
    pairs: List[str] = []
    for theorem in theorems:
        if theorem.size == 1:
            (_, box, cell), = theorem.pattern
            singles.append("(dead1 %s %s)" % (box, cell))
        elif guard == "full":
            (_, b1, c1), (_, b2, c2) = theorem.pattern
            pairs.append("(deadpair %s %s %s %s)" % (b1, c1, b2, c2))
            pairs.append("(deadpair %s %s %s %s)" % (b2, c2, b1, c1))
    return sorted(set(singles)), sorted(set(pairs))


def guarded_problem_text(problem_text: str, theorems: Sequence[Theorem],
                         guard: str = "full") -> str:
    """The original problem with the guard facts spliced into `:init`.

    Splicing text rather than re-rendering the problem is deliberate: the
    original `:init` reaches Fast Downward byte for byte, so a difference in the
    measurement cannot come from this module having re-serialised the instance
    slightly differently.
    """
    singles, pairs = guard_facts(theorems, guard)
    facts = singles + pairs
    marker = "(:goal"
    index = problem_text.rindex(marker)
    head, tail = problem_text[:index], problem_text[index:]

    # `:init` is the block just before `:goal`; close it, add ours, reopen nothing.
    closing = head.rindex(")")
    block = "\n    ;; deadlock theorems, compiled in by bench/compile_theorems.py\n"
    block += "\n".join("    %s" % fact for fact in facts)
    guarded_head = head[:closing] + block + "\n" + head[closing:]
    return (
        guarded_head.replace("(:domain sokoban)", "(:domain sokoban-guarded)")
        + tail
    )


def write_guarded(directory: str, name: str, problem_text: str,
                  theorems: Sequence[Theorem], guard: str = "full"
                  ) -> Tuple[str, str]:
    """Write the guarded domain and problem for one guard; returns their paths."""
    if guard not in GUARDS:
        raise ValueError("unknown guard %r; have %s" % (guard, ", ".join(sorted(GUARDS))))
    os.makedirs(directory, exist_ok=True)
    domain_path = os.path.join(directory, "sokoban_guarded_%s_domain.pddl" % guard)
    problem_path = os.path.join(directory, "%s_guarded_%s.pddl" % (name, guard))
    with open(domain_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(GUARDS[guard])
    with open(problem_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(guarded_problem_text(problem_text, theorems, guard))
    return domain_path, problem_path


def guard_size(theorems: Sequence[Theorem], guard: str = "full") -> Dict[str, int]:
    """What the guard costs the problem file, before the planner sees it."""
    singles, pairs = guard_facts(theorems, guard)
    return {
        "guard": guard,
        "dead1_facts": len(singles),
        "deadpair_facts": len(pairs),
        "guard_facts_total": len(singles) + len(pairs),
        # How much of the proved evidence this guard can actually carry.  The
        # singleton guard leaves every pair theorem on the floor, and the table
        # has to say so next to the dividend it reports.
        "theorems_total": len(theorems),
        "theorems_expressed": (
            len(singles) if guard == "singleton" else len(theorems)
        ),
    }
