"""Concatenate `sections/*.md` into `PAPER.md`, in filename order.

The sections are the editable source; `PAPER.md` is generated and should not be
hand-edited. Deterministic: no timestamp, LF endings, sections joined in sorted
order, one blank line and a horizontal rule between them.

    python papers/phase1-workshop/assemble.py
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent
SECTIONS = HERE / "sections"
OUT = HERE / "PAPER.md"

BANNER = (
    "<!-- GENERATED by assemble.py from sections/*.md — edit the sections, "
    "not this file. -->\n\n"
)


def main() -> None:
    parts = []
    for path in sorted(SECTIONS.glob("*.md")):
        parts.append(path.read_text(encoding="utf-8").rstrip("\n"))
    body = "\n\n---\n\n".join(parts) + "\n"
    OUT.write_text(BANNER + body, encoding="utf-8", newline="\n")
    words = len(body.split())
    print(f"wrote {OUT.name}: {len(parts)} sections, ~{words} words")


if __name__ == "__main__":
    main()
