"""Mechanical gate for the Phase 1 workshop draft.

`CITECHECK.md` is a *report*: a human-run audit against one sha256 of `PAPER.md`,
which has since moved. A report cannot fail a build. This is the executable half
of the same rule, and it is meant to be run before every push that touches
`papers/phase1-workshop/`.

Four checks, each independently reported, exit code 1 if any fails:

  A. GENERATED   `PAPER.md` is byte-identical to `assemble.py`'s output from
                 `sections/*.md`. The header says "do not hand-edit"; this is the
                 test of it.
  B. PATHS       Every path-like token cited in backticks in `sections/*.md`
                 resolves. Three verdicts, not two:
                   ok         -- resolves repo-relative, unambiguously
                   AMBIGUOUS  -- the token's leading directory exists BOTH at the
                                 repo root and beside PAPER.md, so a reader
                                 resolving it locally lands somewhere else or
                                 nowhere. `figures/` is the live instance: the
                                 paper cites the root pipeline's fig05/06/07
                                 while sitting next to a local `figures/` holding
                                 three homonymous plates.
                   BROKEN     -- resolves nowhere
  C. FIGDATA     The three local figure extractors are byte-deterministic: rerun
                 into a scratch tree and compare against `figures/data/*.json`.
  D. NOSECRET    No `.env` value, and nothing shaped like the ARC key, appears in
                 any file this directory publishes.

Run:  python papers/phase1-workshop/verify_paper.py
      python papers/phase1-workshop/verify_paper.py --quiet   (verdict lines only)

No network, no API key, no model call, no game spend.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SECTIONS = HERE / "sections"

# A backticked token counts as a path claim if it has a directory separator and
# a plausible extension, or ends in a separator. This deliberately misses bare
# filenames (`PAPER.md`) -- those are the 31 non-repo-relative citations
# CITECHECK already counted, and they are a style finding, not a broken link.
PATH_TOKEN = re.compile(r"`([A-Za-z0-9_.\-/]+/[A-Za-z0-9_.\-/]*)`")

# Tokens that look like paths but are not repository paths.
NOT_A_PATH = re.compile(
    r"^(https?:|arxiv|doi|[0-9]+/[0-9]+$)"  # urls, dois, and fractions like 276/276
    r"|^[0-9]+/[0-9]+"                       # 34/38, 252/252, ...
)

# Directories that legitimately do not exist in a checkout.
GITIGNORED_BY_DESIGN = (
    ".toolchain/",
    "figures/.verify/",
    ".worktrees/",
)

# Ambiguities that have been looked at and ruled on, each with its adjudication.
# The rule is `figures/PARITY.md`'s: the paper cites the repository-root figure
# pipeline, and the three homonymous plates under `papers/phase1-workshop/figures/`
# are kept deliberately as a second opinion rather than deleted. An ambiguity NOT
# listed here fails, because it is new and nobody has ruled on it. A permanently
# red check is a check people learn to scroll past; a check that hides its
# rulings is worse than no check.
ADJUDICATED_AMBIGUITY = {
    token: "repo-root figure pipeline; the local figures/ is the witness (figures/PARITY.md)"
    for token in (
        "figures/fig05_a2_repair_loop.py",
        "figures/fig06_concept_timeline.py",
        "figures/fig07_a0_vs_a0prime.py",
        "figures/out/light/fig05_a2_repair_loop.svg",
        "figures/out/light/fig06_concept_timeline.svg",
        "figures/out/light/fig07_a0_vs_a0prime.svg",
        "figures/out/dark/fig06_concept_timeline.svg",
        "figures/csv/fig05_a2_repair_loop.csv",
        "figures/csv/fig06_concept_timeline.csv",
        "figures/csv/fig07_a0_vs_a0prime.csv",
    )
}


def fail(msg: str) -> str:
    return msg


def check_generated() -> tuple[bool, list[str]]:
    """A. PAPER.md must equal a fresh assemble of sections/."""
    notes: list[str] = []
    banner = (
        "<!-- GENERATED by assemble.py from sections/*.md — edit the sections, "
        "not this file. -->\n\n"
    )
    parts = [p.read_text(encoding="utf-8").rstrip("\n") for p in sorted(SECTIONS.glob("*.md"))]
    expected = banner + "\n\n---\n\n".join(parts) + "\n"
    actual = (HERE / "PAPER.md").read_text(encoding="utf-8")
    if actual == expected:
        notes.append(f"  {len(parts)} sections, {len(expected.split())} words, byte-identical")
        return True, notes
    notes.append(fail("  PAPER.md differs from assemble.py's output -- it was hand-edited,"))
    notes.append(fail("  or a section changed and assemble.py was not rerun. Run:"))
    notes.append(fail("      python papers/phase1-workshop/assemble.py"))
    if len(actual) != len(expected):
        notes.append(f"  ({len(actual)} bytes on disk vs {len(expected)} regenerated)")
    return False, notes


def classify(token: str) -> str:
    """ok / RULED / AMBIGUOUS / ELIDED / BROKEN / skip, for one cited path token."""
    if NOT_A_PATH.search(token):
        return "skip"
    if token.startswith(".../") or "/.../" in token:
        # `.../MANIFEST.json` is a typographic elision, not a link. It still
        # breaks the binding rule -- a reader cannot resolve it -- so it is
        # reported, but it is a different defect from a path that does not exist.
        return "ELIDED"
    if any(token.startswith(g) or f"/{g}" in token for g in GITIGNORED_BY_DESIGN):
        return "skip"

    at_root = (ROOT / token).exists()
    at_local = (HERE / token).exists()

    head = token.split("/", 1)[0]
    head_both = (ROOT / head).is_dir() and (HERE / head).is_dir()

    if at_root and at_local and (ROOT / token).resolve() == (HERE / token).resolve():
        return "ok"

    if at_root or at_local:
        # Resolves -- but if the leading directory also exists in both trees, a
        # reader resolving relative to PAPER.md lands somewhere else or nowhere.
        if (at_root and at_local) or head_both:
            return "RULED" if token in ADJUDICATED_AMBIGUITY else "AMBIGUOUS"
        return "ok"
    return "BROKEN"


def check_paths() -> tuple[bool, list[str]]:
    """B. Every cited path resolves, and unambiguously."""
    notes: list[str] = []
    seen: dict[str, tuple[str, str]] = {}  # token -> (verdict, first section seen in)
    for section in sorted(SECTIONS.glob("*.md")):
        for token in PATH_TOKEN.findall(section.read_text(encoding="utf-8")):
            if token in seen:
                continue
            verdict = classify(token)
            if verdict != "skip":
                seen[token] = (verdict, section.name)

    def of(kind: str) -> list[str]:
        return sorted(t for t, (v, _) in seen.items() if v == kind)

    ok, ruled = of("ok"), of("RULED")
    amb, elided, broken = of("AMBIGUOUS"), of("ELIDED"), of("BROKEN")

    notes.append(f"  {len(seen)} distinct path citations: {len(ok)} ok, "
                 f"{len(ruled)} ambiguous-but-ruled, {len(amb)} ambiguous-unruled, "
                 f"{len(elided)} elided, {len(broken)} broken")
    for t in broken:
        notes.append(fail(f"  BROKEN    {t}   ({seen[t][1]}) -- resolves from neither the repo "
                          f"root nor beside PAPER.md"))
    for t in elided:
        notes.append(fail(f"  ELIDED    {t}   ({seen[t][1]}) -- an ellipsis is not a path a "
                          f"reader can follow; the binding rule wants the whole thing"))
    for t in amb:
        notes.append(fail(f"  AMBIGUOUS {t}   ({seen[t][1]}) -- `{t.split('/', 1)[0]}/` exists "
                          f"both at the repo root and beside PAPER.md, and nobody has ruled "
                          f"which one this means"))
    for t in ruled:
        notes.append(f"  ruled     {t} -- {ADJUDICATED_AMBIGUITY[t]}")
    return not (broken or amb or elided), notes


def check_figdata() -> tuple[bool, list[str]]:
    """C. The local figure extractors are byte-deterministic.

    They are run *in place*, not in a scratch copy: each one locates the
    repository by walking up from its own `__file__`, so a copied script reads a
    different tree and the test would measure the harness instead of the code.
    Running in place is safe precisely because the property under test is
    idempotence -- if the extractors are deterministic and the committed payloads
    are current, the run is a no-op. If it is not a no-op that is the finding, and
    the original bytes are restored before returning either way.
    """
    notes: list[str] = []
    scripts = sorted(HERE.glob("figures/fig[0-9]*.py"))
    if not scripts:
        return False, [fail("  no figure extractors found under figures/")]

    data_dir = HERE / "figures" / "data"
    before = {p: p.read_bytes() for p in sorted(data_dir.glob("*.json"))}
    drifted: list[str] = []
    try:
        for script in scripts:
            r = subprocess.run(
                [sys.executable, str(script)],
                capture_output=True, text=True, cwd=str(HERE),
            )
            if r.returncode != 0:
                last = (r.stderr or r.stdout).strip().splitlines()[-1:] or ["(no output)"]
                drifted.append(f"{script.name} exited {r.returncode}: {last[0]}")
                continue
            payload = data_dir / f"{script.stem}.json"
            if not payload.exists():
                drifted.append(f"{script.stem}.json was not regenerated")
            elif payload.read_bytes() != before.get(payload, b""):
                drifted.append(f"{script.stem}.json changed on rerun -- the committed payload "
                               f"is stale, or the extractor is not deterministic")
    finally:
        for path, blob in before.items():
            if path.read_bytes() != blob:
                path.write_bytes(blob)

    if drifted:
        notes.extend(fail(f"  {d}") for d in drifted)
        return False, notes
    notes.append(f"  {len(scripts)} extractors reran in place, {len(before)} payloads unchanged")
    return True, notes


def check_nosecret() -> tuple[bool, list[str]]:
    """D. No credential value anywhere under this directory."""
    notes: list[str] = []
    env = ROOT / ".env"
    secrets = []
    if env.exists():
        for line in env.read_text(encoding="utf-8", errors="replace").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                value = line.split("=", 1)[1].strip().strip("'\"")
                if len(value) >= 12:
                    secrets.append(value)
    hits = []
    for path in sorted(HERE.rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for value in secrets:
            if value in text:
                # Never print the value.
                hits.append(f"  a .env value appears in {path.relative_to(ROOT)}")
    if hits:
        notes.extend(fail(h) for h in hits)
        return False, notes
    notes.append(f"  {len(secrets)} .env value(s) checked against every published file: absent"
                 if secrets else "  no .env present to check against (nothing to leak)")
    return True, notes


CHECKS = [
    ("A GENERATED", "PAPER.md == assemble(sections/)", check_generated),
    ("B PATHS", "every cited path resolves, unambiguously", check_paths),
    ("C FIGDATA", "figure extractors are byte-deterministic", check_figdata),
    ("D NOSECRET", "no credential value in any published file", check_nosecret),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--quiet", action="store_true", help="verdict lines only")
    args = ap.parse_args()

    failures = []
    for tag, blurb, fn in CHECKS:
        passed, notes = fn()
        print(f"[{'PASS' if passed else 'FAIL'}] {tag} -- {blurb}")
        if not args.quiet or not passed:
            for n in notes:
                print(n)
        if not passed:
            failures.append(tag)

    print()
    if failures:
        print(f"verify_paper: FAIL ({len(failures)}/{len(CHECKS)}) -- {', '.join(failures)}")
        return 1
    print(f"verify_paper: PASS ({len(CHECKS)}/{len(CHECKS)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
