;; Sokoban level ell. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #..###
;;   #..###
;;   #....#
;;   #....#
;;   ######
;;
;; player c44; boxes b1@c22, b2@c33; goals b1@c42, b2@c12
(define (problem sokoban-ell)
  (:domain sokoban)
  (:objects
    c11 c12 c21 c22 c31 c32 c33 c34 c41 c42 c43 c44 - cell
    b1 b2 - box
    down left right up - dir)
  (:init
    (at b1 c22)
    (at b2 c33)
    (at-player c44)
    (clear c11)
    (clear c12)
    (clear c21)
    (clear c31)
    (clear c32)
    (clear c34)
    (clear c41)
    (clear c42)
    (clear c43)
    (adj c11 c12 right)
    (adj c11 c21 down)
    (adj c12 c11 left)
    (adj c12 c22 down)
    (adj c21 c11 up)
    (adj c21 c22 right)
    (adj c21 c31 down)
    (adj c22 c12 up)
    (adj c22 c21 left)
    (adj c22 c32 down)
    (adj c31 c21 up)
    (adj c31 c32 right)
    (adj c31 c41 down)
    (adj c32 c22 up)
    (adj c32 c31 left)
    (adj c32 c33 right)
    (adj c32 c42 down)
    (adj c33 c32 left)
    (adj c33 c34 right)
    (adj c33 c43 down)
    (adj c34 c33 left)
    (adj c34 c44 down)
    (adj c41 c31 up)
    (adj c41 c42 right)
    (adj c42 c32 up)
    (adj c42 c41 left)
    (adj c42 c43 right)
    (adj c43 c33 up)
    (adj c43 c42 left)
    (adj c43 c44 right)
    (adj c44 c34 up)
    (adj c44 c43 left))
  (:goal (and (at b1 c42) (at b2 c12))))
