#!/usr/bin/env sh
# verify.sh -- A30 / agent/a30-wall-clock-8h
# generated by .claude/skills/verify-gate at 2026-08-04T14:42:28Z; base 18e7d81
#
# Every check runs even after one fails: a red run must print the whole
# checklist, not stop at the first red. Exit 0 only when every line is PASS.
#
#   sh verify.sh            (from anywhere -- it finds its own worktree root)
#   PYTHON=python3 sh verify.sh
set -u

ROOT=$(cd "$(dirname "$0")" && git rev-parse --show-toplevel) || exit 2
cd "$ROOT" || exit 2
PY=${PYTHON:-python}
export PY                       # `check` runs its command in `sh -c`, a new process
export PYTHONIOENCODING=utf-8   # this repo's prose is Chinese; consoles here are not UTF-8
PASS=0
FAIL=0
LOGDIR=$(mktemp -d 2>/dev/null || printf '%s' "${TMPDIR:-/tmp}/verify.$$")
mkdir -p "$LOGDIR" || exit 2

check() {
  _name=$1
  shift
  if sh -c "$*" >"$LOGDIR/out" 2>&1; then
    printf '[PASS] %s\n' "$_name"
    PASS=$((PASS + 1))
  else
    printf '[FAIL] %s\n' "$_name"
    tail -n 30 "$LOGDIR/out" | sed -e 's/^/       | /'
    FAIL=$((FAIL + 1))
  fi
}

printf '== verify.sh :: %s :: %s ==\n' 'A30' 'agent/a30-wall-clock-8h'
check 'tests -- theoria-arm' 'cd theoria-arm && "$PY" -m pytest -q'
check 'MANIFEST hashes reproduce' '"$PY" .claude/skills/runs-archive/scripts/runs_archive.py check --run theoria-arm/runs/2026-08-04T143015Z-A30-wall-clock-8h'
check 'boundary -- only theoria-arm changed' '"$PY" .claude/skills/verify-gate/scripts/guards.py boundary --base 18e7d81b72a16f223a064d9b5cd09b3e7e9a965e --territory theoria-arm'
check 'sealed pile untouched' '"$PY" .claude/skills/verify-gate/scripts/guards.py sealed --base 18e7d81b72a16f223a064d9b5cd09b3e7e9a965e'
check 'credential never entered a tracked file' '"$PY" .claude/skills/verify-gate/scripts/guards.py secret --base 18e7d81b72a16f223a064d9b5cd09b3e7e9a965e'
check 'delivered: theoria-arm/runs/2026-08-04T143015Z-A30-wall-clock-8h/MANIFEST.json' 'test -e '\''theoria-arm/runs/2026-08-04T143015Z-A30-wall-clock-8h/MANIFEST.json'\'''
check 'the lease still outlives the default wall clock' 'cd theoria-arm && python -m pytest tests/test_desk_gate.py -q -k '\''wall_clock or lease or TTL'\'''

printf -- '-- %s/%s green' "$PASS" "$((PASS + FAIL))"
if [ "$FAIL" -eq 0 ]; then
  printf '\n'
  exit 0
fi
printf '  <<< NOT GREEN (%s red)\n' "$FAIL"
exit 1
