;; Sokoban level tee. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   #######
;;   #.....#
;;   ###.###
;;   ###.###
;;   #.....#
;;   ###.###
;;   #######
;;
;; player c53; boxes b1@c33; goals b1@c13
(define (problem sokoban-tee)
  (:domain sokoban-guarded)
  (:objects
    c11 c12 c13 c14 c15 c23 c33 c41 c42 c43 c44 c45 c53 - cell
    b1 - box
    down left right up - dir)
  (:init
    (at-player c53)
    (at b1 c33)
    (clear c11)
    (clear c12)
    (clear c13)
    (clear c14)
    (clear c15)
    (clear c23)
    (clear c41)
    (clear c42)
    (clear c43)
    (clear c44)
    (clear c45)
    (adj c11 c12 right)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c13 c23 down)
    (adj c13 c12 left)
    (adj c13 c14 right)
    (adj c14 c13 left)
    (adj c14 c15 right)
    (adj c15 c14 left)
    (adj c23 c33 down)
    (adj c23 c13 up)
    (adj c33 c43 down)
    (adj c33 c23 up)
    (adj c41 c42 right)
    (adj c42 c41 left)
    (adj c42 c43 right)
    (adj c43 c53 down)
    (adj c43 c42 left)
    (adj c43 c44 right)
    (adj c43 c33 up)
    (adj c44 c43 left)
    (adj c44 c45 right)
    (adj c45 c44 left)
    (adj c53 c43 up)
    ;; deadlock theorems, compiled in by bench/compile_theorems.py

)
  (:goal (and (at b1 c13))))
