"""Process 3 — de-redundancy.

`Theoria.md`: *相关性聚类，一族留代表——二十个互相相关的数字不是二十个发现.*

Spearman rather than Pearson: these metrics are ratios, counts and shares on
wildly different scales, and monotone agreement is what "says the same thing"
actually means here.

Clustering is single-linkage at |rho| >= 0.9 — transitive by construction, so
the result does not depend on the order metrics arrive in. That determinism is
worth more than a cleverer algorithm: two runs of the battery must produce the
same clusters, and an agglomerative method with a tie-break would not promise
that.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence, Tuple

from battery.audit.stats import spearman
from battery.metrics import REGISTRY, Value

THRESHOLD = 0.9
MIN_SHARED = 4      # fewer than four shared runs and a correlation is noise


def as_markdown(result: Dict[str, object]) -> str:
    """The clustering basis and every elimination, in reviewable form.

    `Theoria.md` process 3 asks for a de-redundancy pass, and a list of
    surviving metrics is not a reviewable one: "these two say the same thing"
    is a claim about a correlation, over a sample, at a threshold, and none of
    those travel with a bare list. This is generated from the same artefact the
    recompute writes, so it cannot drift from what the code actually did.
    """
    lines: List[str] = []
    out = lines.append
    out("# De-redundancy — process 3, generated by `battery.run_battery`")
    out("")
    out("**Do not edit by hand.** Regenerate with "
        "`python -m battery.run_battery`.")
    out("")
    out("> `Theoria.md` Phase 2 process 3: *相关性聚类，一族留代表——二十个互相"
        "相关的数字不是二十个发现.*")
    out("")
    out("## Method")
    out("")
    out("- %s" % result["method"])
    out("- A pair needs **%d shared runs** to be correlated at all; below that "
        "it is reported as unmeasurable rather than as zero."
        % result["min_shared_runs"])
    out("- **One representative per family, not per cluster.** A cluster that "
        "spans families keeps one representative in each, so no metric is ever "
        "retired by a metric answering a different question.")
    out("- Representatives are chosen by **coverage** — the count of usable "
        "values — with ties broken by id. Nothing consults a value, so the "
        "choice cannot be made after seeing the numbers.")
    out("")
    out("## Coverage of the correlation matrix")
    out("")
    out("| | |")
    out("|---|---|")
    out("| metric pairs | %d |" % result["n_pairs"])
    out("| pairs with enough shared runs to correlate | **%d** |"
        % result["n_pairs_measured"])
    out("| pairs that share too few runs | %d |"
        % result["n_pairs_unmeasurable"])
    out("| clusters | %d of %d metrics |"
        % (result["n_clusters"], result["n_metrics"]))
    out("| metrics retired into a representative | **%d** |"
        % result["n_eliminated"])
    out("")
    out("%s" % result["coverage_note"])
    out("")

    strong = result["strong_pairs"]
    out("## The pairs that did the clustering (|rho| >= %.1f)"
        % result["threshold"])
    out("")
    if not strong:
        out("None. Nothing was merged.")
    else:
        out("| a | b | rho |")
        out("|---|---|---|")
        for pair in strong:
            out("| %s | %s | %+.3f |" % (pair["a"], pair["b"], pair["rho"]))
    out("")

    out("## Clusters")
    out("")
    for entry in result["clusters"]:
        members = entry["members"]
        if len(members) < 2:
            continue
        out("### %s" % " ~ ".join(members))
        out("")
        reps = entry["representatives_by_family"]
        out("- families: %s" % ", ".join(entry["families"]))
        out("- representative%s: %s"
            % ("" if len(reps) == 1 else "s",
               ", ".join("**%s** (%s)" % (r, f) for f, r in sorted(reps.items()))))
        out("- coverage: %s"
            % ", ".join("%s=%d" % (m, entry["coverage"][m]) for m in members))
        if entry.get("warning"):
            out("")
            out("> **Cross-family.** %s" % entry["warning"])
        out("")

    out("## Retired metrics, and why")
    out("")
    out("Retired is **not deleted**. Every metric below is still computed, "
        "still reported, and still correlated; it is excluded from being "
        "counted as an independent finding.")
    out("")
    if not result["eliminated"]:
        out("None.")
    else:
        for entry in result["eliminated"]:
            rho_value = entry["rho_with_representative"]
            out("### %s (%s) → represented by %s"
                % (entry["metric"], entry["family"], entry["represented_by"]))
            out("")
            out("- rho with representative: %s over %d shared runs"
                % ("unmeasurable" if rho_value is None else "%+.3f" % rho_value,
                   entry["shared_runs"]))
            out("- coverage: %d against the representative's %d"
                % (entry["coverage"], entry["representative_coverage"]))
            out("- %s" % entry["reason"])
            out("")
    return "\n".join(lines).rstrip() + "\n"


def _series(values: Dict[str, Dict[str, Value]],
            metric_id: str) -> Dict[str, float]:
    out: Dict[str, float] = {}
    for run_id in sorted(values):
        value = values[run_id].get(metric_id)
        if value is not None and value.ok and value.value is not None:
            out[run_id] = value.value
    return out


def correlations(values: Dict[str, Dict[str, Value]]
                 ) -> Dict[Tuple[str, str], Optional[float]]:
    series = {mid: _series(values, mid) for mid in sorted(REGISTRY)}
    out: Dict[Tuple[str, str], Optional[float]] = {}
    ids = sorted(REGISTRY)
    for i, a in enumerate(ids):
        for b in ids[i + 1:]:
            shared = sorted(set(series[a]) & set(series[b]))
            if len(shared) < MIN_SHARED:
                out[(a, b)] = None
                continue
            out[(a, b)] = spearman([series[a][k] for k in shared],
                                   [series[b][k] for k in shared])
    return out


def cluster(values: Dict[str, Dict[str, Value]]) -> Dict[str, object]:
    """Group metrics that say the same thing and nominate representatives.

    The representative is the metric with the most usable data, ties broken by
    id. Coverage, not elegance: a cluster's representative has to be the one
    most likely to have a number when it matters, and any tie-break that
    consulted the *values* would let the choice be made after seeing them.

    **One representative per family, not one per cluster.** `Theoria.md`
    process 3 is 相关性聚类，一族留代表 — cluster by correlation, keep a
    representative *per family*. Through v1 this function kept one per cluster,
    and on v2's richer material that became a live defect rather than a
    pedantic one: K6 (epistemic) correlates with X1 and X4 (exploration) at
    rho >= 0.9 over five shared runs, so a single-representative rule elected
    X1 and quietly retired the only epistemic metric in the group. An
    exploration metric cannot stand in for an epistemic one — they answer
    different questions and `Theoria.md` organises the whole battery by family
    for that reason. A correlation across a family boundary on five runs is
    evidence about the sample, not about the metrics.

    Cross-family clusters are therefore flagged rather than trusted, and no
    metric is ever absorbed by a representative from another family.
    """
    ids = sorted(REGISTRY)
    parent = {mid: mid for mid in ids}

    def find(x: str) -> str:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a: str, b: str) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            # Always point at the lexicographically smaller root, so the
            # forest's shape does not depend on iteration order.
            lo, hi = sorted((ra, rb))
            parent[hi] = lo

    rho = correlations(values)
    strong: List[Dict[str, object]] = []
    for (a, b), value in sorted(rho.items()):
        if value is not None and abs(value) >= THRESHOLD:
            union(a, b)
            strong.append({"a": a, "b": b, "rho": round(value, 9)})

    groups: Dict[str, List[str]] = {}
    for mid in ids:
        groups.setdefault(find(mid), []).append(mid)

    coverage = {mid: len(_series(values, mid)) for mid in ids}
    rho_of = {}
    for (a, b), value in rho.items():
        rho_of[(a, b)] = rho_of[(b, a)] = value

    clusters = []
    eliminated = []
    for root in sorted(groups):
        members = sorted(groups[root])
        families = sorted({REGISTRY[m].family for m in members})

        # One representative per family present in the cluster.
        reps = {}
        for family in families:
            in_family = [m for m in members
                         if REGISTRY[m].family == family]
            reps[family] = sorted(in_family, key=lambda m: (-coverage[m], m))[0]

        for member in members:
            family = REGISTRY[member].family
            rep = reps[family]
            if member == rep:
                continue
            value = rho_of.get((member, rep))
            shared = len(set(_series(values, member)) & set(_series(values, rep)))
            eliminated.append({
                "metric": member,
                "family": family,
                "represented_by": rep,
                "rho_with_representative": (None if value is None
                                            else round(value, 9)),
                "shared_runs": shared,
                "coverage": coverage[member],
                "representative_coverage": coverage[rep],
                # Why this one and not the other: coverage, decided before any
                # value was looked at.
                "reason": (
                    "clusters with %s at |rho| >= %.1f (single-linkage, so the "
                    "link may be transitive rather than direct); %s carries %d "
                    "usable values against this metric's %d, so it represents "
                    "the group for the %s family. Not deleted -- still "
                    "computed, reported and correlated, and excluded only from "
                    "being counted as a separate finding."
                    % (rep, THRESHOLD, rep, coverage[rep], coverage[member],
                       family)),
            })

        entry = {
            "members": members,
            # Kept for readers and artefacts written before v2: the highest
            # coverage member overall.  `representatives_by_family` is the one
            # that decides what gets retired.
            "representative": sorted(members,
                                     key=lambda m: (-coverage[m], m))[0],
            "representatives_by_family": reps,
            "families": families,
            "coverage": {m: coverage[m] for m in members},
            "cross_family": len(families) > 1,
        }
        if len(families) > 1:
            entry["warning"] = (
                "this cluster spans %d families (%s). A correlation across a "
                "family boundary is evidence about the sample, not about the "
                "metrics -- these families are answering different questions "
                "and Theoria.md organises the battery by family for that "
                "reason. No metric here is absorbed across the boundary: each "
                "family keeps its own representative."
                % (len(families), ", ".join(families)))
        clusters.append(entry)

    # The basis, not just the verdict.  A cluster assignment is an assertion
    # about every pair that did *not* cluster as much as about the pairs that
    # did, and "these two metrics say the same thing" is not checkable from a
    # list of clusters alone.  Every pair is emitted with its rho and the
    # number of runs the correlation was computed over, so a reader can see
    # which non-clusterings were decisions and which were simply absences --
    # on thin data most pairs share too few runs to correlate at all, and a
    # matrix full of `null` is a very different fact from a matrix full of
    # small correlations.
    pairs = []
    measured = 0
    for (a, b), value in sorted(rho.items()):
        shared = len(set(_series(values, a)) & set(_series(values, b)))
        if value is not None:
            measured += 1
        pairs.append({
            "a": a, "b": b,
            "rho": None if value is None else round(value, 9),
            "shared_runs": shared,
            "reason": (None if value is not None
                       else "fewer than %d shared runs" % MIN_SHARED),
        })

    families: Dict[str, List[str]] = {}
    for mid in ids:
        families.setdefault(REGISTRY[mid].family, []).append(mid)

    return {
        "threshold": THRESHOLD,
        "min_shared_runs": MIN_SHARED,
        "method": ("Spearman rank correlation; single-linkage clustering at "
                   "|rho| >= %.1f, transitive by construction so the result "
                   "does not depend on the order metrics arrive in"
                   % THRESHOLD),
        "n_clusters": len(clusters),
        "n_metrics": len(ids),
        "n_pairs": len(pairs),
        "n_pairs_measured": measured,
        "n_pairs_unmeasurable": len(pairs) - measured,
        "coverage_note": (
            "%d of %d metric pairs share enough runs to correlate at all. A "
            "cluster count near the metric count reflects thin data, not "
            "twenty independent findings."
            % (measured, len(pairs))),
        "strong_pairs": strong,
        "clusters": clusters,
        "representatives": sorted({r for c in clusters
                                   for r in c["representatives_by_family"].values()}),
        "n_eliminated": len(eliminated),
        "eliminated": sorted(eliminated, key=lambda e: e["metric"]),
        "cross_family_clusters": [c["members"] for c in clusters
                                  if c["cross_family"]],
        "by_family": {f: sorted(ms) for f, ms in sorted(families.items())},
        "matrix": pairs,
    }
