;; Sokoban level rnd0033. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #...##
;;   ##...#
;;   #...##
;;   #..#.#
;;   ######
;;
;; player c44; boxes b1@c12, b2@c11; goals b1@c42, b2@c23
(define (problem sokoban-rnd0033)
  (:domain sokoban)
  (:objects
    c11 c12 c13 c22 c23 c24 c31 c32 c33 c41 c42 c44 - cell
    b1 b2 - box
    down left right up - dir)
  (:init
    (at-player c44)
    (at b1 c12)
    (at b2 c11)
    (clear c13)
    (clear c22)
    (clear c23)
    (clear c24)
    (clear c31)
    (clear c32)
    (clear c33)
    (clear c41)
    (clear c42)
    (adj c11 c12 right)
    (adj c12 c22 down)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c13 c23 down)
    (adj c13 c12 left)
    (adj c22 c32 down)
    (adj c22 c23 right)
    (adj c22 c12 up)
    (adj c23 c33 down)
    (adj c23 c22 left)
    (adj c23 c24 right)
    (adj c23 c13 up)
    (adj c24 c23 left)
    (adj c31 c41 down)
    (adj c31 c32 right)
    (adj c32 c42 down)
    (adj c32 c31 left)
    (adj c32 c33 right)
    (adj c32 c22 up)
    (adj c33 c32 left)
    (adj c33 c23 up)
    (adj c41 c42 right)
    (adj c41 c31 up)
    (adj c42 c41 left)
    (adj c42 c32 up))
  (:goal (and (at b1 c42) (at b2 c23))))
