;; Sokoban level rnd0000. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #...##
;;   #....#
;;   #....#
;;   #.#..#
;;   ######
;;
;; player c34; boxes b1@c13, b2@c33, b3@c44; goals b1@c31, b2@c41, b3@c23
(define (problem sokoban-rnd0000)
  (:domain sokoban-guarded)
  (:objects
    c11 c12 c13 c21 c22 c23 c24 c31 c32 c33 c34 c41 c43 c44 - cell
    b1 b2 b3 - box
    down left right up - dir)
  (:init
    (at-player c34)
    (at b1 c13)
    (at b2 c33)
    (at b3 c44)
    (clear c11)
    (clear c12)
    (clear c21)
    (clear c22)
    (clear c23)
    (clear c24)
    (clear c31)
    (clear c32)
    (clear c41)
    (clear c43)
    (adj c11 c21 down)
    (adj c11 c12 right)
    (adj c12 c22 down)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c13 c23 down)
    (adj c13 c12 left)
    (adj c21 c31 down)
    (adj c21 c22 right)
    (adj c21 c11 up)
    (adj c22 c32 down)
    (adj c22 c21 left)
    (adj c22 c23 right)
    (adj c22 c12 up)
    (adj c23 c33 down)
    (adj c23 c22 left)
    (adj c23 c24 right)
    (adj c23 c13 up)
    (adj c24 c34 down)
    (adj c24 c23 left)
    (adj c31 c41 down)
    (adj c31 c32 right)
    (adj c31 c21 up)
    (adj c32 c31 left)
    (adj c32 c33 right)
    (adj c32 c22 up)
    (adj c33 c43 down)
    (adj c33 c32 left)
    (adj c33 c34 right)
    (adj c33 c23 up)
    (adj c34 c44 down)
    (adj c34 c33 left)
    (adj c34 c24 up)
    (adj c41 c31 up)
    (adj c43 c44 right)
    (adj c43 c33 up)
    (adj c44 c43 left)
    (adj c44 c34 up)
    ;; deadlock theorems, compiled in by bench/compile_theorems.py
    (dead1 b1 c13)
    (dead1 b2 c34)
    (dead1 b2 c41)
    (dead1 b2 c43)
    (dead1 b3 c44)
)
  (:goal (and (at b1 c31) (at b2 c41) (at b3 c23))))
