"""Random STRIPS instances -- the fuzz input for `fd_adapter`.

Two families, for two different jobs.

**`sokoban`** exercises the planner on a world with real geometry: random walls,
one or two boxes, random goals.  Most draws are unsolvable, which is deliberate
-- "no plan exists" is a *result* in this adapter and a result nobody checks is a
result nobody can trust.  The domain is the same STRIPS sokoban the fixtures use;
cell names are `c_<r>_<c>` rather than the fixture's `c<r><c>`, because the
latter collides at two digits (`(1,10)` and `(11,0)` both render `c110`) and a
fuzz generator that walks into that would be testing its own bug.

**`abstract`** exercises the *parser and grounder* instead: random predicates of
random arity, random action schemas with positive and negative preconditions,
random add and delete lists.  These worlds mean nothing, which is the point --
there is no geometry for a planner to be accidentally right about, and grounding,
static-atom stripping and plan validation have to stand on their own.

Both families emit PDDL text.  `fd_adapter.solve()` reads files, so the campaign
writes them to a scratch directory; `solve_parsed()` takes the parsed objects
directly and that is what most properties use.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence, Set, Tuple

from fuzzlab.prng import Rng
from fuzzlab.worlds.common import World

Cell = Tuple[int, int]

WALL = "#"
FLOOR = "."

DELTA: Dict[str, Cell] = {
    "down": (1, 0),
    "left": (0, -1),
    "right": (0, 1),
    "up": (-1, 0),
}
DIRECTIONS = tuple(sorted(DELTA))

SOKOBAN_DOMAIN = """;; Sokoban in the STRIPS subset fd_adapter parses.
;; Generated by fuzzlab/worlds/blockworld.py -- do not edit by hand.
(define (domain sokoban)
  (:requirements :strips :typing)
  (:types cell box dir)
  (:predicates
    (at-player ?c - cell)
    (at ?b - box ?c - cell)
    (clear ?c - cell)
    (adj ?from - cell ?to - cell ?d - dir))

  (:action move
    :parameters (?from - cell ?to - cell ?d - dir)
    :precondition (and (at-player ?from) (clear ?to) (adj ?from ?to ?d))
    :effect (and (at-player ?to) (not (at-player ?from))
                 (clear ?from) (not (clear ?to))))

  (:action push
    :parameters (?p - cell ?from - cell ?to - cell ?b - box ?d - dir)
    :precondition (and (at-player ?p) (at ?b ?from) (clear ?to)
                       (adj ?p ?from ?d) (adj ?from ?to ?d))
    :effect (and (at-player ?from) (not (at-player ?p)) (clear ?p)
                 (at ?b ?to) (not (at ?b ?from))
                 (not (clear ?to)) (not (clear ?from)))))
"""


@dataclass(frozen=True)
class BlockSpec:
    seed: int
    flavour: str                                  # sokoban | abstract
    detail: Dict[str, Any]

    def json(self) -> Dict[str, Any]:
        return {"seed": self.seed, "flavour": self.flavour, "detail": self.detail}


@dataclass
class BlockWorld(World):
    spec: BlockSpec
    domain_text: str
    problem_text: str

    family = "blockworld"

    @property
    def seed(self) -> int:
        return self.spec.seed

    def spec_json(self) -> Dict[str, Any]:
        return self.spec.json()

    @property
    def flavour(self) -> str:
        return self.spec.flavour


# ------------------------------------------------------------------- sokoban

def _cell_name(cell: Cell) -> str:
    return "c_%d_%d" % cell


def _sokoban_problem(name: str, grid: Sequence[str], player: Cell,
                     boxes: Sequence[Tuple[str, Cell]],
                     goals: Sequence[Tuple[str, Cell]]) -> str:
    floors = sorted(
        (r, c)
        for r, row in enumerate(grid)
        for c, char in enumerate(row)
        if char == FLOOR
    )
    occupied = {player: "player"}
    for box, cell in boxes:
        occupied[cell] = box

    adjacency = []
    for cell in floors:
        for direction in DIRECTIONS:
            dr, dc = DELTA[direction]
            target = (cell[0] + dr, cell[1] + dc)
            if target in floors:
                adjacency.append(
                    "    (adj %s %s %s)"
                    % (_cell_name(cell), _cell_name(target), direction)
                )

    init = ["    (at-player %s)" % _cell_name(player)]
    init += ["    (at %s %s)" % (b, _cell_name(c)) for b, c in sorted(boxes)]
    init += [
        "    (clear %s)" % _cell_name(cell)
        for cell in floors if cell not in occupied
    ]
    goal = " ".join(
        "(at %s %s)" % (b, _cell_name(c)) for b, c in sorted(goals)
    )
    picture = "\n".join(";;   " + row for row in grid)

    return (
        ";; fuzzlab sokoban %s\n;;\n%s\n;;\n"
        "(define (problem %s)\n"
        "  (:domain sokoban)\n"
        "  (:objects\n"
        "    %s - cell\n"
        "    %s - box\n"
        "    %s - dir)\n"
        "  (:init\n%s)\n"
        "  (:goal (and %s)))\n"
        % (
            name, picture, name,
            " ".join(_cell_name(c) for c in floors),
            " ".join(b for b, _ in sorted(boxes)),
            " ".join(DIRECTIONS),
            "\n".join(sorted(init) + sorted(adjacency)),
            goal,
        )
    )


def _generate_sokoban(rng: Rng, seed: int) -> BlockWorld:
    height = rng.between(3, 5)
    width = rng.between(3, 5)

    # A ring of wall around a randomly holed interior.
    interior = [
        (r, c) for r in range(1, height + 1) for c in range(1, width + 1)
    ]
    wall_count = rng.between(0, max(0, len(interior) // 3))
    walls = set(rng.sample(interior, wall_count))
    floors = [cell for cell in interior if cell not in walls]

    n_boxes = rng.between(1, 2)
    if len(floors) < n_boxes + 1:
        walls = set()
        floors = list(interior)
    n_boxes = min(n_boxes, max(1, len(floors) - 1))

    picks = rng.sample(floors, n_boxes + 1)
    player = picks[0]
    box_cells = picks[1:]
    boxes = tuple(("b%d" % i, cell) for i, cell in enumerate(box_cells))
    goal_cells = rng.sample(floors, n_boxes)
    goals = tuple(("b%d" % i, cell) for i, cell in enumerate(goal_cells))

    grid = []
    for r in range(height + 2):
        row = ""
        for c in range(width + 2):
            row += FLOOR if (r, c) in floors else WALL
        grid.append(row)

    name = "fuzz-sokoban-%016x" % seed
    spec = BlockSpec(
        seed=seed, flavour="sokoban",
        detail={
            "height": height + 2,
            "width": width + 2,
            "grid": grid,
            "player": list(player),
            "boxes": [[b, list(c)] for b, c in boxes],
            "goals": [[b, list(c)] for b, c in goals],
            "n_floors": len(floors),
        },
    )
    return BlockWorld(
        spec=spec,
        domain_text=SOKOBAN_DOMAIN,
        problem_text=_sokoban_problem(name, grid, player, boxes, goals),
    )


# ------------------------------------------------------------------ abstract

def _generate_abstract(rng: Rng, seed: int) -> BlockWorld:
    n_objects = rng.between(2, 3)
    objects = ["o%d" % i for i in range(n_objects)]

    n_preds = rng.between(2, 3)
    predicates = [("p%d" % i, rng.between(1, 2)) for i in range(n_preds)]

    def ground_atoms() -> List[Tuple[str, ...]]:
        out = []
        for name, arity in predicates:
            if arity == 1:
                out += [(name, o) for o in objects]
            else:
                out += [(name, a, b) for a in objects for b in objects]
        return out

    def schema_atoms(params: Sequence[str]) -> List[Tuple[str, ...]]:
        out = []
        for name, arity in predicates:
            if arity == 1:
                out += [(name, p) for p in params]
            else:
                out += [(name, a, b) for a in params for b in params]
        return out

    n_actions = rng.between(2, 3)
    actions = []
    for index in range(n_actions):
        n_params = rng.between(1, 2)
        params = ["?x%d" % i for i in range(n_params)]
        vocabulary = schema_atoms(params)
        pre_pos = rng.subset(vocabulary, 0, 2)
        rest = [a for a in vocabulary if a not in pre_pos]
        pre_neg = rng.subset(rest, 0, 1)
        adds = rng.subset(vocabulary, 1, 2)
        deletes = rng.subset(
            [a for a in vocabulary if a not in adds], 0, 2
        )
        actions.append(
            {
                "name": "a%d" % index,
                "params": params,
                "pre_pos": pre_pos,
                "pre_neg": pre_neg,
                "add": adds,
                "del": deletes,
            }
        )

    atoms = ground_atoms()
    init = rng.subset(atoms, 0, max(1, len(atoms) // 2))
    goal_pos = rng.subset(atoms, 1, 2)
    goal_neg = rng.subset([a for a in atoms if a not in goal_pos], 0, 1)

    def render(atom: Sequence[str]) -> str:
        return "(%s)" % " ".join(atom)

    predicate_decls = "\n".join(
        "    (%s %s)" % (
            name,
            " ".join("?a%d - obj" % i for i in range(arity)),
        )
        for name, arity in predicates
    )
    action_texts = []
    for action in actions:
        pre_parts = [render(a) for a in action["pre_pos"]]
        pre_parts += ["(not %s)" % render(a) for a in action["pre_neg"]]
        eff_parts = [render(a) for a in action["add"]]
        eff_parts += ["(not %s)" % render(a) for a in action["del"]]
        action_texts.append(
            "  (:action %s\n"
            "    :parameters (%s)\n"
            "    :precondition (and %s)\n"
            "    :effect (and %s))"
            % (
                action["name"],
                " ".join("%s - obj" % p for p in action["params"]),
                " ".join(pre_parts) or "",
                " ".join(eff_parts),
            )
        )

    domain_name = "fuzz-abstract"
    domain_text = (
        ";; fuzzlab abstract STRIPS domain, seed %016x\n"
        "(define (domain %s)\n"
        "  (:requirements :strips :typing)\n"
        "  (:types obj)\n"
        "  (:predicates\n%s)\n\n%s)\n"
        % (seed, domain_name, predicate_decls, "\n\n".join(action_texts))
    )

    goal_parts = [render(a) for a in goal_pos]
    goal_parts += ["(not %s)" % render(a) for a in goal_neg]
    problem_name = "fuzz-abstract-%016x" % seed
    problem_text = (
        "(define (problem %s)\n"
        "  (:domain %s)\n"
        "  (:objects %s - obj)\n"
        "  (:init %s)\n"
        "  (:goal (and %s)))\n"
        % (
            problem_name, domain_name, " ".join(objects),
            " ".join(render(a) for a in init) or "",
            " ".join(goal_parts),
        )
    )

    spec = BlockSpec(
        seed=seed, flavour="abstract",
        detail={
            "objects": objects,
            "predicates": [[n, a] for n, a in predicates],
            "actions": [
                {
                    "name": a["name"],
                    "params": a["params"],
                    "pre_pos": [list(x) for x in a["pre_pos"]],
                    "pre_neg": [list(x) for x in a["pre_neg"]],
                    "add": [list(x) for x in a["add"]],
                    "del": [list(x) for x in a["del"]],
                }
                for a in actions
            ],
            "init": [list(a) for a in init],
            "goal_pos": [list(a) for a in goal_pos],
            "goal_neg": [list(a) for a in goal_neg],
        },
    )
    return BlockWorld(spec=spec, domain_text=domain_text, problem_text=problem_text)


# ------------------------------------------------------------------ generator

def generate(seed: int) -> BlockWorld:
    """A STRIPS instance, a pure function of `seed`."""
    rng = Rng(seed)
    if rng.chance(1, 2):
        return _generate_sokoban(rng, seed)
    return _generate_abstract(rng, seed)
