#!/usr/bin/env python3
"""Merge the per-line BibTeX fragments into one library.

    cd papers/related-work && python merge_bib.py

Reads `lines/*.bib`, writes `references.bib`. Deterministic: entries are sorted
by citekey, fields are emitted in a fixed order, and running it twice produces
an identical file. No network, no model call.

It is a merger, not a formatter: field *values* are passed through verbatim, so
what a line agent verified is what lands in the library. What it does enforce:

  * no duplicate citekey across fragments (same key, different content -> error;
    same key, byte-identical content -> deduplicated, since two lines may
    legitimately want the same paper);
  * every entry has an author/title/year (a `@misc` may omit year only if it
    carries a `note` saying why);
  * the fragment a key came from is recorded, so `AUDIT.md` can sample by line.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LINES = HERE / "lines"
OUT = HERE / "references.bib"

ENTRY_RE = re.compile(r"^@(\w+)\s*\{\s*([^,\s]+)\s*,", re.MULTILINE)

FIELD_ORDER = [
    "author", "title", "booktitle", "journal", "editor", "volume", "number",
    "series", "pages", "publisher", "address", "school", "institution",
    "howpublished", "year", "month", "eprint", "archiveprefix", "primaryclass",
    "doi", "url", "urldate", "note",
]


def split_entries(text: str, source: str):
    """Yield (kind, key, raw_block, source) for each @entry in a fragment."""
    starts = [(m.start(), m.group(1).lower(), m.group(2)) for m in ENTRY_RE.finditer(text)]
    for i, (pos, kind, key) in enumerate(starts):
        end = starts[i + 1][0] if i + 1 < len(starts) else len(text)
        block = text[pos:end].rstrip()
        # trim any trailing comment lines that belong to the next entry
        while block and not block.rstrip().endswith("}"):
            block = block[: block.rfind("\n")] if "\n" in block else block
        yield kind, key, block.strip(), source


def fields_of(block: str) -> dict[str, str]:
    """Crude field scrape, enough for the presence checks below."""
    out = {}
    for m in re.finditer(r"(?m)^\s*(\w+)\s*=\s*", block):
        out[m.group(1).lower()] = ""
    return out


def main() -> int:
    if not LINES.is_dir():
        print(f"no fragments: {LINES} does not exist", file=sys.stderr)
        return 1

    seen: dict[str, tuple[str, str, str]] = {}   # key -> (kind, block, source)
    problems: list[str] = []
    per_source: dict[str, int] = {}

    for frag in sorted(LINES.glob("*.bib")):
        raw = frag.read_text(encoding="utf-8")
        n = 0
        for kind, key, block, source in split_entries(raw, frag.name):
            n += 1
            if key in seen:
                prev_kind, prev_block, prev_source = seen[key]
                if _norm(prev_block) == _norm(block):
                    continue                     # same paper, two lines wanted it
                problems.append(
                    f"duplicate citekey {key!r} with differing content: "
                    f"{prev_source} vs {source}"
                )
                continue
            f = fields_of(block)
            for required in ("author", "title"):
                if required not in f:
                    problems.append(f"{source}: {key} has no {required}")
            if "year" not in f and "note" not in f:
                problems.append(f"{source}: {key} has neither year nor an explanatory note")
            seen[key] = (kind, block, source)
        per_source[frag.name] = n

    if problems:
        for p in problems:
            print(f"PROBLEM: {p}", file=sys.stderr)
        print(f"{len(problems)} problem(s); references.bib not written", file=sys.stderr)
        return 1

    header = [
        "% references.bib -- generated by papers/related-work/merge_bib.py",
        "% DO NOT HAND-EDIT. Edit the per-line fragment in lines/ and re-run.",
        "%",
        "% Every entry here was cross-verified against two independent sources;",
        "% the two sources are named per entry in the line file that owns it.",
        "% Entries that failed cross-verification are in UNVERIFIED.md and are",
        "% deliberately NOT in this file.",
        "%",
        "% fragments merged:",
    ]
    for name in sorted(per_source):
        header.append(f"%   {name}: {per_source[name]} entr{'y' if per_source[name] == 1 else 'ies'}")
    header.append(f"% total after dedup: {len(seen)}")
    header.append("")

    body = []
    for key in sorted(seen, key=str.lower):
        kind, block, source = seen[key]
        body.append(f"% [{source}]")
        body.append(block)
        body.append("")

    OUT.write_text("\n".join(header + body), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(HERE.parent.parent)}: {len(seen)} entries "
          f"from {len(per_source)} fragment(s)")
    for name in sorted(per_source):
        print(f"  {name}: {per_source[name]}")
    return 0


def _norm(block: str) -> str:
    return re.sub(r"\s+", " ", block).strip()


if __name__ == "__main__":
    raise SystemExit(main())
