;; Sokoban level rnd0021. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #...##
;;   #..#.#
;;   #....#
;;   #....#
;;   ######
;;
;; player c34; boxes b1@c42, b2@c12; goals b1@c41, b2@c11
(define (problem sokoban-rnd0021)
  (:domain sokoban)
  (:objects
    c11 c12 c13 c21 c22 c24 c31 c32 c33 c34 c41 c42 c43 c44 - cell
    b1 b2 - box
    down left right up - dir)
  (:init
    (at b1 c41)
    (at b2 c12)
    (at-player c31)
    (clear c11)
    (clear c13)
    (clear c21)
    (clear c22)
    (clear c24)
    (clear c32)
    (clear c33)
    (clear c34)
    (clear c42)
    (clear c43)
    (clear c44)
    (adj c11 c12 right)
    (adj c11 c21 down)
    (adj c12 c11 left)
    (adj c12 c13 right)
    (adj c12 c22 down)
    (adj c13 c12 left)
    (adj c21 c11 up)
    (adj c21 c22 right)
    (adj c21 c31 down)
    (adj c22 c12 up)
    (adj c22 c21 left)
    (adj c22 c32 down)
    (adj c24 c34 down)
    (adj c31 c21 up)
    (adj c31 c32 right)
    (adj c31 c41 down)
    (adj c32 c22 up)
    (adj c32 c31 left)
    (adj c32 c33 right)
    (adj c32 c42 down)
    (adj c33 c32 left)
    (adj c33 c34 right)
    (adj c33 c43 down)
    (adj c34 c24 up)
    (adj c34 c33 left)
    (adj c34 c44 down)
    (adj c41 c31 up)
    (adj c41 c42 right)
    (adj c42 c32 up)
    (adj c42 c41 left)
    (adj c42 c43 right)
    (adj c43 c33 up)
    (adj c43 c42 left)
    (adj c43 c44 right)
    (adj c44 c34 up)
    (adj c44 c43 left))
  (:goal (and (at b1 c41) (at b2 c11))))
