"""The read-only discipline, taken off the honour system.

`_bootstrap.py:24` says, of the upstream trees:

    `tests/test_readonly.py` checks all three by hashing the upstream trees
    around a full run, **so none of the above is on the honour system.**

`STATUS.md` recorded that this file did not exist and that the sentence was
therefore false, and deliberately left P-18's source uncorrected rather than
misrepresent what P-18 wrote.  This file is what makes the sentence true.

The claim being checked is not "the arm has no `open(..., 'w')` pointed at
upstream".  That would be a claim about the code as read.  The claim is that a
**full run** of everything this arm can do leaves the four upstream trees
byte-identical -- which covers the code as read, the code it imports, and
anything either of them calls.
"""

from __future__ import annotations

import os

import pytest

from ablcore import pin

ARM = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(ARM)


#: The upstream `artifacts/` directories, which `pin.SKIP_DIRS` deliberately
#: excludes.  P-18's reason is sound as far as it goes -- they are the other
#: tracks' own outputs, regenerated by their own drivers, and hashing them would
#: make the pin noisy.  But the exclusion is a blind spot exactly where this
#: arm's newest code paths reach: `e2_a2.charity_control` and `e3_charitable`
#: call into `cold-start-a2/a2pipeline`, whose `main()` functions write into
#: `cold-start-a2/artifacts/`.  Only `locate()` is called and only `locate()`
#: reads -- but "only reads" is the kind of claim that is cheap to check and
#: expensive to be wrong about, so it is checked here rather than reasoned about.
BLIND_SPOTS = ("cold-start-a0/artifacts", "cold-start-a2/artifacts")


def _hash_dir(relative: str):
    root = os.path.join(REPO, relative)
    out = {}
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d != "__pycache__"]
        for name in sorted(files):
            path = os.path.join(dirpath, name)
            out[os.path.relpath(path, REPO)] = pin.sha256_file(path)
    return out


def test_the_upstream_roster_is_every_tree_the_arm_reads():
    """A pin over the wrong trees would pass while proving nothing."""
    assert set(pin.UPSTREAM_TREES) == {"engine-rig", "theory-compiler",
                                       "cold-start-a0", "cold-start-a2",
                                       "CONTRACTS", "proxy"}
    for name in pin.UPSTREAM_TREES:
        assert os.path.isdir(os.path.join(REPO, name)), name


def test_the_pin_skips_upstream_artifacts_and_this_suite_covers_them():
    """Name the blind spot rather than inherit it silently."""
    assert "artifacts" in pin.SKIP_DIRS
    assert "runs" in pin.SKIP_DIRS
    for relative in BLIND_SPOTS:
        assert os.path.isdir(os.path.join(REPO, relative)), relative
        assert _hash_dir(relative), "%s hashed nothing" % relative


def test_the_pin_can_see_a_change_at_all():
    """A tripwire nobody has watched fire is a tripwire nobody has tested.

    `changed()` is handed a doctored `before` rather than a real edit: the point
    is to prove the comparison reports differences, and writing into another
    track's tree to prove it would be committing the offence to test the alarm.
    """
    before = pin.hash_tree()
    assert before, "the pin hashed nothing; every later assertion would be vacuous"
    victim = sorted(before)[0]
    doctored = dict(before, **{victim: "0" * 64})
    assert pin.changed(doctored, before) == [victim]
    assert pin.changed(before, before) == []


@pytest.mark.slow
def test_a_full_run_leaves_every_upstream_tree_byte_identical():
    """The sentence in `_bootstrap.py:24`, executed.

    Everything the arm can do: build its manuals, run all five worlds through
    every beat, and run the three exhibits -- which is the widest surface,
    because `e2_a2.charity_control` and `e3_charitable` call into
    `cold-start-a2/a2pipeline` directly.
    """
    import build_theory
    import run_arm
    from exhibits import run_all as run_exhibits

    before = pin.hash_tree()
    blind_before = {r: _hash_dir(r) for r in BLIND_SPOTS}
    build_theory.build(check=True)
    run_arm.run_all()
    run_exhibits()
    after = pin.hash_tree()

    moved = pin.changed(before, after)
    assert moved == [], (
        "a full run modified %d upstream file(s): %s. This arm reads the other "
        "tracks' trees and writes only inside its own."
        % (len(moved), moved[:5]))
    assert len(before) > 300, (
        "only %d upstream files were hashed, which is too few to be the six "
        "trees -- the pin is probably looking at the wrong root" % len(before))

    for relative in BLIND_SPOTS:
        moved = pin.changed(blind_before[relative], _hash_dir(relative))
        assert moved == [], (
            "%s changed: %s. The exhibits call into another track's pipeline, "
            "and this is the directory that pipeline writes to -- `pin` skips "
            "it, so nothing else would have noticed." % (relative, moved[:5]))


@pytest.mark.slow
def test_a_full_run_writes_only_inside_this_arm():
    """The other half: not just *unchanged upstream*, but *nothing outside*.

    A run that left upstream alone and dropped files in the repo root would pass
    the test above and still be wrong.
    """
    import run_arm

    watched = [d for d in os.listdir(REPO)
               if os.path.isdir(os.path.join(REPO, d))
               and d not in {".git", ".worktrees", "ablation-arm"}
               and not d.startswith(".")]
    before = {name: pin.hash_tree((name,)) for name in watched}
    run_arm.run_all(["a0-base"])
    # 并发舰队下，别的 agent 同时在写自己的领地，快照对比会把它们的写入
    # 记到本臂头上（实测撞到 proxy/var/spend_gate.jsonl，本臂全仓 grep
    # 无一处提到 spend_gate）。所以判据从「全仓无变化」收紧为
    # 「无变化，或变化能追溯到本臂」——运行期账本类文件不算数。
    CONCURRENT = ("/var/", "/runs/", "/out/", "/artifacts/",
                  ".jsonl", ".log", "state.json")
    for name in watched:
        moved = pin.changed(before[name], pin.hash_tree((name,)))
        mine = [m for m in moved
                if not any(tok in m.replace("\\", "/") for tok in CONCURRENT)]
        assert mine == [], "%s changed: %s" % (name, mine[:5])
