"""The read-only discipline, taken off the honour system.

`_bootstrap.py:24` says, of the upstream trees:

    `tests/test_readonly.py` checks all three by hashing the upstream trees
    around a full run, **so none of the above is on the honour system.**

`STATUS.md` recorded that this file did not exist and that the sentence was
therefore false, and deliberately left P-18's source uncorrected rather than
misrepresent what P-18 wrote.  This file is what makes the sentence true.

The claim being checked is not "the arm has no `open(..., 'w')` pointed at
upstream".  That would be a claim about the code as read.  The claim is that a
**full run** of everything this arm can do leaves the four upstream trees
byte-identical -- which covers the code as read, the code it imports, and
anything either of them calls.
"""

from __future__ import annotations

import os

import pytest

from ablcore import outside, pin

ARM = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(ARM)


#: The upstream `artifacts/` directories, which `pin.SKIP_DIRS` deliberately
#: excludes.  P-18's reason is sound as far as it goes -- they are the other
#: tracks' own outputs, regenerated by their own drivers, and hashing them would
#: make the pin noisy.  But the exclusion is a blind spot exactly where this
#: arm's newest code paths reach: `e2_a2.charity_control` and `e3_charitable`
#: call into `cold-start-a2/a2pipeline`, whose `main()` functions write into
#: `cold-start-a2/artifacts/`.  Only `locate()` is called and only `locate()`
#: reads -- but "only reads" is the kind of claim that is cheap to check and
#: expensive to be wrong about, so it is checked here rather than reasoned about.
BLIND_SPOTS = ("cold-start-a0/artifacts", "cold-start-a2/artifacts")


def _hash_dir(relative: str):
    root = os.path.join(REPO, relative)
    out = {}
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d != "__pycache__"]
        for name in sorted(files):
            path = os.path.join(dirpath, name)
            out[os.path.relpath(path, REPO)] = pin.sha256_file(path)
    return out


def test_the_upstream_roster_is_every_tree_the_arm_reads():
    """A pin over the wrong trees would pass while proving nothing."""
    assert set(pin.UPSTREAM_TREES) == {"engine-rig", "theory-compiler",
                                       "cold-start-a0", "cold-start-a2",
                                       "CONTRACTS", "proxy"}
    for name in pin.UPSTREAM_TREES:
        assert os.path.isdir(os.path.join(REPO, name)), name


def test_the_pin_skips_upstream_artifacts_and_this_suite_covers_them():
    """Name the blind spot rather than inherit it silently."""
    assert "artifacts" in pin.SKIP_DIRS
    assert "runs" in pin.SKIP_DIRS
    for relative in BLIND_SPOTS:
        assert os.path.isdir(os.path.join(REPO, relative)), relative
        assert _hash_dir(relative), "%s hashed nothing" % relative


def test_the_pin_can_see_a_change_at_all():
    """A tripwire nobody has watched fire is a tripwire nobody has tested.

    `changed()` is handed a doctored `before` rather than a real edit: the point
    is to prove the comparison reports differences, and writing into another
    track's tree to prove it would be committing the offence to test the alarm.
    """
    before = pin.hash_tree()
    assert before, "the pin hashed nothing; every later assertion would be vacuous"
    victim = sorted(before)[0]
    doctored = dict(before, **{victim: "0" * 64})
    assert pin.changed(doctored, before) == [victim]
    assert pin.changed(before, before) == []


@pytest.mark.slow
def test_a_full_run_leaves_every_upstream_tree_byte_identical():
    """The sentence in `_bootstrap.py:24`, executed.

    Everything the arm can do: build its manuals, run all five worlds through
    every beat, and run the three exhibits -- which is the widest surface,
    because `e2_a2.charity_control` and `e3_charitable` call into
    `cold-start-a2/a2pipeline` directly.
    """
    import build_theory
    import run_arm
    from exhibits import run_all as run_exhibits

    before = pin.hash_tree()
    blind_before = {r: _hash_dir(r) for r in BLIND_SPOTS}
    build_theory.build(check=True)
    run_arm.run_all()
    run_exhibits()
    after = pin.hash_tree()

    moved = pin.changed(before, after)
    assert moved == [], (
        "a full run modified %d upstream file(s): %s. This arm reads the other "
        "tracks' trees and writes only inside its own."
        % (len(moved), moved[:5]))
    assert len(before) > 300, (
        "only %d upstream files were hashed, which is too few to be the six "
        "trees -- the pin is probably looking at the wrong root" % len(before))

    for relative in BLIND_SPOTS:
        moved = pin.changed(blind_before[relative], _hash_dir(relative))
        assert moved == [], (
            "%s changed: %s. The exhibits call into another track's pipeline, "
            "and this is the directory that pipeline writes to -- `pin` skips "
            "it, so nothing else would have noticed." % (relative, moved[:5]))


# --------------------------------------------------------------------------
# "nothing outside this arm moved", rebuilt on an empty-run control.
#
# The previous version of this section subtracted concurrent-fleet noise with a
# tuple of path shapes and was falsified by
# `monitor/audit/DRIFT-20260728T1501Z-the-tightened-criterion-hides-the-worst-writes.md`
# (high): the shapes it excluded were exactly the shared ledgers.  `ablcore/outside.py`
# carries the replacement and the full reasoning; these tests are its callers.
# --------------------------------------------------------------------------


def _run_a0_base():
    import run_arm
    run_arm.run_all(["a0-base"])


@pytest.mark.slow
def test_a_full_run_writes_only_inside_this_arm():
    """The other half: not just *unchanged upstream*, but *nothing outside*.

    A run that left upstream alone and dropped files in the repo root would pass
    the test above and still be wrong.

    Concurrent sessions write their own territories while this runs, so the
    comparison is against an **empty-run control** taken in the same wall-clock
    neighbourhood: only paths that moved during the run and *not* during the
    idle window count, plus `outside.HARD_LIST`, which is never subtracted.
    """
    obs = outside.observe(_run_a0_base)

    assert obs.files_watched > 1000, (
        "only %d files outside the arm were hashed, which is too few to be the "
        "repo -- the snapshot is probably looking at the wrong root"
        % obs.files_watched)
    assert obs.aligned, (
        "the empty-run control was exposed for %.2fs but the run for %.2fs; a "
        "control shorter than the thing it controls does not subtract the "
        "noise it is meant to subtract"
        % (obs.idle_seconds + obs.makeup_seconds, obs.run_seconds))
    assert obs.reported == [], obs.message()


@pytest.mark.slow
def test_a_stray_byte_outside_the_arm_turns_this_check_red():
    """The negative control the audit asked for, and the proof it is not a no-op.

    Suggestion (3) verbatim: *write one byte under `proxy/var/` and assert the
    check must go red*.  Without it, nobody can show the alarm still fires after
    the rewrite.

    The second half is the V12/V16 requirement: the same observed set is run
    through `outside.superseded_criterion` -- the exact tuple this ticket
    replaced -- and the byte is shown to be **let through** there.  A negative
    control that is also red against the old code is not a control for this
    change.

    The victim path is chosen to look maximally like innocent noise: it is under
    `proxy/var/` and ends in `.jsonl`, so it trips two of the old exclusion
    tokens at once.  It is deliberately *not* `spend_gate.jsonl` -- corrupting a
    real ledger to test the alarm is committing the offence to prove it is
    detectable -- and deliberately *not* on the hard list either, so what is
    being demonstrated is the empty-run control firing on its own merits.
    """
    victim_rel = "proxy/var/a9-negative-control-%d.jsonl" % os.getpid()
    victim = os.path.join(REPO, victim_rel.replace("/", os.sep))
    var_dir = os.path.dirname(victim)
    made_dir = not os.path.isdir(var_dir)

    assert not outside.is_hard(victim_rel), (
        "the victim is on the hard list, so this would prove the hard list "
        "fires and say nothing about the empty-run control")

    def run_then_trespass():
        _run_a0_base()
        os.makedirs(var_dir, exist_ok=True)
        with open(victim, "wb") as handle:
            handle.write(b"x")

    try:
        obs = outside.observe(run_then_trespass)
    finally:
        if os.path.exists(victim):
            os.remove(victim)
        if made_dir and os.path.isdir(var_dir) and not os.listdir(var_dir):
            os.rmdir(var_dir)
    assert not os.path.exists(victim), "the negative control left its own litter"

    assert victim_rel in obs.reported, (
        "one byte written outside this arm did not turn the check red. "
        "observed=%s reported=%s" % (obs.observed[:5], obs.reported[:5]))

    let_through = outside.superseded_criterion(obs.observed)
    assert victim_rel not in let_through, (
        "the superseded criterion also reports this byte, so this negative "
        "control does not test the A9 change -- pick a victim the old path-shape "
        "table actually excluded")


@pytest.mark.slow
def test_a_mutated_existing_file_outside_the_arm_turns_this_check_red():
    """The harder half of the negative control: modification, not creation.

    The test above writes a *new* file, which is a pure addition to the
    snapshot -- and an addition is the easy case, caught by any criterion that
    diffs key sets at all.  The write this arm would realistically commit is an
    *append* to a file that already exists (that is what the false positive that
    started all this was: a concurrent session appending to a ledger).

    So the victim is created before the first snapshot, is therefore present and
    unchanged in the empty-run leg, and is appended to during the run leg.  Its
    key is in `before` and in `after`; only its content moves.  It stays this
    arm's own litter -- no file belonging to another territory is touched to
    test the alarm.
    """
    victim_rel = "proxy/var/a9-mutation-control-%d.jsonl" % os.getpid()
    victim = os.path.join(REPO, victim_rel.replace("/", os.sep))
    var_dir = os.path.dirname(victim)
    made_dir = not os.path.isdir(var_dir)

    try:
        os.makedirs(var_dir, exist_ok=True)
        with open(victim, "wb") as handle:
            handle.write(b"seed\n")

        def run_then_append():
            _run_a0_base()
            with open(victim, "ab") as handle:
                handle.write(b"x")

        obs = outside.observe(run_then_append)
    finally:
        if os.path.exists(victim):
            os.remove(victim)
        if made_dir and os.path.isdir(var_dir) and not os.listdir(var_dir):
            os.rmdir(var_dir)
    assert not os.path.exists(victim), "the mutation control left its own litter"

    assert victim_rel not in obs.background, (
        "the victim moved during the empty-run leg too, so this proves nothing "
        "about the run leg")
    assert victim_rel in obs.observed, "the appended byte was not even observed"
    assert victim_rel in obs.reported, (
        "one byte appended to an existing file outside this arm did not turn "
        "the check red. reported=%s" % obs.reported[:5])
    assert victim_rel not in outside.superseded_criterion(obs.observed), (
        "the superseded criterion also reports this, so it is not a control "
        "for the A9 change")


def test_the_hard_list_is_reported_even_when_it_is_background_noise():
    """The control's one structural hole, closed by hand.

    If another session writes a file during *both* legs it lands in the
    background set and is subtracted.  For most files that is right.  For the
    shared ledgers it is not, and this pins that: a hard-list path is reported
    even when it is present in the background, while an ordinary path in the
    same position is subtracted.
    """
    hard = "proxy/var/spend_gate.jsonl"
    ordinary = "engine-rig/runs/p13-fd-real/some-scratch.txt"
    assert outside.is_hard(hard) and not outside.is_hard(ordinary)

    obs = outside.Observation(background=[hard, ordinary],
                              observed=[hard, ordinary],
                              idle_seconds=2.0, run_seconds=1.0,
                              makeup_seconds=0.0, files_watched=2000)
    assert obs.reported == [hard]
    assert obs.reported_by_hard_list == [hard]
    assert obs.subtracted == [ordinary]


def test_the_hard_list_covers_every_path_the_old_criterion_hid():
    """The audit's own table, turned into a regression lock.

    The DRIFT note listed six real paths the path-shape tuple excluded.  Each is
    asserted to be let through by the superseded criterion (so the table is a
    faithful record of the bug) and caught by the replacement.

    The two arms of this test are not redundant: the first proves the old
    criterion really was blind here, the second proves the new one is not.  A
    test that only asserted the second would pass on code that never had the
    bug.
    """
    hidden = ["proxy/var/spend_gate.jsonl",
              "arc-recon/data/contamination_log.jsonl",
              "arc-recon/data/incidents.jsonl",
              "engine-rig/artifacts/candidates.jsonl",
              "baseline-arms/ledger.jsonl",
              "monitor/state.json"]
    assert outside.superseded_criterion(hidden) == [], (
        "the audit's table says all six were excluded by the old criterion; "
        "this one was not: %s" % outside.superseded_criterion(hidden))
    missed = [p for p in hidden if not outside.is_hard(p)]
    assert missed == [], "not on the hard list: %s" % missed

    #: Every hard-list pattern must match something that exists on this tree, or
    #: the rule has never been exercised by anything real.  (The adversarial
    #: review's question (b): a hard list of paths nobody ever writes is a rule
    #: that has not been tested.)
    present = outside.snapshot()
    for pattern, _why in outside.ALL_HARD:
        if pattern == "proxy/var/spend_gate.jsonl":
            # gitignored runtime output; absent on a fresh checkout by design,
            # which is exactly why it is pinned by name rather than by presence.
            continue
        hits = [p for p in present if outside._to_regex(pattern).match(p)]
        assert hits, "no file on this tree matches hard-list pattern %r" % pattern


def test_the_glob_matcher_does_not_leak_across_directories():
    """`*` must not cross `/`, or `arc-recon/data/*.jsonl` silently widens.

    `fnmatch` would let it, and on Windows would also fold case.  A hard list
    whose reach depends on the host OS is not a hard list.
    """
    assert outside.is_hard("arc-recon/data/incidents.jsonl")
    assert not outside.is_hard("arc-recon/data/sub/incidents.jsonl")
    assert outside.is_hard("CONTRACTS/candidates_schema.md")
    assert outside.is_hard("baseline-arms/out/shards/ledger.a7-g50t.jsonl")
    assert not outside.is_hard("ablation-arm/runs/x/ledger-notes.md")
    assert not outside.is_hard("proxy/var/some_other.jsonl")


def test_the_snapshot_does_not_inherit_the_pin_s_artifacts_blind_spot():
    """`pin.SKIP_DIRS` drops `artifacts/` and `runs/`; this must not.

    Half the audit's finding was that the worst-consequence paths were excluded
    by the criterion.  The other half is that some of them were never hashed at
    all, so no criterion could have reported them.
    """
    assert "artifacts" in pin.SKIP_DIRS and "runs" in pin.SKIP_DIRS
    assert "artifacts" not in outside.SKIP_DIRS
    assert "runs" not in outside.SKIP_DIRS

    seen = outside.snapshot()
    assert any("/artifacts/" in p for p in seen), "no upstream artifacts hashed"
    assert any("/runs/" in p for p in seen), "no upstream runs/ hashed"
    assert not any(p.startswith("ablation-arm/") for p in seen), \
        "the arm's own tree is inside the watch, so its own writes read as escapes"
    assert "PARTNER_SYNC.md" in seen, (
        "top-level files are not watched; a run that appended to the shared "
        "status board would pass this suite")
