"""The read-only discipline, taken off the honour system.

`_bootstrap.py:24` says, of the upstream trees:

    `tests/test_readonly.py` checks all three by hashing the upstream trees
    around a full run, **so none of the above is on the honour system.**

`STATUS.md` recorded that this file did not exist and that the sentence was
therefore false, and deliberately left P-18's source uncorrected rather than
misrepresent what P-18 wrote.  This file is what makes the sentence true.

The claim being checked is not "the arm has no `open(..., 'w')` pointed at
upstream".  That would be a claim about the code as read.  The claim is that a
**full run** of everything this arm can do leaves the four upstream trees
byte-identical -- which covers the code as read, the code it imports, and
anything either of them calls.

The second half of the file -- "nothing moved *outside* this arm" -- was
falsified once and rebuilt.  Its criterion, its hard list and the reasons for
both live in `ablcore/outside.py`; these are its callers, plus the negative
controls that prove it still fires.  `runs/20260728T191437Z-A9-readonly-baseline/`
holds the measured evidence.

That half is checked twice over, by two mechanisms that fail for disjoint
reasons: a snapshot diff against an empty-run control (`outside.observe`), which
sees writes made by C extensions and child processes but must subtract the
concurrent fleet; and an audit hook that attributes every write to *this*
interpreter, which cannot be confused by the fleet at all but is blind to what
it cannot observe.  Neither subsumes the other, so neither was dropped.
"""

from __future__ import annotations

import json
import os
import sys

import pytest

from ablcore import outside, pin

ARM = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(ARM)


#: The upstream `artifacts/` directories, which `pin.SKIP_DIRS` deliberately
#: excludes.  P-18's reason is sound as far as it goes -- they are the other
#: tracks' own outputs, regenerated by their own drivers, and hashing them would
#: make the pin noisy.  But the exclusion is a blind spot exactly where this
#: arm's newest code paths reach: `e2_a2.charity_control` and `e3_charitable`
#: call into `cold-start-a2/a2pipeline`, whose `main()` functions write into
#: `cold-start-a2/artifacts/`.  Only `locate()` is called and only `locate()`
#: reads -- but "only reads" is the kind of claim that is cheap to check and
#: expensive to be wrong about, so it is checked here rather than reasoned about.
BLIND_SPOTS = ("cold-start-a0/artifacts", "cold-start-a2/artifacts")


def _hash_dir(relative: str):
    root = os.path.join(REPO, relative)
    out = {}
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d != "__pycache__"]
        for name in sorted(files):
            path = os.path.join(dirpath, name)
            out[os.path.relpath(path, REPO)] = pin.sha256_file(path)
    return out


def test_the_upstream_roster_is_every_tree_the_arm_reads():
    """A pin over the wrong trees would pass while proving nothing."""
    assert set(pin.UPSTREAM_TREES) == {"engine-rig", "theory-compiler",
                                       "cold-start-a0", "cold-start-a2",
                                       "CONTRACTS", "proxy"}
    for name in pin.UPSTREAM_TREES:
        assert os.path.isdir(os.path.join(REPO, name)), name


def test_the_pin_skips_upstream_artifacts_and_this_suite_covers_them():
    """Name the blind spot rather than inherit it silently."""
    assert "artifacts" in pin.SKIP_DIRS
    assert "runs" in pin.SKIP_DIRS
    for relative in BLIND_SPOTS:
        assert os.path.isdir(os.path.join(REPO, relative)), relative
        assert _hash_dir(relative), "%s hashed nothing" % relative


def test_the_pin_can_see_a_change_at_all():
    """A tripwire nobody has watched fire is a tripwire nobody has tested.

    `changed()` is handed a doctored `before` rather than a real edit: the point
    is to prove the comparison reports differences, and writing into another
    track's tree to prove it would be committing the offence to test the alarm.
    """
    before = pin.hash_tree()
    assert before, "the pin hashed nothing; every later assertion would be vacuous"
    victim = sorted(before)[0]
    doctored = dict(before, **{victim: "0" * 64})
    assert pin.changed(doctored, before) == [victim]
    assert pin.changed(before, before) == []


@pytest.mark.slow
def test_a_full_run_leaves_every_upstream_tree_byte_identical():
    """The sentence in `_bootstrap.py:24`, executed.

    Everything the arm can do: build its manuals, run all five worlds through
    every beat, and run the three exhibits -- which is the widest surface,
    because `e2_a2.charity_control` and `e3_charitable` call into
    `cold-start-a2/a2pipeline` directly.
    """
    import build_theory
    import run_arm
    from exhibits import run_all as run_exhibits

    before = pin.hash_tree()
    blind_before = {r: _hash_dir(r) for r in BLIND_SPOTS}
    build_theory.build(check=True)
    run_arm.run_all()
    run_exhibits()
    after = pin.hash_tree()

    moved = pin.changed(before, after)
    assert moved == [], (
        "a full run modified %d upstream file(s): %s. This arm reads the other "
        "tracks' trees and writes only inside its own."
        % (len(moved), moved[:5]))
    assert len(before) > 300, (
        "only %d upstream files were hashed, which is too few to be the six "
        "trees -- the pin is probably looking at the wrong root" % len(before))

    for relative in BLIND_SPOTS:
        moved = pin.changed(blind_before[relative], _hash_dir(relative))
        assert moved == [], (
            "%s changed: %s. The exhibits call into another track's pipeline, "
            "and this is the directory that pipeline writes to -- `pin` skips "
            "it, so nothing else would have noticed." % (relative, moved[:5]))


# --------------------------------------------------------------------------
# "nothing outside this arm moved", rebuilt on an empty-run control.
#
# The previous version of this section subtracted concurrent-fleet noise with a
# tuple of path shapes and was falsified by
# `monitor/audit/DRIFT-20260728T1501Z-the-tightened-criterion-hides-the-worst-writes.md`
# (high): the shapes it excluded were exactly the shared ledgers.  `ablcore/outside.py`
# carries the replacement and the full reasoning; these tests are its callers.
# --------------------------------------------------------------------------


def _run_a0_base():
    import run_arm
    run_arm.run_all(["a0-base"])


@pytest.mark.slow
def test_a_full_run_writes_only_inside_this_arm():
    """The other half: not just *unchanged upstream*, but *nothing outside*.

    A run that left upstream alone and dropped files in the repo root would pass
    the test above and still be wrong.

    Concurrent sessions write their own territories while this runs, so the
    comparison is against an **empty-run control** taken in the same wall-clock
    neighbourhood: only paths that moved during the run and *not* during the
    idle window count, plus `outside.HARD_LIST`, which is never subtracted.
    """
    obs = outside.observe(_run_a0_base)

    assert obs.files_watched > 1000, (
        "only %d files outside the arm were hashed, which is too few to be the "
        "repo -- the snapshot is probably looking at the wrong root"
        % obs.files_watched)
    assert obs.aligned, (
        "the empty-run control was exposed for %.2fs but the run for %.2fs; a "
        "control shorter than the thing it controls does not subtract the "
        "noise it is meant to subtract"
        % (obs.idle_seconds + obs.makeup_seconds, obs.run_seconds))
    assert obs.reported == [], obs.message()


#: The child that runs the arm under an audit hook and reports what *it* wrote.
#:
#: A subprocess rather than an in-process hook because `sys.addaudithook` is
#: deliberately irremovable: installing one here would leave it running for
#: every later test in the session, which is a side effect a test is not
#: entitled to have.  The child is launched with `-B` so CPython does not write
#: `__pycache__` into the upstream trees it imports -- those are the
#: interpreter's caches rather than the arm's output, and `pin.SKIP_DIRS` takes
#: the same position; `__pycache__` is filtered again below so the exclusion is
#: visible rather than implied by a flag.
_ATTRIBUTION_CHILD = r'''
import json
import os
import sys

ARM = sys.argv[1]
REPO = os.path.dirname(ARM)
for _p in (ARM, REPO):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import run_arm

_WRITE_FLAGS = (os.O_WRONLY | os.O_RDWR | os.O_CREAT | os.O_APPEND
                | os.O_TRUNC | getattr(os, "O_EXCL", 0))

#: event name -> the positional indices of its path arguments.  Every one of
#: these mutates the filesystem without ever going through `open`.
_PATH_EVENTS = {
    "os.remove": (0,), "os.unlink": (0,), "os.rmdir": (0,),
    "os.mkdir": (0,), "os.makedirs": (0,), "os.truncate": (0,),
    "os.rename": (0, 1), "os.replace": (0, 1),
    "os.link": (1,), "os.symlink": (1,),
    "shutil.copyfile": (0, 1), "shutil.copymode": (1,),
    "shutil.copystat": (1,), "shutil.copytree": (0, 1),
    "shutil.move": (0, 1), "shutil.rmtree": (0,),
}

writes = set()
spawned = []
recording = True


def _hook(event, args):
    if not recording:
        return
    if event == "subprocess.Popen":
        # A child process escapes the hook entirely, so it is reported rather
        # than silently trusted.
        spawned.append(str(args[1])[:200])
        return
    if event == "open":
        path, mode, flags = args[0], args[1], args[2]
        if path is None or isinstance(path, int):
            return              # a file descriptor, not a path
        if (isinstance(mode, str) and any(c in mode for c in "wxa+")) or (
                mode is None and isinstance(flags, int)
                and (flags & _WRITE_FLAGS)):
            # `mode is None` is the `os.open` form of the same event; its intent
            # is in the flags.
            try:
                writes.add(os.fspath(path))
            except TypeError:
                writes.add(str(path))
        return
    for index in _PATH_EVENTS.get(event, ()):
        if index < len(args) and args[index] is not None:
            try:
                writes.add(os.fspath(args[index]))
            except TypeError:
                pass


sys.addaudithook(_hook)
try:
    run_arm.run_all(["a0-base"])
finally:
    recording = False

sys.stdout.write("@@WRITESET@@" + json.dumps(
    {"writes": sorted(str(w) for w in writes), "spawned": spawned}) + "\n")
'''


def _attributed_write_set():
    """Run one world in a child and return every path *that process* wrote."""
    import subprocess
    import tempfile

    handle, script = tempfile.mkstemp(suffix="-attribution.py")
    os.close(handle)
    try:
        with open(script, "w", encoding="utf-8", newline="\n") as out:
            out.write(_ATTRIBUTION_CHILD)
        done = subprocess.run([sys.executable, "-B", script, ARM],
                              cwd=ARM, capture_output=True, text=True)
    finally:
        os.remove(script)

    assert done.returncode == 0, (
        "the attribution child failed (%d); the arm could not be run under an "
        "audit hook.\nstdout:\n%s\nstderr:\n%s"
        % (done.returncode, done.stdout[-2000:], done.stderr[-2000:]))
    marker = done.stdout.rfind("@@WRITESET@@")
    assert marker >= 0, (
        "the attribution child printed no write set.\nstdout:\n%s\nstderr:\n%s"
        % (done.stdout[-2000:], done.stderr[-2000:]))
    return json.loads(done.stdout[marker + len("@@WRITESET@@"):])


@pytest.mark.slow
def test_every_write_this_process_makes_lands_inside_this_arm():
    """The same claim by attribution rather than by snapshot, as a second leg.

    `test_a_full_run_writes_only_inside_this_arm` asks *what moved on disk* and
    subtracts an empty-run control to tell this arm's writes from the fleet's.
    This one asks the complementary question: *which paths did this interpreter
    write*.  A concurrent session's writes never pass through this process, so
    concurrency cannot produce a false positive by construction, and the two
    legs fail for disjoint reasons -- which is why both are kept rather than one
    replacing the other.

    Attribution also catches two things a snapshot diff structurally cannot:
    write-then-restore, and delete-and-recreate with identical bytes.  It is
    weaker exactly where `outside.observe` is strong: it is blind to a write
    made by a C extension that bypasses the audit events, and blind to anything
    a child process does -- which is why `spawned` is asserted empty rather than
    trusted.

    **What is checked, exactly.** No path *under this repository and outside
    `ablation-arm/`* is written or deleted.  Paths outside the repository are
    allowed and are not a loophole left open by accident: `exhibits/e2_a2.py`
    and `exhibits/e3_charitable.py` both call `tempfile.mkdtemp`, and the system
    temp directory is where a scratch directory belongs.
    """
    seen = _attributed_write_set()

    assert seen["spawned"] == [], (
        "the run spawned %d child process(es), which escape the audit hook and "
        "so are unattributed: %s. If the arm has come to legitimately need a "
        "subprocess, this assertion is the place to say so and name it."
        % (len(seen["spawned"]), seen["spawned"][:3]))

    repo = os.path.realpath(REPO) + os.sep
    arm = os.path.realpath(ARM) + os.sep
    trespass = []
    for path in seen["writes"]:
        full = os.path.realpath(os.path.join(ARM, path))
        if not (full + os.sep).startswith(repo):
            continue                        # outside the repo -- see docstring
        if (full + os.sep).startswith(arm):
            continue                        # this arm's own territory
        if "__pycache__" in full.replace(os.sep, "/").split("/"):
            continue                        # CPython's cache, not the arm's
        trespass.append(os.path.relpath(full, REPO).replace(os.sep, "/"))
    assert sorted(trespass) == [], (
        "a run wrote or deleted %d path(s) inside the repo but outside this "
        "arm: %s" % (len(trespass), sorted(trespass)[:5]))
    assert seen["writes"], (
        "the hook recorded no writes at all -- a run that writes nothing means "
        "the hook is not installed, and every assertion above is vacuous")


@pytest.mark.slow
def test_a_stray_byte_outside_the_arm_turns_this_check_red():
    """The negative control the audit asked for, and the proof it is not a no-op.

    Suggestion (3) verbatim: *write one byte under `proxy/var/` and assert the
    check must go red*.  Without it, nobody can show the alarm still fires after
    the rewrite.

    The second half is the V12/V16 requirement: the same observed set is run
    through `outside.superseded_criterion` -- the exact tuple this ticket
    replaced -- and the byte is shown to be **let through** there.  A negative
    control that is also red against the old code is not a control for this
    change.

    The victim path is chosen to look maximally like innocent noise: it ends in
    `.jsonl` and sits at the repo root, so it trips one of the old exclusion
    tokens.  It is deliberately *not* on the hard list, so what is being
    demonstrated is the empty-run control firing on its own merits.

    It is also deliberately **outside `pin.UPSTREAM_TREES`**, and that is the
    part the adversarial review forced.  The first version of this control wrote
    under `proxy/var/`, and `proxy` is an upstream tree that
    `test_a_full_run_leaves_every_upstream_tree_byte_identical` already hashes
    unconditionally -- so the byte was caught by a pre-A9 test that was never
    broken, and this one proved nothing about the change.  A top-level file is
    watched only by `outside.watched()`, which is the code under test; the
    assertion below that `pin` cannot see it is what makes the discrimination
    explicit rather than assumed.

    (Since the merge of the read-only-gate fix, `pin.SKIP_PATHS` prunes
    `proxy/var/` from the pin, so "hashes it unconditionally" no longer holds
    for that subtree.  Nothing is lost: `proxy/var/spend_gate.jsonl` and the
    proxy's ledger are on `outside.HARD_LIST`, which is never subtracted, so
    the coverage moved to the layer that can tell this arm's writes from the
    fleet's instead of being charged for both.  The victim stays at the repo
    root either way.)
    """
    victim_rel = "a9-negative-control-%d.jsonl" % os.getpid()
    victim = os.path.join(REPO, victim_rel)

    assert not outside.is_hard(victim_rel), (
        "the victim is on the hard list, so this would prove the hard list "
        "fires and say nothing about the empty-run control")
    assert victim_rel not in pin.hash_tree(), (
        "the victim is inside an upstream tree, so the pre-A9 pin test would "
        "catch it too and this control would not discriminate")

    def run_then_trespass():
        _run_a0_base()
        with open(victim, "wb") as handle:
            handle.write(b"x")

    try:
        obs = outside.observe(run_then_trespass)
        assert victim_rel not in pin.hash_tree(), (
            "the pin hashed the victim after all; this control is not "
            "discriminating between A9 and the code that predates it")
    finally:
        if os.path.exists(victim):
            os.remove(victim)
    assert not os.path.exists(victim), "the negative control left its own litter"

    assert victim_rel in obs.reported, (
        "one byte written outside this arm did not turn the check red. "
        "observed=%s reported=%s" % (obs.observed[:5], obs.reported[:5]))

    let_through = outside.superseded_criterion(obs.observed)
    assert victim_rel not in let_through, (
        "the superseded criterion also reports this byte, so this negative "
        "control does not test the A9 change -- pick a victim the old path-shape "
        "table actually excluded")


@pytest.mark.slow
def test_a_mutated_existing_file_outside_the_arm_turns_this_check_red():
    """The harder half of the negative control: modification, not creation.

    The test above writes a *new* file, which is a pure addition to the
    snapshot -- and an addition is the easy case, caught by any criterion that
    diffs key sets at all.  The write this arm would realistically commit is an
    *append* to a file that already exists (that is what the false positive that
    started all this was: a concurrent session appending to a ledger).

    So the victim is created before the first snapshot, is therefore present and
    unchanged in the empty-run leg, and is appended to during the run leg.  Its
    key is in `before` and in `after`; only its content moves.  It stays this
    arm's own litter -- no file belonging to another territory is touched to
    test the alarm.
    """
    victim_rel = "a9-mutation-control-%d.jsonl" % os.getpid()
    victim = os.path.join(REPO, victim_rel)

    try:
        with open(victim, "wb") as handle:
            handle.write(b"seed\n")
        assert victim_rel not in pin.hash_tree(), (
            "the victim is inside an upstream tree, so the pre-A9 pin test "
            "would catch it too")

        def run_then_append():
            _run_a0_base()
            with open(victim, "ab") as handle:
                handle.write(b"x")

        obs = outside.observe(run_then_append)
    finally:
        if os.path.exists(victim):
            os.remove(victim)
    assert not os.path.exists(victim), "the mutation control left its own litter"

    assert victim_rel not in obs.background, (
        "the victim moved during the empty-run leg too, so this proves nothing "
        "about the run leg")
    assert victim_rel in obs.observed, "the appended byte was not even observed"
    assert victim_rel in obs.reported, (
        "one byte appended to an existing file outside this arm did not turn "
        "the check red. reported=%s" % obs.reported[:5])
    assert victim_rel not in outside.superseded_criterion(obs.observed), (
        "the superseded criterion also reports this, so it is not a control "
        "for the A9 change")


@pytest.mark.slow
def test_the_subtraction_and_the_hard_list_against_a_real_concurrent_writer():
    """The control that was missing, and the only one that runs the subtraction.

    Everything else in this file leaves `background` empty, because a worktree
    has no concurrent fleet in it: the adversarial review measured 0 background
    paths in 75/75 idle windows here and concluded, correctly, that
    `Observation.subtracted` and `Observation.reported_by_hard_list` had never
    had a non-empty input outside a hand-built object.  A branch reached only by
    a hand-built object is a branch nobody has watched fire.

    So this test *is* the concurrent session.  A thread appends to two files for
    the whole observation -- through the idle leg and the run leg both, which is
    exactly the shape of fleet noise -- and the two files differ in one respect
    only:

    * `a9-noise-<pid>.txt` is ordinary, so the control must **subtract** it;
    * `a9-noise-<pid>/ledger.jsonl` matches the mandated `**/ledger.jsonl` rule,
      so it must be **reported anyway**.

    Same writer, same cadence, same wall clock, opposite verdicts. That is the
    hard list doing work the empty-run control would otherwise undo, executed
    rather than asserted about a dictionary literal.
    """
    import threading

    pid = os.getpid()
    ordinary_rel = "a9-noise-%d.txt" % pid
    hard_rel = "a9-noise-%d/ledger.jsonl" % pid
    ordinary = os.path.join(REPO, ordinary_rel)
    hard = os.path.join(REPO, hard_rel.replace("/", os.sep))
    hard_dir = os.path.dirname(hard)

    assert not outside.is_hard(ordinary_rel)
    assert outside.is_hard(hard_rel), (
        "%s must match the mandated **/ledger.jsonl rule or this test proves "
        "nothing about the hard list" % hard_rel)

    stop = threading.Event()

    def churn():
        n = 0
        while not stop.is_set():
            n += 1
            for path in (ordinary, hard):
                try:
                    with open(path, "ab") as handle:
                        handle.write(b"%d\n" % n)
                except OSError:
                    pass
            stop.wait(0.05)

    writer = threading.Thread(target=churn, daemon=True)
    try:
        os.makedirs(hard_dir, exist_ok=True)
        for path in (ordinary, hard):
            with open(path, "wb") as handle:
                handle.write(b"seed\n")
        writer.start()
        obs = outside.observe(_run_a0_base)
    finally:
        stop.set()
        writer.join(timeout=10)
        for path in (ordinary, hard):
            if os.path.exists(path):
                os.remove(path)
        if os.path.isdir(hard_dir) and not os.listdir(hard_dir):
            os.rmdir(hard_dir)
    assert not os.path.exists(ordinary) and not os.path.isdir(hard_dir), \
        "the concurrent-writer control left its own litter"

    # The premise: both files really did move during both legs.
    assert ordinary_rel in obs.background and hard_rel in obs.background, (
        "the writer did not reach the idle leg, so nothing below is a test of "
        "the subtraction. background=%s" % obs.background[:5])
    assert ordinary_rel in obs.observed and hard_rel in obs.observed

    # The subtraction, executed on real data for the first time.
    assert ordinary_rel in obs.subtracted, obs.message()
    assert ordinary_rel not in obs.reported, (
        "an ordinary path that moved during the empty run was still reported, "
        "so the control subtracted nothing: %s" % obs.message())

    # The hard list, overriding it on the same data.
    assert hard_rel in obs.reported, (
        "a hard-listed path was subtracted as background noise -- this is the "
        "one thing the hard list exists to prevent: %s" % obs.message())
    assert hard_rel in obs.reported_by_hard_list
    assert hard_rel not in obs.subtracted


def test_the_hard_list_is_reported_even_when_it_is_background_noise():
    """The control's one structural hole, closed by hand.

    If another session writes a file during *both* legs it lands in the
    background set and is subtracted.  For most files that is right.  For the
    shared ledgers it is not, and this pins that: a hard-list path is reported
    even when it is present in the background, while an ordinary path in the
    same position is subtracted.
    """
    hard = "proxy/var/spend_gate.jsonl"
    ordinary = "engine-rig/runs/p13-fd-real/some-scratch.txt"
    assert outside.is_hard(hard) and not outside.is_hard(ordinary)

    obs = outside.Observation(background=[hard, ordinary],
                              observed=[hard, ordinary],
                              idle_seconds=2.0, run_seconds=1.0,
                              makeup_seconds=0.0, files_watched=2000)
    assert obs.reported == [hard]
    assert obs.reported_by_hard_list == [hard]
    assert obs.subtracted == [ordinary]


def test_the_hard_list_covers_every_path_the_old_criterion_hid():
    """The audit's own table, turned into a regression lock.

    The DRIFT note listed six real paths the path-shape tuple excluded.  Each is
    asserted to be let through by the superseded criterion (so the table is a
    faithful record of the bug) and caught by the replacement.

    The two arms of this test are not redundant: the first proves the old
    criterion really was blind here, the second proves the new one is not.  A
    test that only asserted the second would pass on code that never had the
    bug.
    """
    hidden = ["proxy/var/spend_gate.jsonl",
              "arc-recon/data/contamination_log.jsonl",
              "arc-recon/data/incidents.jsonl",
              "engine-rig/artifacts/candidates.jsonl",
              "baseline-arms/ledger.jsonl",
              "monitor/state.json"]
    assert outside.superseded_criterion(hidden) == [], (
        "the audit's table says all six were excluded by the old criterion; "
        "this one was not: %s" % outside.superseded_criterion(hidden))
    missed = [p for p in hidden if not outside.is_hard(p)]
    assert missed == [], "not on the hard list: %s" % missed

    #: Every hard-list pattern must match something that exists on this tree, or
    #: the rule has never been exercised by anything real.  (The adversarial
    #: review's question (b): a hard list of paths nobody ever writes is a rule
    #: that has not been tested.)
    present = outside.snapshot()
    for pattern, _why in outside.ALL_HARD:
        if pattern == "proxy/var/spend_gate.jsonl":
            # Gitignored runtime output: absent on a fresh checkout by design,
            # which is exactly why it is pinned by name rather than by presence.
            # The skip is not a hole -- a typo in this pattern still fails the
            # `missed` assertion above, which matches the literal path.
            continue
        hits = [p for p in present if outside._to_regex(pattern).match(p)]
        assert hits, "no file on this tree matches hard-list pattern %r" % pattern


def test_the_ledger_rules_are_checked_against_the_proxy_s_own_layout():
    """Not against a literal retyped out of `outside.py` into this file.

    The adversarial review's sharpest point about the hard list: every
    assertion about `proxy/var/spend_gate.jsonl` compared a string in
    `outside.py` with the same string retyped here, so an upstream rename would
    leave all of them green while the rule protected nothing.

    `proxy/paths.py` is the authority -- "One module so no other file guesses at
    the layout" -- so the rules are checked against it. `spend_gate.jsonl` is
    not a constant there (the gate takes its ledger path from configuration),
    so what can be pinned is the directory and the sibling ledger, and that is
    what is pinned: move `VAR_DIR` and this goes red.
    """
    from proxy import paths

    var_rel = os.path.relpath(paths.VAR_DIR, REPO).replace(os.sep, "/")
    ledger_rel = os.path.relpath(paths.LEDGER_PATH, REPO).replace(os.sep, "/")

    assert outside.is_hard(ledger_rel), (
        "proxy.paths.LEDGER_PATH (%s) is not covered by the hard list" % ledger_rel)
    spend_gate = [p for p, _why in outside.ALL_HARD
                  if p.endswith("spend_gate.jsonl")]
    assert len(spend_gate) == 1, spend_gate
    assert spend_gate[0].startswith(var_rel + "/"), (
        "the hard list pins %r but proxy.paths.VAR_DIR is %r -- the rule is "
        "aimed at a directory the proxy no longer uses"
        % (spend_gate[0], var_rel))


def test_the_glob_matcher_does_not_leak_across_directories():
    """`*` must not cross `/`, or `arc-recon/data/*.jsonl` silently widens.

    `fnmatch` would let it, and on Windows would also fold case.  A hard list
    whose reach depends on the host OS is not a hard list.
    """
    assert outside.is_hard("arc-recon/data/incidents.jsonl")
    assert not outside.is_hard("arc-recon/data/sub/incidents.jsonl")
    assert outside.is_hard("CONTRACTS/candidates_schema.md")
    assert outside.is_hard("baseline-arms/out/shards/ledger.a7-g50t.jsonl")
    assert not outside.is_hard("ablation-arm/runs/x/ledger-notes.md")
    assert not outside.is_hard("proxy/var/some_other.jsonl")


def test_the_snapshot_does_not_inherit_the_pin_s_artifacts_blind_spot():
    """`pin.SKIP_DIRS` drops `artifacts/` and `runs/`; this must not.

    Half the audit's finding was that the worst-consequence paths were excluded
    by the criterion.  The other half is that some of them were never hashed at
    all, so no criterion could have reported them.
    """
    assert "artifacts" in pin.SKIP_DIRS and "runs" in pin.SKIP_DIRS
    assert "artifacts" not in outside.SKIP_DIRS
    assert "runs" not in outside.SKIP_DIRS

    seen = outside.snapshot()
    assert any("/artifacts/" in p for p in seen), "no upstream artifacts hashed"
    assert any("/runs/" in p for p in seen), "no upstream runs/ hashed"
    assert not any(p.startswith("ablation-arm/") for p in seen), \
        "the arm's own tree is inside the watch, so its own writes read as escapes"
    assert "PARTNER_SYNC.md" in seen, (
        "top-level files are not watched; a run that appended to the shared "
        "status board would pass this suite")
    assert not any(p.startswith(".pytest-runs/")
                   or "/.pytest-runs/" in p for p in seen), \
        "pytest's per-run temp dirs are being hashed as if they were territory"


def test_dotfiles_at_the_root_are_watched_because_one_of_them_is_the_key():
    """`.env` is the highest-consequence file in the repo and was not watched.

    `watched()` used to drop every top-level name beginning with `.`, which
    silently excluded `.env`, `.env.example`, `.gitignore` and `.gitattributes`
    -- while nested dot-directories were walked regardless, so the rule was not
    even consistent with itself. The adversarial review found it.

    Only sha256s are taken, never bytes, so watching `.env` cannot leak the key
    it holds; `CLAUDE.md`'s sealing discipline is about the value entering the
    repository, and a hash is what lets this notice a change without reading
    one.
    """
    seen = outside.snapshot()
    # `.git` is a *file* in a worktree (a gitdir pointer), not a directory, so
    # skipping by name rather than by type is what keeps it out.
    root_dotfiles = [n for n in os.listdir(REPO)
                     if n.startswith(".")
                     and n not in outside.SKIP_DIRS
                     and os.path.isfile(os.path.join(REPO, n))]
    missed = [n for n in root_dotfiles if n not in seen]
    assert missed == [], "top-level dotfiles not watched: %s" % missed
    assert ".gitignore" in seen, (
        "no top-level dotfile is watched at all, so this test is vacuous on "
        "this checkout")
    for skipped in (".git", ".worktrees"):
        assert not any(p.startswith(skipped + "/") for p in seen), skipped
