;; Sokoban level rnd0008. Generated by fixtures/sokoban.py -- do not edit.
;;
;;   ######
;;   #.#..#
;;   #..###
;;   #....#
;;   #...##
;;   ######
;;
;; player c13; boxes b1@c14, b2@c33; goals b1@c21, b2@c32
(define (problem sokoban-rnd0008)
  (:domain sokoban)
  (:objects
    c11 c13 c14 c21 c22 c31 c32 c33 c34 c41 c42 c43 - cell
    b1 b2 - box
    down left right up - dir)
  (:init
    (at-player c13)
    (at b1 c14)
    (at b2 c33)
    (clear c11)
    (clear c21)
    (clear c22)
    (clear c31)
    (clear c32)
    (clear c34)
    (clear c41)
    (clear c42)
    (clear c43)
    (adj c11 c21 down)
    (adj c13 c14 right)
    (adj c14 c13 left)
    (adj c21 c31 down)
    (adj c21 c22 right)
    (adj c21 c11 up)
    (adj c22 c32 down)
    (adj c22 c21 left)
    (adj c31 c41 down)
    (adj c31 c32 right)
    (adj c31 c21 up)
    (adj c32 c42 down)
    (adj c32 c31 left)
    (adj c32 c33 right)
    (adj c32 c22 up)
    (adj c33 c43 down)
    (adj c33 c32 left)
    (adj c33 c34 right)
    (adj c34 c33 left)
    (adj c41 c42 right)
    (adj c41 c31 up)
    (adj c42 c41 left)
    (adj c42 c43 right)
    (adj c42 c32 up)
    (adj c43 c42 left)
    (adj c43 c33 up))
  (:goal (and (at b1 c21) (at b2 c32))))
