"""The bill table — C3's evidence, generated from the meters rather than typed.

`A3_REPORT.md`'s central table is written by this module into
`artifacts/bill_table.md` and included by reference.  Nothing in it is
hand-entered: if an arm's cost changes, the table changes on the next run, and
a stale number cannot survive in the report.

The arms, in the order the table shows them:

| arm | level | books | what it establishes |
|---|---|---|---|
| `l1_cold_start` | 1 | none | the baseline — what a level costs from nothing |
| `l2_transfer` | 2 | **carried** | the claim |
| `l2_from_scratch` | 2 | none | the control — the same level, done the hard way |
| `l2_negctl_*` | 2′ | carried | the safety valve, on a domain that is wrong |

**Two ratios, and only one of them is the interesting one.**
`transfer ÷ l1_cold_start` compares a level-2 arm against a *level-1* baseline
and therefore mixes in whatever makes the two levels differ.
`transfer ÷ l2_from_scratch` is the like-for-like: same level, same goal, same
supplied constants, same certify, same planner — only the books differ.  The
report leads with the second and reports the first because it is the one
Theoria's C3 is phrased against ("第二关边际成本").
"""

import json
import os
import sys
from typing import Dict, List

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import _bootstrap  # noqa: F401,E402

from a3pipeline.meter import LINES, compare  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARTIFACTS = os.path.join(ROOT, "artifacts")

ORDER = ("l1_cold_start", "l2_from_scratch", "l2_transfer",
         "l2_negctl_oneway", "l2_negctl_rewired")

HEADLINE = ("world_frames", "world_actions", "engine_stages",
            "candidates_adjudicated", "theorize_rounds", "dsl_clauses_written")


def load_bills() -> List[Dict[str, object]]:
    bills = []
    for arm in ORDER:
        path = os.path.join(ARTIFACTS, "bill_%s.json" % arm)
        if os.path.exists(path):
            bills.append(json.load(open(path, encoding="utf-8")))
    return bills


def _ratio(numerator: int, denominator: int):
    if denominator == 0:
        return None
    return numerator / denominator


def build() -> Dict[str, object]:
    bills = load_bills()
    if not bills:
        raise SystemExit("no bills on disk — run the arms first")
    table = compare(bills)
    by_arm = {b["arm"]: b for b in bills}

    like_for_like = None
    if "l2_transfer" in by_arm and "l2_from_scratch" in by_arm:
        transfer = by_arm["l2_transfer"]["counts"]
        scratch = by_arm["l2_from_scratch"]["counts"]
        like_for_like = {
            line: {
                "l2_from_scratch": scratch[line],
                "l2_transfer": transfer[line],
                "ratio": _ratio(transfer[line], scratch[line]),
                "saved": scratch[line] - transfer[line],
            }
            for line in LINES
        }

    table["like_for_like_level_2"] = like_for_like
    table["note"] = (
        "Ratios against l1_cold_start compare across levels and therefore mix "
        "in whatever differs between them. The like-for-like block is the "
        "same level with and without the books, and is the number to quote."
    )

    out = os.path.join(ARTIFACTS, "bill_table.json")
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(json.dumps(table, indent=2, sort_keys=True) + "\n")
    return table


def markdown(table: Dict[str, object]) -> str:
    arms = [a["arm"] for a in table["arms"]]
    lines = ["<!-- generated by a3pipeline/bill.py — do not hand-edit -->", ""]
    lines.append("| meter line | " + " | ".join(arms) + " |")
    lines.append("|---" * (len(arms) + 1) + "|")
    for row in table["table"]:
        cells = [str(row.get(arm, "")) for arm in arms]
        lines.append("| `%s` | %s |" % (row["line"], " | ".join(cells)))

    lfl = table.get("like_for_like_level_2")
    if lfl:
        lines += ["", "**Level 2, like for like — same level, books or no books.**", ""]
        lines.append("| meter line | from scratch | with the books | ratio | saved |")
        lines.append("|---|---|---|---|---|")
        for line in LINES:
            row = lfl[line]
            ratio = row["ratio"]
            lines.append("| `%s` | %s | %s | %s | %s |" % (
                line, row["l2_from_scratch"], row["l2_transfer"],
                "n/a" if ratio is None else ("%.4g" % ratio), row["saved"]))

    first = table.get("cost_to_first_plan") or {}
    if first:
        lines += ["", "**Cost to first plan** — the snapshot taken the moment "
                  "a plan first existed.", ""]
        keys = [k for k in ORDER if first.get(k)]
        lines.append("| meter line | " + " | ".join(keys) + " |")
        lines.append("|---" * (len(keys) + 1) + "|")
        for line in HEADLINE:
            cells = [str(first[k].get(line, "")) for k in keys]
            lines.append("| `%s` | %s |" % (line, " | ".join(cells)))

    return "\n".join(lines) + "\n"


def main() -> int:
    table = build()
    text = markdown(table)
    out = os.path.join(ARTIFACTS, "bill_table.md")
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
